// Generated by Style Dictionary — do not edit
import SwiftUI

public extension Font {
    enum Tokens {
        public static func caption2() -> Font {
            .custom("SpaceGrotesk-Regular", size: 11.5, relativeTo: .caption2)
        }
        public static func caption() -> Font {
            .custom("SpaceGrotesk-Regular", size: 12.5, relativeTo: .caption)
        }
        public static func footnote() -> Font {
            .custom("SpaceGrotesk-Regular", size: 13.1, relativeTo: .footnote)
        }
        public static func body() -> Font {
            .custom("SpaceGrotesk-Regular", size: 13.1, relativeTo: .body)
        }
        public static func callout() -> Font {
            .custom("SpaceGrotesk-Regular", size: 13.1, relativeTo: .callout)
        }
        public static func subhead() -> Font {
            .custom("SpaceGrotesk-Medium", size: 16.8, relativeTo: .subheadline)
        }
        public static func headline() -> Font {
            .custom("SpaceGrotesk-SemiBold", size: 24, relativeTo: .headline)
        }
        public static func title3() -> Font {
            .custom("SpaceGrotesk-Bold", size: 32, relativeTo: .title3)
        }
        public static func title2() -> Font {
            .custom("SpaceGrotesk-Bold", size: 38.4, relativeTo: .title2)
        }
        public static func title1() -> Font {
            .custom("SpaceGrotesk-Bold", size: 42, relativeTo: .title)
        }
        public static func hero() -> Font {
            .custom("SpaceGrotesk-Bold", size: 35.2, relativeTo: .largeTitle)
        }
        public static func display() -> Font {
            .custom("SpaceGrotesk-Bold", size: 17, relativeTo: .body)
        }
        public static func heading1() -> Font {
            .custom("SpaceGrotesk-Bold", size: 17, relativeTo: .body)
        }
        public static func heading2() -> Font {
            .custom("SpaceGrotesk-SemiBold", size: 17, relativeTo: .body)
        }
        public static func label() -> Font {
            .custom("SpaceGrotesk-Medium", size: 17, relativeTo: .body)
        }
        public static func code() -> Font {
            .custom("SpaceGrotesk-Regular", size: 17, relativeTo: .body)
        }
    }
}
