// Generated by Style Dictionary — do not edit
import SwiftUI

/// Reduced-motion variants for all duration and easing tokens.
/// Use `ReducedMotion.duration` and `ReducedMotion.easing` in views that respect
/// the system accessibility setting `UIAccessibility.isReduceMotionEnabled`.
public enum ReducedMotion {
    public enum Duration {
        public static let all: Double = 0.0
    }
    public enum Easing {
        public static let linear: Animation = .linear(duration: 0)
    }
    /// Returns 0 if reduce-motion is enabled, otherwise returns the provided duration.
    @MainActor
    public static func duration(_ full: Double) -> Double {
        #if os(iOS) || os(tvOS)
        return UIAccessibility.isReduceMotionEnabled ? 0.0 : full
        #else
        return full
        #endif
    }
    /// Returns `.linear(duration: 0)` if reduce-motion is enabled, otherwise returns provided animation.
    @MainActor
    public static func animation(_ full: Animation) -> Animation {
        #if os(iOS) || os(tvOS)
        return UIAccessibility.isReduceMotionEnabled ? .linear(duration: 0) : full
        #else
        return full
        #endif
    }
}
