// Generated by Style Dictionary — do not edit
import CoreGraphics

public enum Spacing {
    public static let s50: CGFloat = 2
    public static let s100: CGFloat = 4
    public static let s150: CGFloat = 6
    public static let s200: CGFloat = 8
    public static let s250: CGFloat = 10
    public static let s300: CGFloat = 12
    public static let s350: CGFloat = 14
    public static let s400: CGFloat = 16
    public static let s450: CGFloat = 18
    public static let s500: CGFloat = 20
    public static let s600: CGFloat = 24
    public static let s700: CGFloat = 28
    public static let s800: CGFloat = 32
    public static let s900: CGFloat = 36
    public static let s1000: CGFloat = 40
    public static let s1200: CGFloat = 48
    public static let s1600: CGFloat = 64
}
