#!/usr/bin/env tsx
/**
 * codegen.ts — Lifegames Schema Codegen Pipeline
 *
 * Generates from 16 JSON schemas (10 vendored LP + 6 authored DS):
 *   - dist/types/{Name}.ts      — TypeScript interfaces via json-schema-to-typescript
 *   - dist/types/branded.ts     — SchemaDerived<T> brand type
 *   - dist/types/index.ts       — Re-exports all types wrapped in SchemaDerived<T>
 *   - swift/WidgetModels.swift  — Swift Codable structs via quicktype
 *   - fixture-map.json          — Fixture → schema → strategy mapping
 *
 * Idempotent: re-running produces byte-identical output.
 * Do NOT modify vendored/ or authored/ schemas from this script.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { execSync } from 'node:child_process';
import { compile } from 'json-schema-to-typescript';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const PKG_ROOT = join(__dirname, '..');
const VENDORED = join(PKG_ROOT, 'vendored');
const AUTHORED = join(PKG_ROOT, 'authored');
const DIST_TYPES = join(PKG_ROOT, 'dist', 'types');
const SWIFT_DIR = join(PKG_ROOT, 'swift');
const SWIFT_TEMP = join(SWIFT_DIR, 'temp');

/**
 * Authoritative naming map — LP schemas lack title/$id/description so we
 * provide names explicitly. Order is stable and determines index.ts export order.
 */
const SCHEMA_ENTRIES: Array<{ relPath: string; name: string }> = [
  { relPath: 'vendored/articles-export.schema.json',              name: 'ArticlesExport' },
  { relPath: 'vendored/books-export.schema.json',                 name: 'BooksExport' },
  { relPath: 'vendored/focus-export.schema.json',                 name: 'FocusExport' },
  { relPath: 'vendored/github-events-export.schema.json',         name: 'GithubEventsExport' },
  { relPath: 'vendored/github-starred-repos-export.schema.json',  name: 'GithubStarredReposExport' },
  { relPath: 'vendored/health-export.schema.json',                name: 'HealthExport' },
  { relPath: 'vendored/location-export.schema.json',              name: 'LocationExport' },
  { relPath: 'vendored/sleep-export.schema.json',                 name: 'SleepExport' },
  { relPath: 'vendored/theatre-reviews-export.schema.json',       name: 'TheatreReviewsExport' },
  { relPath: 'vendored/workouts-export.schema.json',              name: 'WorkoutsExport' },
  { relPath: 'authored/profile.schema.json',                      name: 'Profile' },
  { relPath: 'authored/system.schema.json',                       name: 'System' },
  { relPath: 'authored/dashboard-health.schema.json',             name: 'DashboardHealth' },
  { relPath: 'authored/dashboard-github.schema.json',             name: 'DashboardGithub' },
  { relPath: 'authored/dashboard-reading.schema.json',            name: 'DashboardReading' },
  { relPath: 'authored/dashboard-books.schema.json',              name: 'DashboardBooks' },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function ensureDir(p: string): void {
  mkdirSync(p, { recursive: true });
}

/** Read and parse a JSON schema file. */
function readSchema(absPath: string): object {
  return JSON.parse(readFileSync(absPath, 'utf-8'));
}

/**
 * Patch relative $ref paths in a schema object so json-schema-to-typescript
 * can resolve them using absolute file:// URIs.
 * Only dashboard-health.schema.json uses a cross-file $ref; handled generically.
 */
function patchRefs(schema: object, schemaAbsPath: string): object {
  const schemaDir = dirname(schemaAbsPath);
  const raw = JSON.stringify(schema);
  const patched = raw.replace(/"(\$ref)":\s*"([^"]+)"/g, (_match, key, ref) => {
    // Only patch relative file refs (not JSON Pointer-only refs like "#/...")
    if (ref.startsWith('#') || ref.startsWith('http') || ref.startsWith('file:')) {
      return `"${key}":"${ref}"`;
    }
    // Split on '#' to separate path from JSON pointer
    const [filePart, pointerPart] = ref.split('#');
    if (!filePart) return `"${key}":"${ref}"`; // pure JSON pointer, no file
    const absFile = join(schemaDir, filePart);
    const fileUri = `file://${absFile}`;
    const resolved = pointerPart ? `${fileUri}#${pointerPart}` : fileUri;
    return `"${key}":"${resolved}"`;
  });
  return JSON.parse(patched);
}

// ─── Step 1: Ensure output directories ───────────────────────────────────────

console.log('codegen: ensuring output directories...');
ensureDir(DIST_TYPES);
ensureDir(SWIFT_DIR);
ensureDir(SWIFT_TEMP);

// ─── Step 2: Write branded.ts ────────────────────────────────────────────────

console.log('codegen: writing branded.ts...');
const brandedContent = `// SchemaDerived brand — generated types are wrapped in this type alias
// to enforce W16 convention (widget Props MUST extend a schema-derived type).
// Do not modify this file manually — it is regenerated by scripts/codegen.ts.
declare const __schemaDerived: unique symbol;
export type SchemaDerived<T> = T & { readonly [__schemaDerived]: true };
`;
writeFileSync(join(DIST_TYPES, 'branded.ts'), brandedContent, 'utf-8');

// ─── Step 3: Generate TypeScript types ───────────────────────────────────────

console.log('codegen: generating TypeScript types...');

const generatedNames: string[] = [];

for (const { relPath, name } of SCHEMA_ENTRIES) {
  const absPath = join(PKG_ROOT, relPath);
  const raw = readSchema(absPath);
  const patched = patchRefs(raw, absPath);

  process.stdout.write(`  [TS] ${name} (${relPath})...`);

  const ts = await compile(patched as Parameters<typeof compile>[0], name, {
    bannerComment: '',
    additionalProperties: false,
    declareExternallyReferenced: true,
    unreachableDefinitions: false,
    enableConstEnums: false,
    strictIndexSignatures: false,
    style: { singleQuote: true },
  });

  // Prepend a generation notice
  const header = `// Generated by scripts/codegen.ts — do not edit manually.\n// Source: ${relPath}\n\n`;
  writeFileSync(join(DIST_TYPES, `${name}.ts`), header + ts, 'utf-8');
  generatedNames.push(name);
  console.log(' ok');
}

// ─── Step 4: Write index.ts ──────────────────────────────────────────────────

console.log('codegen: writing index.ts...');

const indexLines: string[] = [
  `// Generated by scripts/codegen.ts — do not edit manually.`,
  `// Re-exports all schema-derived types wrapped in SchemaDerived<T>.`,
  ``,
  `export type { SchemaDerived } from './branded';`,
  `import type { SchemaDerived } from './branded';`,
  ``,
];

for (const name of generatedNames) {
  indexLines.push(`import type { ${name} as _${name} } from './${name}';`);
}
indexLines.push('');
for (const name of generatedNames) {
  indexLines.push(`export type ${name} = SchemaDerived<_${name}>;`);
}
indexLines.push('');

writeFileSync(join(DIST_TYPES, 'index.ts'), indexLines.join('\n'), 'utf-8');

// ─── Step 5: Generate Swift (quicktype, per-schema → aggregate) ───────────────

console.log('codegen: generating Swift structs via quicktype...');

const QUICKTYPE_BIN = join(PKG_ROOT, 'node_modules', '.bin', 'quicktype');

const swiftParts: string[] = [];

for (const { relPath, name } of SCHEMA_ENTRIES) {
  const absPath = join(PKG_ROOT, relPath);
  const outFile = join(SWIFT_TEMP, `${name}.swift`);

  process.stdout.write(`  [Swift] ${name} (${relPath})...`);

  try {
    execSync(
      `"${QUICKTYPE_BIN}" --src-lang schema --lang swift --top-level ${name} -o "${outFile}" "${absPath}"`,
      { stdio: 'pipe' }
    );

    const content = readFileSync(outFile, 'utf-8');
    swiftParts.push(content);
    console.log(' ok');
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`\n  ERROR generating Swift for ${name}: ${msg}`);
    process.exit(1);
  }
}

// Aggregate: deduplicate `import Foundation` and shared helper functions,
// add per-schema section markers.
console.log('codegen: aggregating Swift output...');

const SWIFT_HEADER = `// Generated by scripts/codegen.ts — do not edit manually.
// Source: packages/schemas/{vendored,authored}/*.schema.json
// Re-run: pnpm -F @lifegames/schemas codegen
//
// Contains Codable structs for all 16 widget data schemas.
// Shared decoder helpers appear once at the end of this file.

import Foundation

`;

// Helper blocks that quicktype emits per-file but should appear only once.
// We collect them from the last file and dedup.
const HELPER_MARKERS = [
  'func newJSONDecoder()',
  'func newJSONEncoder()',
  'extension String:',
  '// Serialization extensions for types',
];

function isHelperLine(line: string): boolean {
  return HELPER_MARKERS.some(m => line.includes(m));
}

// Split each part into its sections: header comments + import, main structs/extensions, helpers
const structSections: string[] = [];
let sharedHelpersBlock = '';

for (let i = 0; i < swiftParts.length; i++) {
  const { name } = SCHEMA_ENTRIES[i];
  const lines = swiftParts[i].split('\n');

  // Drop the leading quicktype banner comment and `import Foundation`
  const contentLines: string[] = [];
  let pastHeader = false;
  let inHelpers = false;
  const helperLines: string[] = [];

  for (const line of lines) {
    // Skip the quicktype banner (lines starting with // This file was generated...)
    if (!pastHeader) {
      if (line.startsWith('import Foundation') || (line.trim() === '' && contentLines.length === 0)) {
        // Skip import Foundation (we have it in SWIFT_HEADER) and leading blanks
        if (line.startsWith('import Foundation')) {
          pastHeader = true;
        }
        continue;
      }
      if (line.startsWith('//')) {
        continue; // skip banner comment lines
      }
    }
    pastHeader = true;

    // Detect helper section start
    if (!inHelpers && isHelperLine(line)) {
      inHelpers = true;
    }

    if (inHelpers) {
      helperLines.push(line);
    } else {
      contentLines.push(line);
    }
  }

  // Store helpers from first schema that has them (they're identical across schemas)
  if (helperLines.length > 0 && sharedHelpersBlock === '') {
    sharedHelpersBlock = helperLines.join('\n');
  }

  const sectionContent = contentLines.join('\n').trim();
  if (sectionContent) {
    structSections.push(`// MARK: - Schema: ${name}\n\n${sectionContent}`);
  }
}

const aggregated = SWIFT_HEADER
  + structSections.join('\n\n')
  + '\n\n'
  + (sharedHelpersBlock ? '// MARK: - Shared Helpers\n\n' + sharedHelpersBlock + '\n' : '');

writeFileSync(join(SWIFT_DIR, 'WidgetModels.swift'), aggregated, 'utf-8');

// Clean up temp directory
for (const f of readdirSync(SWIFT_TEMP)) {
  rmSync(join(SWIFT_TEMP, f));
}
rmSync(SWIFT_TEMP, { recursive: true });

// ─── Step 6: Write fixture-map.json ──────────────────────────────────────────

console.log('codegen: writing fixture-map.json...');

const fixtureMap = {
  consumer: {
    'data/profile.json':                  { schema: 'Profile',               strategy: 'single' },
    'data/system.json':                   { schema: 'System',                strategy: 'single' },
    'data/health.json':                   { schema: 'DashboardHealth',       strategy: 'single' },
    'data/github.json':                   { schema: 'DashboardGithub',       strategy: 'single' },
    'data/reading.json':                  { schema: 'DashboardReading',      strategy: 'single' },
    'data/books.json':                    { schema: 'DashboardBooks',        strategy: 'single' },
    'data/theatre-reviews-sample.json':   { schema: 'TheatreReviewsExport',  strategy: 'single' },
  },
  ds: {
    _comment: 'DS-side widget showcase fixtures (Sources/LifegamesWidgets/Resources/widgets/) need per-widget schemas; see .omc/research/2026-05-25-schema-mismatches.md for the deferred follow-up plan.',
  },
};

// Stable serialization: JSON.stringify with sorted keys for idempotency
function sortedStringify(obj: unknown, indent = 2): string {
  return JSON.stringify(obj, (_key, value) => {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return Object.fromEntries(
        Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b))
      );
    }
    return value;
  }, indent);
}

writeFileSync(join(PKG_ROOT, 'fixture-map.json'), sortedStringify(fixtureMap) + '\n', 'utf-8');

// ─── Done ─────────────────────────────────────────────────────────────────────

console.log('');
console.log('codegen: complete.');
console.log(`  TS types:    dist/types/ (${generatedNames.length} schemas + branded.ts + index.ts)`);
console.log(`  Swift:       swift/WidgetModels.swift`);
console.log(`  Fixture map: fixture-map.json`);
