#!/usr/bin/env node
import { emitPlatform } from '../../scripts/emit-platform.mjs';

let failures = 0;

function assert(condition, message) {
  if (!condition) {
    console.error(`  FAIL: ${message}`);
    failures++;
  } else {
    console.log(`  pass: ${message}`);
  }
}

const sampleTokens = [
  { path: ['color', 'accent', 'pink'], $type: 'color', resolvedValue: '#ff006e' },
  { path: ['color', 'accent', 'indigo'], $type: 'color', resolvedValue: '#4f46e5' },
  { path: ['color', 'surface', 'base'], $type: 'color', resolvedValue: '#06060f' },
];

// --- Test 1: empty aliasMap ---
console.log('\nTest 1: empty aliasMap');
{
  const out = emitPlatform({ name: 'test', aliasMap: {}, tokens: sampleTokens });
  assert(out.includes(':root {'), 'contains :root block');
  assert(out.includes('/* Generated by Style Dictionary'), 'contains default header');
  assert(!out.includes('--'), 'no vars emitted for empty aliasMap');
}

// --- Test 2: alias chain resolution ---
console.log('\nTest 2: alias chain resolution');
{
  const aliasMap = {
    'test-primary': '{color.accent.pink}',
    'test-bg': '{color.surface.base}',
  };
  const out = emitPlatform({ name: 'test', aliasMap, tokens: sampleTokens });
  assert(out.includes('--test-primary: #ff006e;'), 'resolves color.accent.pink alias');
  assert(out.includes('--test-bg: #06060f;'), 'resolves color.surface.base alias');
}

// --- Test 3: missing-reference error path ---
console.log('\nTest 3: missing-reference error');
{
  const aliasMap = { 'test-missing': '{color.does.not.exist}' };
  let threw = false;
  try {
    emitPlatform({ name: 'test', aliasMap, tokens: sampleTokens });
  } catch (e) {
    threw = true;
    assert(
      e.message.includes('unresolved alias reference'),
      'error message mentions unresolved alias',
    );
  }
  assert(threw, 'throws on missing alias reference');
}

// --- Test 4: transform function applied ---
console.log('\nTest 4: transform function');
{
  const aliasMap = { 'test-accent': '{color.accent.pink}' };
  const transform = (value) => `transformed(${value})`;
  const out = emitPlatform({ name: 'test', aliasMap, tokens: sampleTokens, transform });
  assert(
    out.includes('--test-accent: transformed(#ff006e);'),
    'transform applied to resolved value',
  );
}

// --- Test 5: custom header ---
console.log('\nTest 5: custom header');
{
  const out = emitPlatform({
    name: 'test',
    aliasMap: {},
    tokens: sampleTokens,
    header: '/* custom header */\n',
  });
  assert(out.startsWith('/* custom header */'), 'custom header used');
  assert(!out.includes('Generated by Style Dictionary'), 'default header not present');
}

// --- Test 6: raw (non-reference) values in aliasMap ---
console.log('\nTest 6: raw values in aliasMap');
{
  const aliasMap = { 'test-raw': '#aabbcc' };
  const out = emitPlatform({ name: 'test', aliasMap, tokens: sampleTokens });
  assert(out.includes('--test-raw: #aabbcc;'), 'raw values emitted unchanged');
}

// --- Summary ---
console.log(`\n${failures === 0 ? 'All tests passed.' : `${failures} test(s) FAILED.`}`);
if (failures > 0) process.exit(1);
