// Generated by packages/copy/scripts/build.ts — do not edit manually.
// Source of truth: packages/copy/src/a11y.en-US.json (rich) → derived flat schema.
// Re-run: pnpm -F @j0nathan-ll0yd/copy build

import Foundation

/// Rich authoring schema for the a11y (accessibility) slice of @j0nathan-ll0yd/copy. Every
/// customer-facing accessibility string — aria-labels, image alt text, dialog labels, and
/// pagination/region labels — is a CopyString leaf carrying authoring context in _meta. The
/// two identity-slice a11y strings (skipToMain, ogImageAlt) intentionally remain in the
/// identity namespace and are NOT duplicated here. The copy build derives a FLAT schema from
/// this one (stripping _meta) for all consumer codegen (TS/Zod/Swift). Strings are authored
/// in ICU MessageFormat 1 syntax; interpolated templates are substituted at the call site
/// (no MessageFormat runtime). Casing is natural case: a11y copy needs no display
/// uppercasing transform. The $defs block is byte-identical to schema/identity.schema.json
/// and schema/widgets.schema.json; the $defs are inlined per schema file (no cross-file
/// $ref), which the flat-schema derivation requires.
// MARK: - Accessibility
public struct Accessibility: Codable, Sendable {
    /// Book detail modal accessibility label — the dialog region label.
    public let bookModal: A11YBookModal
    /// Bookshelf widget accessibility label — the per-book list-item aria-label template.
    public let bookshelf: A11YBookshelf
    /// Live clock accessibility label (web shell) — the top-bar current-time readout.
    public let clock: A11YClock
    /// Coffee tracking screen accessibility labels — hero mug, caffeine readout, daily bar, and
    /// primary action button states.
    public let coffee: A11YCoffee
    /// Identity card accessibility labels — the avatar image alt text and the social-links nav
    /// region label.
    public let identity: A11YIdentity
    /// Generic modal accessibility label — the close-button aria-label (shared modal chrome).
    public let modal: A11YModal
    /// Movement Rings widget accessibility labels — the rings progress summary and the daylight
    /// sun-arc image label.
    public let movement: A11YMovement
    /// Top-level navigation landmark labels (web shell) — profile aside and dashboard nav.
    public let nav: A11YNav
    /// 404 page accessibility label (web shell) — the glitch error region.
    public let page404: A11YPage404
    /// Reading Feed widget accessibility label — the article pagination button aria-label
    /// template.
    public let readingFeed: A11YReadingFeed
    /// Triptych column region landmark labels (web shell) — the Body and Mind sections.
    public let region: A11YRegion

    public init(bookModal: A11YBookModal, bookshelf: A11YBookshelf, clock: A11YClock, coffee: A11YCoffee, identity: A11YIdentity, modal: A11YModal, movement: A11YMovement, nav: A11YNav, page404: A11YPage404, readingFeed: A11YReadingFeed, region: A11YRegion) {
        self.bookModal = bookModal
        self.bookshelf = bookshelf
        self.clock = clock
        self.coffee = coffee
        self.identity = identity
        self.modal = modal
        self.movement = movement
        self.nav = nav
        self.page404 = page404
        self.readingFeed = readingFeed
        self.region = region
    }
}

// MARK: Accessibility convenience initializers and mutators

public extension Accessibility {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Accessibility.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        bookModal: A11YBookModal? = nil,
        bookshelf: A11YBookshelf? = nil,
        clock: A11YClock? = nil,
        coffee: A11YCoffee? = nil,
        identity: A11YIdentity? = nil,
        modal: A11YModal? = nil,
        movement: A11YMovement? = nil,
        nav: A11YNav? = nil,
        page404: A11YPage404? = nil,
        readingFeed: A11YReadingFeed? = nil,
        region: A11YRegion? = nil
    ) -> Accessibility {
        return Accessibility(
            bookModal: bookModal ?? self.bookModal,
            bookshelf: bookshelf ?? self.bookshelf,
            clock: clock ?? self.clock,
            coffee: coffee ?? self.coffee,
            identity: identity ?? self.identity,
            modal: modal ?? self.modal,
            movement: movement ?? self.movement,
            nav: nav ?? self.nav,
            page404: page404 ?? self.page404,
            readingFeed: readingFeed ?? self.readingFeed,
            region: region ?? self.region
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Book detail modal accessibility label — the dialog region label.
// MARK: - A11YBookModal
public struct A11YBookModal: Codable, Sendable {
    public let dialog: String

    public init(dialog: String) {
        self.dialog = dialog
    }
}

// MARK: A11YBookModal convenience initializers and mutators

public extension A11YBookModal {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YBookModal.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        dialog: String? = nil
    ) -> A11YBookModal {
        return A11YBookModal(
            dialog: dialog ?? self.dialog
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Bookshelf widget accessibility label — the per-book list-item aria-label template.
// MARK: - A11YBookshelf
public struct A11YBookshelf: Codable, Sendable {
    public let bookItem: String

    public init(bookItem: String) {
        self.bookItem = bookItem
    }
}

// MARK: A11YBookshelf convenience initializers and mutators

public extension A11YBookshelf {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YBookshelf.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        bookItem: String? = nil
    ) -> A11YBookshelf {
        return A11YBookshelf(
            bookItem: bookItem ?? self.bookItem
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Live clock accessibility label (web shell) — the top-bar current-time readout.
// MARK: - A11YClock
public struct A11YClock: Codable, Sendable {
    public let currentTime: String

    public init(currentTime: String) {
        self.currentTime = currentTime
    }
}

// MARK: A11YClock convenience initializers and mutators

public extension A11YClock {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YClock.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        currentTime: String? = nil
    ) -> A11YClock {
        return A11YClock(
            currentTime: currentTime ?? self.currentTime
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Coffee tracking screen accessibility labels — hero mug, caffeine readout, daily bar, and
/// primary action button states.
// MARK: - A11YCoffee
public struct A11YCoffee: Codable, Sendable {
    public let actionConnect, actionFinishCup, actionNewCup, actionReconnect: String
    public let actionSearching, caffeineThisCup, dailyCaffeine, mug: String

    public init(actionConnect: String, actionFinishCup: String, actionNewCup: String, actionReconnect: String, actionSearching: String, caffeineThisCup: String, dailyCaffeine: String, mug: String) {
        self.actionConnect = actionConnect
        self.actionFinishCup = actionFinishCup
        self.actionNewCup = actionNewCup
        self.actionReconnect = actionReconnect
        self.actionSearching = actionSearching
        self.caffeineThisCup = caffeineThisCup
        self.dailyCaffeine = dailyCaffeine
        self.mug = mug
    }
}

// MARK: A11YCoffee convenience initializers and mutators

public extension A11YCoffee {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YCoffee.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        actionConnect: String? = nil,
        actionFinishCup: String? = nil,
        actionNewCup: String? = nil,
        actionReconnect: String? = nil,
        actionSearching: String? = nil,
        caffeineThisCup: String? = nil,
        dailyCaffeine: String? = nil,
        mug: String? = nil
    ) -> A11YCoffee {
        return A11YCoffee(
            actionConnect: actionConnect ?? self.actionConnect,
            actionFinishCup: actionFinishCup ?? self.actionFinishCup,
            actionNewCup: actionNewCup ?? self.actionNewCup,
            actionReconnect: actionReconnect ?? self.actionReconnect,
            actionSearching: actionSearching ?? self.actionSearching,
            caffeineThisCup: caffeineThisCup ?? self.caffeineThisCup,
            dailyCaffeine: dailyCaffeine ?? self.dailyCaffeine,
            mug: mug ?? self.mug
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Identity card accessibility labels — the avatar image alt text and the social-links nav
/// region label.
// MARK: - A11YIdentity
public struct A11YIdentity: Codable, Sendable {
    public let avatarAlt, socialNav: String

    public init(avatarAlt: String, socialNav: String) {
        self.avatarAlt = avatarAlt
        self.socialNav = socialNav
    }
}

// MARK: A11YIdentity convenience initializers and mutators

public extension A11YIdentity {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YIdentity.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        avatarAlt: String? = nil,
        socialNav: String? = nil
    ) -> A11YIdentity {
        return A11YIdentity(
            avatarAlt: avatarAlt ?? self.avatarAlt,
            socialNav: socialNav ?? self.socialNav
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Generic modal accessibility label — the close-button aria-label (shared modal chrome).
// MARK: - A11YModal
public struct A11YModal: Codable, Sendable {
    public let close: String

    public init(close: String) {
        self.close = close
    }
}

// MARK: A11YModal convenience initializers and mutators

public extension A11YModal {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YModal.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        close: String? = nil
    ) -> A11YModal {
        return A11YModal(
            close: close ?? self.close
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Movement Rings widget accessibility labels — the rings progress summary and the daylight
/// sun-arc image label.
// MARK: - A11YMovement
public struct A11YMovement: Codable, Sendable {
    public let daylight, rings: String

    public init(daylight: String, rings: String) {
        self.daylight = daylight
        self.rings = rings
    }
}

// MARK: A11YMovement convenience initializers and mutators

public extension A11YMovement {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YMovement.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        daylight: String? = nil,
        rings: String? = nil
    ) -> A11YMovement {
        return A11YMovement(
            daylight: daylight ?? self.daylight,
            rings: rings ?? self.rings
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Top-level navigation landmark labels (web shell) — profile aside and dashboard nav.
// MARK: - A11YNav
public struct A11YNav: Codable, Sendable {
    public let dashboard, profile: String

    public init(dashboard: String, profile: String) {
        self.dashboard = dashboard
        self.profile = profile
    }
}

// MARK: A11YNav convenience initializers and mutators

public extension A11YNav {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YNav.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        dashboard: String? = nil,
        profile: String? = nil
    ) -> A11YNav {
        return A11YNav(
            dashboard: dashboard ?? self.dashboard,
            profile: profile ?? self.profile
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// 404 page accessibility label (web shell) — the glitch error region.
// MARK: - A11YPage404
public struct A11YPage404: Codable, Sendable {
    public let region: String

    public init(region: String) {
        self.region = region
    }
}

// MARK: A11YPage404 convenience initializers and mutators

public extension A11YPage404 {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YPage404.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        region: String? = nil
    ) -> A11YPage404 {
        return A11YPage404(
            region: region ?? self.region
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Reading Feed widget accessibility label — the article pagination button aria-label
/// template.
// MARK: - A11YReadingFeed
public struct A11YReadingFeed: Codable, Sendable {
    public let pagination: String

    public init(pagination: String) {
        self.pagination = pagination
    }
}

// MARK: A11YReadingFeed convenience initializers and mutators

public extension A11YReadingFeed {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YReadingFeed.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        pagination: String? = nil
    ) -> A11YReadingFeed {
        return A11YReadingFeed(
            pagination: pagination ?? self.pagination
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Triptych column region landmark labels (web shell) — the Body and Mind sections.
// MARK: - A11YRegion
public struct A11YRegion: Codable, Sendable {
    public let body, mind: String

    public init(body: String, mind: String) {
        self.body = body
        self.mind = mind
    }
}

// MARK: A11YRegion convenience initializers and mutators

public extension A11YRegion {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11YRegion.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        body: String? = nil,
        mind: String? = nil
    ) -> A11YRegion {
        return A11YRegion(
            body: body ?? self.body,
            mind: mind ?? self.mind
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}
