// Generated by packages/copy/scripts/build.ts — do not edit manually.
// Source of truth: packages/copy/src/app.en-US.json (rich) → derived flat schema.
// Re-run: pnpm -F @lifegames/copy build

import Foundation

/// Rich authoring schema for the app slice of @lifegames/copy. Every customer-facing UI
/// string in the iOS/watchOS LifePortal app — navigation titles, tab labels, section
/// headers, buttons, alerts, field labels, placeholders, and interpolated templates — is a
/// CopyString leaf carrying authoring context in _meta. Source of truth is
/// ios-LifegamesPortal/LifePortal/Packages/LifePortalFeatures/Sources/** (verified file:line
/// in each leaf's _meta.usage). The copy build derives a FLAT schema from this one
/// (stripping _meta) for all consumer codegen (TS/Zod/Swift). Strings are authored in ICU
/// MessageFormat 1 syntax; interpolated templates carry their ICU placeholders ({count},
/// {percent}, {relative}, …) and ICU plural syntax where the source pluralizes — consumers
/// keep their native plural logic. Stored in natural case: the app uppercases section
/// headers / buttons at the call site via .textCase / .kerning, so stored values are natural
/// case ('Sync Now', not 'SYNC NOW'). Every object group has a UNIQUE title (App* /
/// Perm-free App-prefixed) so quicktype-derived Swift struct names never collide across
/// namespaces. The $defs block is byte-identical to schema/identity.schema.json,
/// schema/widgets.schema.json, and schema/a11y.schema.json; the $defs are inlined per schema
/// file (no cross-file $ref), which the flat-schema derivation requires.
// MARK: - App
public struct App: Codable, Sendable {
    /// Add Saved Place sheet — header, field labels, placeholders, radius template, and
    /// coordinate tip.
    public let addPlace: AppAddPlace
    /// Bookshelf feature — list sections, dashboard tile, status labels, plus the add/edit book
    /// screens and bookshelf alerts.
    public let bookshelf: AppBookshelf
    /// Shared button/action labels reused across many screens (alert buttons, toolbar actions).
    public let common: AppCommon
    /// Health dashboard — section headers, workouts, HealthKit authorization, sync, and
    /// data-mode toggle.
    public let health: AppHealth
    /// Home dashboard strings — loading state, health/location summary cards, and the
    /// sync-status banner.
    public let home: AppHome
    /// Location feature — grouped by sub-screen (journey, visit correction, place rename, top
    /// places, heat map, today stats, week chart, now-at hero, merge, current-location ribbon,
    /// visit duration).
    public let location: AppLocation
    /// Navigation-bar titles for the app's primary screens (SwiftUI .navigationTitle).
    public let nav: AppNav
    /// 404 page chrome/SEO copy used on the web shell (404.astro) — document title and meta
    /// description.
    public let page404: AppPage404
    /// Saved Places list — empty state and per-row radius label.
    public let savedPlaces: AppSavedPlaces
    /// Dashboard triptych column header labels used on the web dashboard (index.astro).
    public let sections: AppSections
    /// Settings screen — section headers, server/data/diagnostics/about rows, buttons, and
    /// destructive-action alerts.
    public let settings: AppSettings
    /// Sleep-score entry sheet — title, prompt, placeholder, buttons, and a11y labels for the
    /// add/edit affordance.
    public let sleep: AppSleep
    /// Bottom tab-bar labels (TabView Label text).
    public let tab: AppTab
    /// watchOS app + sync-status complication — diagnostics chrome, sync action labels, and
    /// complication strings.
    public let watch: AppWatch

    public init(addPlace: AppAddPlace, bookshelf: AppBookshelf, common: AppCommon, health: AppHealth, home: AppHome, location: AppLocation, nav: AppNav, page404: AppPage404, savedPlaces: AppSavedPlaces, sections: AppSections, settings: AppSettings, sleep: AppSleep, tab: AppTab, watch: AppWatch) {
        self.addPlace = addPlace
        self.bookshelf = bookshelf
        self.common = common
        self.health = health
        self.home = home
        self.location = location
        self.nav = nav
        self.page404 = page404
        self.savedPlaces = savedPlaces
        self.sections = sections
        self.settings = settings
        self.sleep = sleep
        self.tab = tab
        self.watch = watch
    }
}

// MARK: App convenience initializers and mutators

public extension App {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(App.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        addPlace: AppAddPlace? = nil,
        bookshelf: AppBookshelf? = nil,
        common: AppCommon? = nil,
        health: AppHealth? = nil,
        home: AppHome? = nil,
        location: AppLocation? = nil,
        nav: AppNav? = nil,
        page404: AppPage404? = nil,
        savedPlaces: AppSavedPlaces? = nil,
        sections: AppSections? = nil,
        settings: AppSettings? = nil,
        sleep: AppSleep? = nil,
        tab: AppTab? = nil,
        watch: AppWatch? = nil
    ) -> App {
        return App(
            addPlace: addPlace ?? self.addPlace,
            bookshelf: bookshelf ?? self.bookshelf,
            common: common ?? self.common,
            health: health ?? self.health,
            home: home ?? self.home,
            location: location ?? self.location,
            nav: nav ?? self.nav,
            page404: page404 ?? self.page404,
            savedPlaces: savedPlaces ?? self.savedPlaces,
            sections: sections ?? self.sections,
            settings: settings ?? self.settings,
            sleep: sleep ?? self.sleep,
            tab: tab ?? self.tab,
            watch: watch ?? self.watch
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Add Saved Place sheet — header, field labels, placeholders, radius template, and
/// coordinate tip.
// MARK: - AppAddPlace
public struct AppAddPlace: Codable, Sendable {
    public let fieldCategory, fieldLatitude, fieldLongitude, fieldName: String
    public let fieldNamePlaceholder, fieldRadius, sectionNewLocation, tip: String
    public let title: String

    public init(fieldCategory: String, fieldLatitude: String, fieldLongitude: String, fieldName: String, fieldNamePlaceholder: String, fieldRadius: String, sectionNewLocation: String, tip: String, title: String) {
        self.fieldCategory = fieldCategory
        self.fieldLatitude = fieldLatitude
        self.fieldLongitude = fieldLongitude
        self.fieldName = fieldName
        self.fieldNamePlaceholder = fieldNamePlaceholder
        self.fieldRadius = fieldRadius
        self.sectionNewLocation = sectionNewLocation
        self.tip = tip
        self.title = title
    }
}

// MARK: AppAddPlace convenience initializers and mutators

public extension AppAddPlace {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppAddPlace.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        fieldCategory: String? = nil,
        fieldLatitude: String? = nil,
        fieldLongitude: String? = nil,
        fieldName: String? = nil,
        fieldNamePlaceholder: String? = nil,
        fieldRadius: String? = nil,
        sectionNewLocation: String? = nil,
        tip: String? = nil,
        title: String? = nil
    ) -> AppAddPlace {
        return AppAddPlace(
            fieldCategory: fieldCategory ?? self.fieldCategory,
            fieldLatitude: fieldLatitude ?? self.fieldLatitude,
            fieldLongitude: fieldLongitude ?? self.fieldLongitude,
            fieldName: fieldName ?? self.fieldName,
            fieldNamePlaceholder: fieldNamePlaceholder ?? self.fieldNamePlaceholder,
            fieldRadius: fieldRadius ?? self.fieldRadius,
            sectionNewLocation: sectionNewLocation ?? self.sectionNewLocation,
            tip: tip ?? self.tip,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Bookshelf feature — list sections, dashboard tile, status labels, plus the add/edit book
/// screens and bookshelf alerts.
// MARK: - AppBookshelf
public struct AppBookshelf: Codable, Sendable {
    /// Add Book search screen — title, search placeholder, empty prompt, ASIN template, add
    /// button.
    public let addBook: AppBookshelfAddBook
    /// Bookshelf error-alert titles (load/add/update/delete failures).
    public let alerts: AppBookshelfAlerts
    public let currentlyReading: String
    /// Edit Book screen — title, buttons, placeholders, section headers, and metadata field
    /// labels.
    public let editBook: AppBookshelfEditBook
    public let enriching, navTitle, pageOf, pages: String
    public let sectionPending, sectionRecentlyFinished, sectionUpNext, statusFinished: String
    public let statusPending, statusReading, statusUpNext, tileBooks: String
    public let tileComplete, tileHeader, tileReading: String

    public init(addBook: AppBookshelfAddBook, alerts: AppBookshelfAlerts, currentlyReading: String, editBook: AppBookshelfEditBook, enriching: String, navTitle: String, pageOf: String, pages: String, sectionPending: String, sectionRecentlyFinished: String, sectionUpNext: String, statusFinished: String, statusPending: String, statusReading: String, statusUpNext: String, tileBooks: String, tileComplete: String, tileHeader: String, tileReading: String) {
        self.addBook = addBook
        self.alerts = alerts
        self.currentlyReading = currentlyReading
        self.editBook = editBook
        self.enriching = enriching
        self.navTitle = navTitle
        self.pageOf = pageOf
        self.pages = pages
        self.sectionPending = sectionPending
        self.sectionRecentlyFinished = sectionRecentlyFinished
        self.sectionUpNext = sectionUpNext
        self.statusFinished = statusFinished
        self.statusPending = statusPending
        self.statusReading = statusReading
        self.statusUpNext = statusUpNext
        self.tileBooks = tileBooks
        self.tileComplete = tileComplete
        self.tileHeader = tileHeader
        self.tileReading = tileReading
    }
}

// MARK: AppBookshelf convenience initializers and mutators

public extension AppBookshelf {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppBookshelf.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        addBook: AppBookshelfAddBook? = nil,
        alerts: AppBookshelfAlerts? = nil,
        currentlyReading: String? = nil,
        editBook: AppBookshelfEditBook? = nil,
        enriching: String? = nil,
        navTitle: String? = nil,
        pageOf: String? = nil,
        pages: String? = nil,
        sectionPending: String? = nil,
        sectionRecentlyFinished: String? = nil,
        sectionUpNext: String? = nil,
        statusFinished: String? = nil,
        statusPending: String? = nil,
        statusReading: String? = nil,
        statusUpNext: String? = nil,
        tileBooks: String? = nil,
        tileComplete: String? = nil,
        tileHeader: String? = nil,
        tileReading: String? = nil
    ) -> AppBookshelf {
        return AppBookshelf(
            addBook: addBook ?? self.addBook,
            alerts: alerts ?? self.alerts,
            currentlyReading: currentlyReading ?? self.currentlyReading,
            editBook: editBook ?? self.editBook,
            enriching: enriching ?? self.enriching,
            navTitle: navTitle ?? self.navTitle,
            pageOf: pageOf ?? self.pageOf,
            pages: pages ?? self.pages,
            sectionPending: sectionPending ?? self.sectionPending,
            sectionRecentlyFinished: sectionRecentlyFinished ?? self.sectionRecentlyFinished,
            sectionUpNext: sectionUpNext ?? self.sectionUpNext,
            statusFinished: statusFinished ?? self.statusFinished,
            statusPending: statusPending ?? self.statusPending,
            statusReading: statusReading ?? self.statusReading,
            statusUpNext: statusUpNext ?? self.statusUpNext,
            tileBooks: tileBooks ?? self.tileBooks,
            tileComplete: tileComplete ?? self.tileComplete,
            tileHeader: tileHeader ?? self.tileHeader,
            tileReading: tileReading ?? self.tileReading
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Add Book search screen — title, search placeholder, empty prompt, ASIN template, add
/// button.
// MARK: - AppBookshelfAddBook
public struct AppBookshelfAddBook: Codable, Sendable {
    public let add, asin, emptyPrompt, searchPlaceholder: String
    public let title: String

    public init(add: String, asin: String, emptyPrompt: String, searchPlaceholder: String, title: String) {
        self.add = add
        self.asin = asin
        self.emptyPrompt = emptyPrompt
        self.searchPlaceholder = searchPlaceholder
        self.title = title
    }
}

// MARK: AppBookshelfAddBook convenience initializers and mutators

public extension AppBookshelfAddBook {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppBookshelfAddBook.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        add: String? = nil,
        asin: String? = nil,
        emptyPrompt: String? = nil,
        searchPlaceholder: String? = nil,
        title: String? = nil
    ) -> AppBookshelfAddBook {
        return AppBookshelfAddBook(
            add: add ?? self.add,
            asin: asin ?? self.asin,
            emptyPrompt: emptyPrompt ?? self.emptyPrompt,
            searchPlaceholder: searchPlaceholder ?? self.searchPlaceholder,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Bookshelf error-alert titles (load/add/update/delete failures).
// MARK: - AppBookshelfAlerts
public struct AppBookshelfAlerts: Codable, Sendable {
    public let failedToAddBook, failedToDelete, failedToLoad, failedToUpdate: String

    public init(failedToAddBook: String, failedToDelete: String, failedToLoad: String, failedToUpdate: String) {
        self.failedToAddBook = failedToAddBook
        self.failedToDelete = failedToDelete
        self.failedToLoad = failedToLoad
        self.failedToUpdate = failedToUpdate
    }
}

// MARK: AppBookshelfAlerts convenience initializers and mutators

public extension AppBookshelfAlerts {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppBookshelfAlerts.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        failedToAddBook: String? = nil,
        failedToDelete: String? = nil,
        failedToLoad: String? = nil,
        failedToUpdate: String? = nil
    ) -> AppBookshelfAlerts {
        return AppBookshelfAlerts(
            failedToAddBook: failedToAddBook ?? self.failedToAddBook,
            failedToDelete: failedToDelete ?? self.failedToDelete,
            failedToLoad: failedToLoad ?? self.failedToLoad,
            failedToUpdate: failedToUpdate ?? self.failedToUpdate
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Edit Book screen — title, buttons, placeholders, section headers, and metadata field
/// labels.
// MARK: - AppBookshelfEditBook
public struct AppBookshelfEditBook: Codable, Sendable {
    public let delete, descriptionPlaceholder, fieldDate, fieldDatePlaceholder: String
    public let fieldGenres, fieldGenresPlaceholder, fieldSeries, fieldSeriesNum: String
    public let fieldSeriesPlaceholder, fieldSeriesTotal, fieldYear, notesPlaceholder: String
    public let of, page, save, sectionCategories: String
    public let sectionDescription, sectionDetails, sectionNotes, sectionProgress: String
    public let sectionPublication, sectionRating, sectionStatus, title: String

    public init(delete: String, descriptionPlaceholder: String, fieldDate: String, fieldDatePlaceholder: String, fieldGenres: String, fieldGenresPlaceholder: String, fieldSeries: String, fieldSeriesNum: String, fieldSeriesPlaceholder: String, fieldSeriesTotal: String, fieldYear: String, notesPlaceholder: String, of: String, page: String, save: String, sectionCategories: String, sectionDescription: String, sectionDetails: String, sectionNotes: String, sectionProgress: String, sectionPublication: String, sectionRating: String, sectionStatus: String, title: String) {
        self.delete = delete
        self.descriptionPlaceholder = descriptionPlaceholder
        self.fieldDate = fieldDate
        self.fieldDatePlaceholder = fieldDatePlaceholder
        self.fieldGenres = fieldGenres
        self.fieldGenresPlaceholder = fieldGenresPlaceholder
        self.fieldSeries = fieldSeries
        self.fieldSeriesNum = fieldSeriesNum
        self.fieldSeriesPlaceholder = fieldSeriesPlaceholder
        self.fieldSeriesTotal = fieldSeriesTotal
        self.fieldYear = fieldYear
        self.notesPlaceholder = notesPlaceholder
        self.of = of
        self.page = page
        self.save = save
        self.sectionCategories = sectionCategories
        self.sectionDescription = sectionDescription
        self.sectionDetails = sectionDetails
        self.sectionNotes = sectionNotes
        self.sectionProgress = sectionProgress
        self.sectionPublication = sectionPublication
        self.sectionRating = sectionRating
        self.sectionStatus = sectionStatus
        self.title = title
    }
}

// MARK: AppBookshelfEditBook convenience initializers and mutators

public extension AppBookshelfEditBook {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppBookshelfEditBook.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        delete: String? = nil,
        descriptionPlaceholder: String? = nil,
        fieldDate: String? = nil,
        fieldDatePlaceholder: String? = nil,
        fieldGenres: String? = nil,
        fieldGenresPlaceholder: String? = nil,
        fieldSeries: String? = nil,
        fieldSeriesNum: String? = nil,
        fieldSeriesPlaceholder: String? = nil,
        fieldSeriesTotal: String? = nil,
        fieldYear: String? = nil,
        notesPlaceholder: String? = nil,
        of: String? = nil,
        page: String? = nil,
        save: String? = nil,
        sectionCategories: String? = nil,
        sectionDescription: String? = nil,
        sectionDetails: String? = nil,
        sectionNotes: String? = nil,
        sectionProgress: String? = nil,
        sectionPublication: String? = nil,
        sectionRating: String? = nil,
        sectionStatus: String? = nil,
        title: String? = nil
    ) -> AppBookshelfEditBook {
        return AppBookshelfEditBook(
            delete: delete ?? self.delete,
            descriptionPlaceholder: descriptionPlaceholder ?? self.descriptionPlaceholder,
            fieldDate: fieldDate ?? self.fieldDate,
            fieldDatePlaceholder: fieldDatePlaceholder ?? self.fieldDatePlaceholder,
            fieldGenres: fieldGenres ?? self.fieldGenres,
            fieldGenresPlaceholder: fieldGenresPlaceholder ?? self.fieldGenresPlaceholder,
            fieldSeries: fieldSeries ?? self.fieldSeries,
            fieldSeriesNum: fieldSeriesNum ?? self.fieldSeriesNum,
            fieldSeriesPlaceholder: fieldSeriesPlaceholder ?? self.fieldSeriesPlaceholder,
            fieldSeriesTotal: fieldSeriesTotal ?? self.fieldSeriesTotal,
            fieldYear: fieldYear ?? self.fieldYear,
            notesPlaceholder: notesPlaceholder ?? self.notesPlaceholder,
            of: of ?? self.of,
            page: page ?? self.page,
            save: save ?? self.save,
            sectionCategories: sectionCategories ?? self.sectionCategories,
            sectionDescription: sectionDescription ?? self.sectionDescription,
            sectionDetails: sectionDetails ?? self.sectionDetails,
            sectionNotes: sectionNotes ?? self.sectionNotes,
            sectionProgress: sectionProgress ?? self.sectionProgress,
            sectionPublication: sectionPublication ?? self.sectionPublication,
            sectionRating: sectionRating ?? self.sectionRating,
            sectionStatus: sectionStatus ?? self.sectionStatus,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Shared button/action labels reused across many screens (alert buttons, toolbar actions).
// MARK: - AppCommon
public struct AppCommon: Codable, Sendable {
    public let add, cancel, clear, delete: String
    public let done, ok, save: String

    public init(add: String, cancel: String, clear: String, delete: String, done: String, ok: String, save: String) {
        self.add = add
        self.cancel = cancel
        self.clear = clear
        self.delete = delete
        self.done = done
        self.ok = ok
        self.save = save
    }
}

// MARK: AppCommon convenience initializers and mutators

public extension AppCommon {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppCommon.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        add: String? = nil,
        cancel: String? = nil,
        clear: String? = nil,
        delete: String? = nil,
        done: String? = nil,
        ok: String? = nil,
        save: String? = nil
    ) -> AppCommon {
        return AppCommon(
            add: add ?? self.add,
            cancel: cancel ?? self.cancel,
            clear: clear ?? self.clear,
            delete: delete ?? self.delete,
            done: done ?? self.done,
            ok: ok ?? self.ok,
            save: save ?? self.save
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Health dashboard — section headers, workouts, HealthKit authorization, sync, and
/// data-mode toggle.
// MARK: - AppHealth
public struct AppHealth: Codable, Sendable {
    public let authorization, authorized, lastSync, noWorkouts: String
    public let realActive, recoveryDay, sectionData, sectionDataMode: String
    public let sectionHealthkit, sectionHeart, sectionMovement, sectionSleep: String
    public let sectionWorkouts, simActive, syncing, syncNow: String
    public let todaysWorkouts, useRealHR, workoutCalories, workoutDuration: String

    public init(authorization: String, authorized: String, lastSync: String, noWorkouts: String, realActive: String, recoveryDay: String, sectionData: String, sectionDataMode: String, sectionHealthkit: String, sectionHeart: String, sectionMovement: String, sectionSleep: String, sectionWorkouts: String, simActive: String, syncing: String, syncNow: String, todaysWorkouts: String, useRealHR: String, workoutCalories: String, workoutDuration: String) {
        self.authorization = authorization
        self.authorized = authorized
        self.lastSync = lastSync
        self.noWorkouts = noWorkouts
        self.realActive = realActive
        self.recoveryDay = recoveryDay
        self.sectionData = sectionData
        self.sectionDataMode = sectionDataMode
        self.sectionHealthkit = sectionHealthkit
        self.sectionHeart = sectionHeart
        self.sectionMovement = sectionMovement
        self.sectionSleep = sectionSleep
        self.sectionWorkouts = sectionWorkouts
        self.simActive = simActive
        self.syncing = syncing
        self.syncNow = syncNow
        self.todaysWorkouts = todaysWorkouts
        self.useRealHR = useRealHR
        self.workoutCalories = workoutCalories
        self.workoutDuration = workoutDuration
    }
}

// MARK: AppHealth convenience initializers and mutators

public extension AppHealth {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppHealth.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        authorization: String? = nil,
        authorized: String? = nil,
        lastSync: String? = nil,
        noWorkouts: String? = nil,
        realActive: String? = nil,
        recoveryDay: String? = nil,
        sectionData: String? = nil,
        sectionDataMode: String? = nil,
        sectionHealthkit: String? = nil,
        sectionHeart: String? = nil,
        sectionMovement: String? = nil,
        sectionSleep: String? = nil,
        sectionWorkouts: String? = nil,
        simActive: String? = nil,
        syncing: String? = nil,
        syncNow: String? = nil,
        todaysWorkouts: String? = nil,
        useRealHR: String? = nil,
        workoutCalories: String? = nil,
        workoutDuration: String? = nil
    ) -> AppHealth {
        return AppHealth(
            authorization: authorization ?? self.authorization,
            authorized: authorized ?? self.authorized,
            lastSync: lastSync ?? self.lastSync,
            noWorkouts: noWorkouts ?? self.noWorkouts,
            realActive: realActive ?? self.realActive,
            recoveryDay: recoveryDay ?? self.recoveryDay,
            sectionData: sectionData ?? self.sectionData,
            sectionDataMode: sectionDataMode ?? self.sectionDataMode,
            sectionHealthkit: sectionHealthkit ?? self.sectionHealthkit,
            sectionHeart: sectionHeart ?? self.sectionHeart,
            sectionMovement: sectionMovement ?? self.sectionMovement,
            sectionSleep: sectionSleep ?? self.sectionSleep,
            sectionWorkouts: sectionWorkouts ?? self.sectionWorkouts,
            simActive: simActive ?? self.simActive,
            syncing: syncing ?? self.syncing,
            syncNow: syncNow ?? self.syncNow,
            todaysWorkouts: todaysWorkouts ?? self.todaysWorkouts,
            useRealHR: useRealHR ?? self.useRealHR,
            workoutCalories: workoutCalories ?? self.workoutCalories,
            workoutDuration: workoutDuration ?? self.workoutDuration
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Home dashboard strings — loading state, health/location summary cards, and the
/// sync-status banner.
// MARK: - AppHome
public struct AppHome: Codable, Sendable {
    public let goalProgress, loading, noLocation, notSynced: String
    public let notTracking, sectionHealth, sectionLocation, stepsUnit: String
    public let syncStatus, tracking, unsynced, visitsToday: String

    public init(goalProgress: String, loading: String, noLocation: String, notSynced: String, notTracking: String, sectionHealth: String, sectionLocation: String, stepsUnit: String, syncStatus: String, tracking: String, unsynced: String, visitsToday: String) {
        self.goalProgress = goalProgress
        self.loading = loading
        self.noLocation = noLocation
        self.notSynced = notSynced
        self.notTracking = notTracking
        self.sectionHealth = sectionHealth
        self.sectionLocation = sectionLocation
        self.stepsUnit = stepsUnit
        self.syncStatus = syncStatus
        self.tracking = tracking
        self.unsynced = unsynced
        self.visitsToday = visitsToday
    }
}

// MARK: AppHome convenience initializers and mutators

public extension AppHome {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppHome.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        goalProgress: String? = nil,
        loading: String? = nil,
        noLocation: String? = nil,
        notSynced: String? = nil,
        notTracking: String? = nil,
        sectionHealth: String? = nil,
        sectionLocation: String? = nil,
        stepsUnit: String? = nil,
        syncStatus: String? = nil,
        tracking: String? = nil,
        unsynced: String? = nil,
        visitsToday: String? = nil
    ) -> AppHome {
        return AppHome(
            goalProgress: goalProgress ?? self.goalProgress,
            loading: loading ?? self.loading,
            noLocation: noLocation ?? self.noLocation,
            notSynced: notSynced ?? self.notSynced,
            notTracking: notTracking ?? self.notTracking,
            sectionHealth: sectionHealth ?? self.sectionHealth,
            sectionLocation: sectionLocation ?? self.sectionLocation,
            stepsUnit: stepsUnit ?? self.stepsUnit,
            syncStatus: syncStatus ?? self.syncStatus,
            tracking: tracking ?? self.tracking,
            unsynced: unsynced ?? self.unsynced,
            visitsToday: visitsToday ?? self.visitsToday
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Location feature — grouped by sub-screen (journey, visit correction, place rename, top
/// places, heat map, today stats, week chart, now-at hero, merge, current-location ribbon,
/// visit duration).
// MARK: - AppLocation
public struct AppLocation: Codable, Sendable {
    /// Activity Map card + full screen — header, legend, totals, and scale template.
    public let heatMap: AppLocationHeatMap
    /// Journey timeline screen — empty state, per-visit actions, and the delete-visit alert.
    public let journey: AppLocationJourney
    /// Merge Visits sheet — header, keep/absorb/result labels, and merged-samples template.
    public let merge: AppLocationMerge
    /// Now-At hero card — contextual header labels and fallbacks for current/last location.
    public let nowAt: AppLocationNowAt
    /// Place Rename sheet — title, subtitle template, success template, fields.
    public let placeRename: AppLocationPlaceRename
    /// Current-location ribbon — staleness prefix, proximity template, and exploring fallback.
    public let ribbon: AppLocationRibbon
    /// Today stats row — the three stat-cell labels.
    public let todayStats: AppLocationTodayStats
    /// Top Places card + full screen — header, counts, empty state, sort options, and per-place
    /// actions.
    public let topPlaces: AppLocationTopPlaces
    /// Visit Correction sheet — header, tab hints, time pickers, and confirm button.
    public let visitCorrection: AppLocationVisitCorrection
    /// Visit-duration fallbacks — in-progress label for an ongoing (not-yet-departed) visit.
    public let visitDuration: AppLocationVisitDuration
    /// This-week bar chart — header and total-visits template.
    public let weekChart: AppLocationWeekChart

    public init(heatMap: AppLocationHeatMap, journey: AppLocationJourney, merge: AppLocationMerge, nowAt: AppLocationNowAt, placeRename: AppLocationPlaceRename, ribbon: AppLocationRibbon, todayStats: AppLocationTodayStats, topPlaces: AppLocationTopPlaces, visitCorrection: AppLocationVisitCorrection, visitDuration: AppLocationVisitDuration, weekChart: AppLocationWeekChart) {
        self.heatMap = heatMap
        self.journey = journey
        self.merge = merge
        self.nowAt = nowAt
        self.placeRename = placeRename
        self.ribbon = ribbon
        self.todayStats = todayStats
        self.topPlaces = topPlaces
        self.visitCorrection = visitCorrection
        self.visitDuration = visitDuration
        self.weekChart = weekChart
    }
}

// MARK: AppLocation convenience initializers and mutators

public extension AppLocation {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocation.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        heatMap: AppLocationHeatMap? = nil,
        journey: AppLocationJourney? = nil,
        merge: AppLocationMerge? = nil,
        nowAt: AppLocationNowAt? = nil,
        placeRename: AppLocationPlaceRename? = nil,
        ribbon: AppLocationRibbon? = nil,
        todayStats: AppLocationTodayStats? = nil,
        topPlaces: AppLocationTopPlaces? = nil,
        visitCorrection: AppLocationVisitCorrection? = nil,
        visitDuration: AppLocationVisitDuration? = nil,
        weekChart: AppLocationWeekChart? = nil
    ) -> AppLocation {
        return AppLocation(
            heatMap: heatMap ?? self.heatMap,
            journey: journey ?? self.journey,
            merge: merge ?? self.merge,
            nowAt: nowAt ?? self.nowAt,
            placeRename: placeRename ?? self.placeRename,
            ribbon: ribbon ?? self.ribbon,
            todayStats: todayStats ?? self.todayStats,
            topPlaces: topPlaces ?? self.topPlaces,
            visitCorrection: visitCorrection ?? self.visitCorrection,
            visitDuration: visitDuration ?? self.visitDuration,
            weekChart: weekChart ?? self.weekChart
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Activity Map card + full screen — header, legend, totals, and scale template.
// MARK: - AppLocationHeatMap
public struct AppLocationHeatMap: Codable, Sendable {
    public let header, legendLess, legendMore, scale: String
    public let seeMonth, totalVisits: String

    public init(header: String, legendLess: String, legendMore: String, scale: String, seeMonth: String, totalVisits: String) {
        self.header = header
        self.legendLess = legendLess
        self.legendMore = legendMore
        self.scale = scale
        self.seeMonth = seeMonth
        self.totalVisits = totalVisits
    }
}

// MARK: AppLocationHeatMap convenience initializers and mutators

public extension AppLocationHeatMap {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationHeatMap.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        header: String? = nil,
        legendLess: String? = nil,
        legendMore: String? = nil,
        scale: String? = nil,
        seeMonth: String? = nil,
        totalVisits: String? = nil
    ) -> AppLocationHeatMap {
        return AppLocationHeatMap(
            header: header ?? self.header,
            legendLess: legendLess ?? self.legendLess,
            legendMore: legendMore ?? self.legendMore,
            scale: scale ?? self.scale,
            seeMonth: seeMonth ?? self.seeMonth,
            totalVisits: totalVisits ?? self.totalVisits
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Journey timeline screen — empty state, per-visit actions, and the delete-visit alert.
// MARK: - AppLocationJourney
public struct AppLocationJourney: Codable, Sendable {
    public let actionCorrect, actionDelete, actionMerge, actionSavePlace: String
    public let deleteVisitMessage, deleteVisitTitle, emptyMessage, emptyTitle: String
    public let mapUnavailable, placesVisited, unknown, viewYesterday: String
    public let visitFallback: String

    public init(actionCorrect: String, actionDelete: String, actionMerge: String, actionSavePlace: String, deleteVisitMessage: String, deleteVisitTitle: String, emptyMessage: String, emptyTitle: String, mapUnavailable: String, placesVisited: String, unknown: String, viewYesterday: String, visitFallback: String) {
        self.actionCorrect = actionCorrect
        self.actionDelete = actionDelete
        self.actionMerge = actionMerge
        self.actionSavePlace = actionSavePlace
        self.deleteVisitMessage = deleteVisitMessage
        self.deleteVisitTitle = deleteVisitTitle
        self.emptyMessage = emptyMessage
        self.emptyTitle = emptyTitle
        self.mapUnavailable = mapUnavailable
        self.placesVisited = placesVisited
        self.unknown = unknown
        self.viewYesterday = viewYesterday
        self.visitFallback = visitFallback
    }
}

// MARK: AppLocationJourney convenience initializers and mutators

public extension AppLocationJourney {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationJourney.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        actionCorrect: String? = nil,
        actionDelete: String? = nil,
        actionMerge: String? = nil,
        actionSavePlace: String? = nil,
        deleteVisitMessage: String? = nil,
        deleteVisitTitle: String? = nil,
        emptyMessage: String? = nil,
        emptyTitle: String? = nil,
        mapUnavailable: String? = nil,
        placesVisited: String? = nil,
        unknown: String? = nil,
        viewYesterday: String? = nil,
        visitFallback: String? = nil
    ) -> AppLocationJourney {
        return AppLocationJourney(
            actionCorrect: actionCorrect ?? self.actionCorrect,
            actionDelete: actionDelete ?? self.actionDelete,
            actionMerge: actionMerge ?? self.actionMerge,
            actionSavePlace: actionSavePlace ?? self.actionSavePlace,
            deleteVisitMessage: deleteVisitMessage ?? self.deleteVisitMessage,
            deleteVisitTitle: deleteVisitTitle ?? self.deleteVisitTitle,
            emptyMessage: emptyMessage ?? self.emptyMessage,
            emptyTitle: emptyTitle ?? self.emptyTitle,
            mapUnavailable: mapUnavailable ?? self.mapUnavailable,
            placesVisited: placesVisited ?? self.placesVisited,
            unknown: unknown ?? self.unknown,
            viewYesterday: viewYesterday ?? self.viewYesterday,
            visitFallback: visitFallback ?? self.visitFallback
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Merge Visits sheet — header, keep/absorb/result labels, and merged-samples template.
// MARK: - AppLocationMerge
public struct AppLocationMerge: Codable, Sendable {
    public let absorb, combining, keep, result: String
    public let samplesMerged, subtitle, title: String

    public init(absorb: String, combining: String, keep: String, result: String, samplesMerged: String, subtitle: String, title: String) {
        self.absorb = absorb
        self.combining = combining
        self.keep = keep
        self.result = result
        self.samplesMerged = samplesMerged
        self.subtitle = subtitle
        self.title = title
    }
}

// MARK: AppLocationMerge convenience initializers and mutators

public extension AppLocationMerge {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationMerge.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        absorb: String? = nil,
        combining: String? = nil,
        keep: String? = nil,
        result: String? = nil,
        samplesMerged: String? = nil,
        subtitle: String? = nil,
        title: String? = nil
    ) -> AppLocationMerge {
        return AppLocationMerge(
            absorb: absorb ?? self.absorb,
            combining: combining ?? self.combining,
            keep: keep ?? self.keep,
            result: result ?? self.result,
            samplesMerged: samplesMerged ?? self.samplesMerged,
            subtitle: subtitle ?? self.subtitle,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Now-At hero card — contextual header labels and fallbacks for current/last location.
// MARK: - AppLocationNowAt
public struct AppLocationNowAt: Codable, Sendable {
    public let atHome, currentlyHere, homeFallback, lastKnown: String
    public let lastVisited, location, unknownLocation, waiting: String

    public init(atHome: String, currentlyHere: String, homeFallback: String, lastKnown: String, lastVisited: String, location: String, unknownLocation: String, waiting: String) {
        self.atHome = atHome
        self.currentlyHere = currentlyHere
        self.homeFallback = homeFallback
        self.lastKnown = lastKnown
        self.lastVisited = lastVisited
        self.location = location
        self.unknownLocation = unknownLocation
        self.waiting = waiting
    }
}

// MARK: AppLocationNowAt convenience initializers and mutators

public extension AppLocationNowAt {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationNowAt.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        atHome: String? = nil,
        currentlyHere: String? = nil,
        homeFallback: String? = nil,
        lastKnown: String? = nil,
        lastVisited: String? = nil,
        location: String? = nil,
        unknownLocation: String? = nil,
        waiting: String? = nil
    ) -> AppLocationNowAt {
        return AppLocationNowAt(
            atHome: atHome ?? self.atHome,
            currentlyHere: currentlyHere ?? self.currentlyHere,
            homeFallback: homeFallback ?? self.homeFallback,
            lastKnown: lastKnown ?? self.lastKnown,
            lastVisited: lastVisited ?? self.lastVisited,
            location: location ?? self.location,
            unknownLocation: unknownLocation ?? self.unknownLocation,
            waiting: waiting ?? self.waiting
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Place Rename sheet — title, subtitle template, success template, fields.
// MARK: - AppLocationPlaceRename
public struct AppLocationPlaceRename: Codable, Sendable {
    public let category, done, newName, newNamePlaceholder: String
    public let result, subtitle, title: String

    public init(category: String, done: String, newName: String, newNamePlaceholder: String, result: String, subtitle: String, title: String) {
        self.category = category
        self.done = done
        self.newName = newName
        self.newNamePlaceholder = newNamePlaceholder
        self.result = result
        self.subtitle = subtitle
        self.title = title
    }
}

// MARK: AppLocationPlaceRename convenience initializers and mutators

public extension AppLocationPlaceRename {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationPlaceRename.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        category: String? = nil,
        done: String? = nil,
        newName: String? = nil,
        newNamePlaceholder: String? = nil,
        result: String? = nil,
        subtitle: String? = nil,
        title: String? = nil
    ) -> AppLocationPlaceRename {
        return AppLocationPlaceRename(
            category: category ?? self.category,
            done: done ?? self.done,
            newName: newName ?? self.newName,
            newNamePlaceholder: newNamePlaceholder ?? self.newNamePlaceholder,
            result: result ?? self.result,
            subtitle: subtitle ?? self.subtitle,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Current-location ribbon — staleness prefix, proximity template, and exploring fallback.
// MARK: - AppLocationRibbon
public struct AppLocationRibbon: Codable, Sendable {
    public let exploring, lastSeenPrefix, near: String

    public init(exploring: String, lastSeenPrefix: String, near: String) {
        self.exploring = exploring
        self.lastSeenPrefix = lastSeenPrefix
        self.near = near
    }
}

// MARK: AppLocationRibbon convenience initializers and mutators

public extension AppLocationRibbon {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationRibbon.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        exploring: String? = nil,
        lastSeenPrefix: String? = nil,
        near: String? = nil
    ) -> AppLocationRibbon {
        return AppLocationRibbon(
            exploring: exploring ?? self.exploring,
            lastSeenPrefix: lastSeenPrefix ?? self.lastSeenPrefix,
            near: near ?? self.near
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Today stats row — the three stat-cell labels.
// MARK: - AppLocationTodayStats
public struct AppLocationTodayStats: Codable, Sendable {
    public let distance, timeOut, visits: String

    public init(distance: String, timeOut: String, visits: String) {
        self.distance = distance
        self.timeOut = timeOut
        self.visits = visits
    }
}

// MARK: AppLocationTodayStats convenience initializers and mutators

public extension AppLocationTodayStats {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationTodayStats.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        distance: String? = nil,
        timeOut: String? = nil,
        visits: String? = nil
    ) -> AppLocationTodayStats {
        return AppLocationTodayStats(
            distance: distance ?? self.distance,
            timeOut: timeOut ?? self.timeOut,
            visits: visits ?? self.visits
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Top Places card + full screen — header, counts, empty state, sort options, and per-place
/// actions.
// MARK: - AppLocationTopPlaces
public struct AppLocationTopPlaces: Codable, Sendable {
    public let empty, emptyMessage, emptyTitle, header: String
    public let lastVisit, recentVisits, rename, seeAll: String
    public let sort, sortMostRecent, sortMostVisited, uniqueLocations: String
    public let visitsUnit: String

    public init(empty: String, emptyMessage: String, emptyTitle: String, header: String, lastVisit: String, recentVisits: String, rename: String, seeAll: String, sort: String, sortMostRecent: String, sortMostVisited: String, uniqueLocations: String, visitsUnit: String) {
        self.empty = empty
        self.emptyMessage = emptyMessage
        self.emptyTitle = emptyTitle
        self.header = header
        self.lastVisit = lastVisit
        self.recentVisits = recentVisits
        self.rename = rename
        self.seeAll = seeAll
        self.sort = sort
        self.sortMostRecent = sortMostRecent
        self.sortMostVisited = sortMostVisited
        self.uniqueLocations = uniqueLocations
        self.visitsUnit = visitsUnit
    }
}

// MARK: AppLocationTopPlaces convenience initializers and mutators

public extension AppLocationTopPlaces {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationTopPlaces.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        empty: String? = nil,
        emptyMessage: String? = nil,
        emptyTitle: String? = nil,
        header: String? = nil,
        lastVisit: String? = nil,
        recentVisits: String? = nil,
        rename: String? = nil,
        seeAll: String? = nil,
        sort: String? = nil,
        sortMostRecent: String? = nil,
        sortMostVisited: String? = nil,
        uniqueLocations: String? = nil,
        visitsUnit: String? = nil
    ) -> AppLocationTopPlaces {
        return AppLocationTopPlaces(
            empty: empty ?? self.empty,
            emptyMessage: emptyMessage ?? self.emptyMessage,
            emptyTitle: emptyTitle ?? self.emptyTitle,
            header: header ?? self.header,
            lastVisit: lastVisit ?? self.lastVisit,
            recentVisits: recentVisits ?? self.recentVisits,
            rename: rename ?? self.rename,
            seeAll: seeAll ?? self.seeAll,
            sort: sort ?? self.sort,
            sortMostRecent: sortMostRecent ?? self.sortMostRecent,
            sortMostVisited: sortMostVisited ?? self.sortMostVisited,
            uniqueLocations: uniqueLocations ?? self.uniqueLocations,
            visitsUnit: visitsUnit ?? self.visitsUnit
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Visit Correction sheet — header, tab hints, time pickers, and confirm button.
// MARK: - AppLocationVisitCorrection
public struct AppLocationVisitCorrection: Codable, Sendable {
    public let adjustTimes, arrived, confirm, confirming: String
    public let departed, dragPin, pinnedLocation, searchPlaceholder: String
    public let title, unknownVisit: String

    public init(adjustTimes: String, arrived: String, confirm: String, confirming: String, departed: String, dragPin: String, pinnedLocation: String, searchPlaceholder: String, title: String, unknownVisit: String) {
        self.adjustTimes = adjustTimes
        self.arrived = arrived
        self.confirm = confirm
        self.confirming = confirming
        self.departed = departed
        self.dragPin = dragPin
        self.pinnedLocation = pinnedLocation
        self.searchPlaceholder = searchPlaceholder
        self.title = title
        self.unknownVisit = unknownVisit
    }
}

// MARK: AppLocationVisitCorrection convenience initializers and mutators

public extension AppLocationVisitCorrection {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationVisitCorrection.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        adjustTimes: String? = nil,
        arrived: String? = nil,
        confirm: String? = nil,
        confirming: String? = nil,
        departed: String? = nil,
        dragPin: String? = nil,
        pinnedLocation: String? = nil,
        searchPlaceholder: String? = nil,
        title: String? = nil,
        unknownVisit: String? = nil
    ) -> AppLocationVisitCorrection {
        return AppLocationVisitCorrection(
            adjustTimes: adjustTimes ?? self.adjustTimes,
            arrived: arrived ?? self.arrived,
            confirm: confirm ?? self.confirm,
            confirming: confirming ?? self.confirming,
            departed: departed ?? self.departed,
            dragPin: dragPin ?? self.dragPin,
            pinnedLocation: pinnedLocation ?? self.pinnedLocation,
            searchPlaceholder: searchPlaceholder ?? self.searchPlaceholder,
            title: title ?? self.title,
            unknownVisit: unknownVisit ?? self.unknownVisit
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Visit-duration fallbacks — in-progress label for an ongoing (not-yet-departed) visit.
// MARK: - AppLocationVisitDuration
public struct AppLocationVisitDuration: Codable, Sendable {
    public let inProgress: String

    public init(inProgress: String) {
        self.inProgress = inProgress
    }
}

// MARK: AppLocationVisitDuration convenience initializers and mutators

public extension AppLocationVisitDuration {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationVisitDuration.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        inProgress: String? = nil
    ) -> AppLocationVisitDuration {
        return AppLocationVisitDuration(
            inProgress: inProgress ?? self.inProgress
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// This-week bar chart — header and total-visits template.
// MARK: - AppLocationWeekChart
public struct AppLocationWeekChart: Codable, Sendable {
    public let header, totalVisits: String

    public init(header: String, totalVisits: String) {
        self.header = header
        self.totalVisits = totalVisits
    }
}

// MARK: AppLocationWeekChart convenience initializers and mutators

public extension AppLocationWeekChart {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppLocationWeekChart.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        header: String? = nil,
        totalVisits: String? = nil
    ) -> AppLocationWeekChart {
        return AppLocationWeekChart(
            header: header ?? self.header,
            totalVisits: totalVisits ?? self.totalVisits
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Navigation-bar titles for the app's primary screens (SwiftUI .navigationTitle).
// MARK: - AppNav
public struct AppNav: Codable, Sendable {
    public let activityMap, bookshelf, diagnostics, health: String
    public let home, journey, location, savedPlaces: String
    public let settings, topPlaces: String

    public init(activityMap: String, bookshelf: String, diagnostics: String, health: String, home: String, journey: String, location: String, savedPlaces: String, settings: String, topPlaces: String) {
        self.activityMap = activityMap
        self.bookshelf = bookshelf
        self.diagnostics = diagnostics
        self.health = health
        self.home = home
        self.journey = journey
        self.location = location
        self.savedPlaces = savedPlaces
        self.settings = settings
        self.topPlaces = topPlaces
    }
}

// MARK: AppNav convenience initializers and mutators

public extension AppNav {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppNav.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        activityMap: String? = nil,
        bookshelf: String? = nil,
        diagnostics: String? = nil,
        health: String? = nil,
        home: String? = nil,
        journey: String? = nil,
        location: String? = nil,
        savedPlaces: String? = nil,
        settings: String? = nil,
        topPlaces: String? = nil
    ) -> AppNav {
        return AppNav(
            activityMap: activityMap ?? self.activityMap,
            bookshelf: bookshelf ?? self.bookshelf,
            diagnostics: diagnostics ?? self.diagnostics,
            health: health ?? self.health,
            home: home ?? self.home,
            journey: journey ?? self.journey,
            location: location ?? self.location,
            savedPlaces: savedPlaces ?? self.savedPlaces,
            settings: settings ?? self.settings,
            topPlaces: topPlaces ?? self.topPlaces
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// 404 page chrome/SEO copy used on the web shell (404.astro) — document title and meta
/// description.
// MARK: - AppPage404
public struct AppPage404: Codable, Sendable {
    public let description, title: String

    public init(description: String, title: String) {
        self.description = description
        self.title = title
    }
}

// MARK: AppPage404 convenience initializers and mutators

public extension AppPage404 {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppPage404.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        description: String? = nil,
        title: String? = nil
    ) -> AppPage404 {
        return AppPage404(
            description: description ?? self.description,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Saved Places list — empty state and per-row radius label.
// MARK: - AppSavedPlaces
public struct AppSavedPlaces: Codable, Sendable {
    public let addHome, emptyBody, emptyTitle, radius: String

    public init(addHome: String, emptyBody: String, emptyTitle: String, radius: String) {
        self.addHome = addHome
        self.emptyBody = emptyBody
        self.emptyTitle = emptyTitle
        self.radius = radius
    }
}

// MARK: AppSavedPlaces convenience initializers and mutators

public extension AppSavedPlaces {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppSavedPlaces.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        addHome: String? = nil,
        emptyBody: String? = nil,
        emptyTitle: String? = nil,
        radius: String? = nil
    ) -> AppSavedPlaces {
        return AppSavedPlaces(
            addHome: addHome ?? self.addHome,
            emptyBody: emptyBody ?? self.emptyBody,
            emptyTitle: emptyTitle ?? self.emptyTitle,
            radius: radius ?? self.radius
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Dashboard triptych column header labels used on the web dashboard (index.astro).
// MARK: - AppSections
public struct AppSections: Codable, Sendable {
    public let body, mind: String

    public init(body: String, mind: String) {
        self.body = body
        self.mind = mind
    }
}

// MARK: AppSections convenience initializers and mutators

public extension AppSections {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppSections.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        body: String? = nil,
        mind: String? = nil
    ) -> AppSections {
        return AppSections(
            body: body ?? self.body,
            mind: mind ?? self.mind
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Settings screen — section headers, server/data/diagnostics/about rows, buttons, and
/// destructive-action alerts.
// MARK: - AppSettings
public struct AppSettings: Codable, Sendable {
    public let aboutBuild, aboutName, aboutPlatform, aboutTitle: String
    public let aboutVersion: String
    /// Settings destructive-action confirmation alerts (delete-all, full re-sync, clear-logs).
    public let alerts: AppSettingsAlerts
    public let apiBaseURL, apiBaseURLPlaceholder, apiToken, apiTokenPlaceholder: String
    public let clearLogs, deleteAll, diagEmpty, fileSize: String
    public let fullResync, lastHealthSync, recentEntries, reload: String
    public let savedPlacesSubtitle, savedPlacesTitle, sectionAbout, sectionData: String
    public let sectionDiagnostics, sectionLocation, sectionServer, shareLog: String
    public let totalVisits, unsyncedVisits, watchLogEntries: String

    public enum CodingKeys: String, CodingKey {
        case aboutBuild, aboutName, aboutPlatform, aboutTitle, aboutVersion, alerts
        case apiBaseURL = "apiBaseUrl"
        case apiBaseURLPlaceholder = "apiBaseUrlPlaceholder"
        case apiToken, apiTokenPlaceholder, clearLogs, deleteAll, diagEmpty, fileSize, fullResync, lastHealthSync, recentEntries, reload, savedPlacesSubtitle, savedPlacesTitle, sectionAbout, sectionData, sectionDiagnostics, sectionLocation, sectionServer, shareLog, totalVisits, unsyncedVisits, watchLogEntries
    }

    public init(aboutBuild: String, aboutName: String, aboutPlatform: String, aboutTitle: String, aboutVersion: String, alerts: AppSettingsAlerts, apiBaseURL: String, apiBaseURLPlaceholder: String, apiToken: String, apiTokenPlaceholder: String, clearLogs: String, deleteAll: String, diagEmpty: String, fileSize: String, fullResync: String, lastHealthSync: String, recentEntries: String, reload: String, savedPlacesSubtitle: String, savedPlacesTitle: String, sectionAbout: String, sectionData: String, sectionDiagnostics: String, sectionLocation: String, sectionServer: String, shareLog: String, totalVisits: String, unsyncedVisits: String, watchLogEntries: String) {
        self.aboutBuild = aboutBuild
        self.aboutName = aboutName
        self.aboutPlatform = aboutPlatform
        self.aboutTitle = aboutTitle
        self.aboutVersion = aboutVersion
        self.alerts = alerts
        self.apiBaseURL = apiBaseURL
        self.apiBaseURLPlaceholder = apiBaseURLPlaceholder
        self.apiToken = apiToken
        self.apiTokenPlaceholder = apiTokenPlaceholder
        self.clearLogs = clearLogs
        self.deleteAll = deleteAll
        self.diagEmpty = diagEmpty
        self.fileSize = fileSize
        self.fullResync = fullResync
        self.lastHealthSync = lastHealthSync
        self.recentEntries = recentEntries
        self.reload = reload
        self.savedPlacesSubtitle = savedPlacesSubtitle
        self.savedPlacesTitle = savedPlacesTitle
        self.sectionAbout = sectionAbout
        self.sectionData = sectionData
        self.sectionDiagnostics = sectionDiagnostics
        self.sectionLocation = sectionLocation
        self.sectionServer = sectionServer
        self.shareLog = shareLog
        self.totalVisits = totalVisits
        self.unsyncedVisits = unsyncedVisits
        self.watchLogEntries = watchLogEntries
    }
}

// MARK: AppSettings convenience initializers and mutators

public extension AppSettings {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppSettings.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        aboutBuild: String? = nil,
        aboutName: String? = nil,
        aboutPlatform: String? = nil,
        aboutTitle: String? = nil,
        aboutVersion: String? = nil,
        alerts: AppSettingsAlerts? = nil,
        apiBaseURL: String? = nil,
        apiBaseURLPlaceholder: String? = nil,
        apiToken: String? = nil,
        apiTokenPlaceholder: String? = nil,
        clearLogs: String? = nil,
        deleteAll: String? = nil,
        diagEmpty: String? = nil,
        fileSize: String? = nil,
        fullResync: String? = nil,
        lastHealthSync: String? = nil,
        recentEntries: String? = nil,
        reload: String? = nil,
        savedPlacesSubtitle: String? = nil,
        savedPlacesTitle: String? = nil,
        sectionAbout: String? = nil,
        sectionData: String? = nil,
        sectionDiagnostics: String? = nil,
        sectionLocation: String? = nil,
        sectionServer: String? = nil,
        shareLog: String? = nil,
        totalVisits: String? = nil,
        unsyncedVisits: String? = nil,
        watchLogEntries: String? = nil
    ) -> AppSettings {
        return AppSettings(
            aboutBuild: aboutBuild ?? self.aboutBuild,
            aboutName: aboutName ?? self.aboutName,
            aboutPlatform: aboutPlatform ?? self.aboutPlatform,
            aboutTitle: aboutTitle ?? self.aboutTitle,
            aboutVersion: aboutVersion ?? self.aboutVersion,
            alerts: alerts ?? self.alerts,
            apiBaseURL: apiBaseURL ?? self.apiBaseURL,
            apiBaseURLPlaceholder: apiBaseURLPlaceholder ?? self.apiBaseURLPlaceholder,
            apiToken: apiToken ?? self.apiToken,
            apiTokenPlaceholder: apiTokenPlaceholder ?? self.apiTokenPlaceholder,
            clearLogs: clearLogs ?? self.clearLogs,
            deleteAll: deleteAll ?? self.deleteAll,
            diagEmpty: diagEmpty ?? self.diagEmpty,
            fileSize: fileSize ?? self.fileSize,
            fullResync: fullResync ?? self.fullResync,
            lastHealthSync: lastHealthSync ?? self.lastHealthSync,
            recentEntries: recentEntries ?? self.recentEntries,
            reload: reload ?? self.reload,
            savedPlacesSubtitle: savedPlacesSubtitle ?? self.savedPlacesSubtitle,
            savedPlacesTitle: savedPlacesTitle ?? self.savedPlacesTitle,
            sectionAbout: sectionAbout ?? self.sectionAbout,
            sectionData: sectionData ?? self.sectionData,
            sectionDiagnostics: sectionDiagnostics ?? self.sectionDiagnostics,
            sectionLocation: sectionLocation ?? self.sectionLocation,
            sectionServer: sectionServer ?? self.sectionServer,
            shareLog: shareLog ?? self.shareLog,
            totalVisits: totalVisits ?? self.totalVisits,
            unsyncedVisits: unsyncedVisits ?? self.unsyncedVisits,
            watchLogEntries: watchLogEntries ?? self.watchLogEntries
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Settings destructive-action confirmation alerts (delete-all, full re-sync, clear-logs).
// MARK: - AppSettingsAlerts
public struct AppSettingsAlerts: Codable, Sendable {
    public let clearLogsMessage, clearLogsTitle, deleteAllMessage, deleteAllTitle: String
    public let resyncConfirm, resyncMessage, resyncTitle: String

    public init(clearLogsMessage: String, clearLogsTitle: String, deleteAllMessage: String, deleteAllTitle: String, resyncConfirm: String, resyncMessage: String, resyncTitle: String) {
        self.clearLogsMessage = clearLogsMessage
        self.clearLogsTitle = clearLogsTitle
        self.deleteAllMessage = deleteAllMessage
        self.deleteAllTitle = deleteAllTitle
        self.resyncConfirm = resyncConfirm
        self.resyncMessage = resyncMessage
        self.resyncTitle = resyncTitle
    }
}

// MARK: AppSettingsAlerts convenience initializers and mutators

public extension AppSettingsAlerts {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppSettingsAlerts.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        clearLogsMessage: String? = nil,
        clearLogsTitle: String? = nil,
        deleteAllMessage: String? = nil,
        deleteAllTitle: String? = nil,
        resyncConfirm: String? = nil,
        resyncMessage: String? = nil,
        resyncTitle: String? = nil
    ) -> AppSettingsAlerts {
        return AppSettingsAlerts(
            clearLogsMessage: clearLogsMessage ?? self.clearLogsMessage,
            clearLogsTitle: clearLogsTitle ?? self.clearLogsTitle,
            deleteAllMessage: deleteAllMessage ?? self.deleteAllMessage,
            deleteAllTitle: deleteAllTitle ?? self.deleteAllTitle,
            resyncConfirm: resyncConfirm ?? self.resyncConfirm,
            resyncMessage: resyncMessage ?? self.resyncMessage,
            resyncTitle: resyncTitle ?? self.resyncTitle
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Sleep-score entry sheet — title, prompt, placeholder, buttons, and a11y labels for the
/// add/edit affordance.
// MARK: - AppSleep
public struct AppSleep: Codable, Sendable {
    public let a11YAdd, a11YEdit, cancel, deleteScore: String
    public let placeholder, prompt, save, title: String

    public enum CodingKeys: String, CodingKey {
        case a11YAdd = "a11yAdd"
        case a11YEdit = "a11yEdit"
        case cancel, deleteScore, placeholder, prompt, save, title
    }

    public init(a11YAdd: String, a11YEdit: String, cancel: String, deleteScore: String, placeholder: String, prompt: String, save: String, title: String) {
        self.a11YAdd = a11YAdd
        self.a11YEdit = a11YEdit
        self.cancel = cancel
        self.deleteScore = deleteScore
        self.placeholder = placeholder
        self.prompt = prompt
        self.save = save
        self.title = title
    }
}

// MARK: AppSleep convenience initializers and mutators

public extension AppSleep {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppSleep.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        a11YAdd: String? = nil,
        a11YEdit: String? = nil,
        cancel: String? = nil,
        deleteScore: String? = nil,
        placeholder: String? = nil,
        prompt: String? = nil,
        save: String? = nil,
        title: String? = nil
    ) -> AppSleep {
        return AppSleep(
            a11YAdd: a11YAdd ?? self.a11YAdd,
            a11YEdit: a11YEdit ?? self.a11YEdit,
            cancel: cancel ?? self.cancel,
            deleteScore: deleteScore ?? self.deleteScore,
            placeholder: placeholder ?? self.placeholder,
            prompt: prompt ?? self.prompt,
            save: save ?? self.save,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Bottom tab-bar labels (TabView Label text).
// MARK: - AppTab
public struct AppTab: Codable, Sendable {
    public let books, health, home, location: String
    public let settings: String

    public init(books: String, health: String, home: String, location: String, settings: String) {
        self.books = books
        self.health = health
        self.home = home
        self.location = location
        self.settings = settings
    }
}

// MARK: AppTab convenience initializers and mutators

public extension AppTab {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppTab.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        books: String? = nil,
        health: String? = nil,
        home: String? = nil,
        location: String? = nil,
        settings: String? = nil
    ) -> AppTab {
        return AppTab(
            books: books ?? self.books,
            health: health ?? self.health,
            home: home ?? self.home,
            location: location ?? self.location,
            settings: settings ?? self.settings
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// watchOS app + sync-status complication — diagnostics chrome, sync action labels, and
/// complication strings.
// MARK: - AppWatch
public struct AppWatch: Codable, Sendable {
    public let authorize, complicationDescription, complicationDisplayName, complicationNotSynced: String
    public let complicationSyncAgo, diagA11YHint, diagA11YLabel, diagTitle: String
    public let openIphone, sync, syncFailed, transferSent: String

    public enum CodingKeys: String, CodingKey {
        case authorize, complicationDescription, complicationDisplayName, complicationNotSynced, complicationSyncAgo
        case diagA11YHint = "diagA11yHint"
        case diagA11YLabel = "diagA11yLabel"
        case diagTitle, openIphone, sync, syncFailed, transferSent
    }

    public init(authorize: String, complicationDescription: String, complicationDisplayName: String, complicationNotSynced: String, complicationSyncAgo: String, diagA11YHint: String, diagA11YLabel: String, diagTitle: String, openIphone: String, sync: String, syncFailed: String, transferSent: String) {
        self.authorize = authorize
        self.complicationDescription = complicationDescription
        self.complicationDisplayName = complicationDisplayName
        self.complicationNotSynced = complicationNotSynced
        self.complicationSyncAgo = complicationSyncAgo
        self.diagA11YHint = diagA11YHint
        self.diagA11YLabel = diagA11YLabel
        self.diagTitle = diagTitle
        self.openIphone = openIphone
        self.sync = sync
        self.syncFailed = syncFailed
        self.transferSent = transferSent
    }
}

// MARK: AppWatch convenience initializers and mutators

public extension AppWatch {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(AppWatch.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        authorize: String? = nil,
        complicationDescription: String? = nil,
        complicationDisplayName: String? = nil,
        complicationNotSynced: String? = nil,
        complicationSyncAgo: String? = nil,
        diagA11YHint: String? = nil,
        diagA11YLabel: String? = nil,
        diagTitle: String? = nil,
        openIphone: String? = nil,
        sync: String? = nil,
        syncFailed: String? = nil,
        transferSent: String? = nil
    ) -> AppWatch {
        return AppWatch(
            authorize: authorize ?? self.authorize,
            complicationDescription: complicationDescription ?? self.complicationDescription,
            complicationDisplayName: complicationDisplayName ?? self.complicationDisplayName,
            complicationNotSynced: complicationNotSynced ?? self.complicationNotSynced,
            complicationSyncAgo: complicationSyncAgo ?? self.complicationSyncAgo,
            diagA11YHint: diagA11YHint ?? self.diagA11YHint,
            diagA11YLabel: diagA11YLabel ?? self.diagA11YLabel,
            diagTitle: diagTitle ?? self.diagTitle,
            openIphone: openIphone ?? self.openIphone,
            sync: sync ?? self.sync,
            syncFailed: syncFailed ?? self.syncFailed,
            transferSent: transferSent ?? self.transferSent
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}
