import Foundation

/// Errors thrown while loading bundled copy resources.
public enum CopyError: Error, Sendable {
    /// The expected JSON resource was not present in the module bundle.
    case resourceNotFound(name: String)
    /// The resource was found but could not be decoded into the expected type.
    case decodingFailed(name: String, underlying: Error)
}

/// Loads the `@lifegames/copy` identity strings bundled with this target.
///
/// The JSON is generated by `packages/copy/scripts/build.ts` (flat values only —
/// no `_meta`) and copied to `Sources/LifegamesCopy/Resources/identity.en-US.json`.
/// `CopyLoader` and `CopyError` are the only hand-written Swift in this target;
/// `Identity` and its nested types are generated (`Identity.generated.swift`).
public enum CopyLoader {
    private static let identityResource = "identity.en-US"
    private static let widgetsResource = "widgets.en-US"
    private static let a11yResource = "a11y.en-US"

    /// Decodes the bundled identity copy (en-US, flat values).
    ///
    /// - Throws: ``CopyError/resourceNotFound(name:)`` if the bundled JSON is
    ///   missing, or ``CopyError/decodingFailed(name:underlying:)`` if it cannot
    ///   be decoded into ``Identity``.
    public static func loadIdentity() throws -> Identity {
        guard let url = Bundle.module.url(forResource: identityResource, withExtension: "json") else {
            throw CopyError.resourceNotFound(name: "\(identityResource).json")
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode(Identity.self, from: data)
        } catch {
            throw CopyError.decodingFailed(name: "\(identityResource).json", underlying: error)
        }
    }

    /// The bundled identity, force-loaded once.
    ///
    /// Safe to force-load: the JSON ships in this module's resource bundle and is
    /// validated by `LifegamesCopyTests` + the design-system freshness gate, so it
    /// cannot be missing or malformed in a built product. Use this where a throwing
    /// call is impractical (e.g. Swift default-argument values); use
    /// ``loadIdentity()`` where you want to handle failure explicitly.
    public static let identity: Identity = {
        do {
            return try loadIdentity()
        } catch {
            fatalError("LifegamesCopy: bundled \(identityResource).json failed to load: \(error)")
        }
    }()

    /// Decodes the bundled widgets copy (en-US, flat values).
    ///
    /// - Throws: ``CopyError/resourceNotFound(name:)`` if the bundled JSON is
    ///   missing, or ``CopyError/decodingFailed(name:underlying:)`` if it cannot
    ///   be decoded into ``Widgets``.
    public static func loadWidgets() throws -> Widgets {
        guard let url = Bundle.module.url(forResource: widgetsResource, withExtension: "json") else {
            throw CopyError.resourceNotFound(name: "\(widgetsResource).json")
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode(Widgets.self, from: data)
        } catch {
            throw CopyError.decodingFailed(name: "\(widgetsResource).json", underlying: error)
        }
    }

    /// The bundled widgets copy, force-loaded once.
    ///
    /// Safe to force-load: the JSON ships in this module's resource bundle and is
    /// validated by `LifegamesCopyTests` + the design-system freshness gate, so it
    /// cannot be missing or malformed in a built product. Use this where a throwing
    /// call is impractical (e.g. Swift default-argument values); use
    /// ``loadWidgets()`` where you want to handle failure explicitly.
    public static let widgets: Widgets = {
        do {
            return try loadWidgets()
        } catch {
            fatalError("LifegamesCopy: bundled \(widgetsResource).json failed to load: \(error)")
        }
    }()

    /// Decodes the bundled accessibility copy (en-US, flat values).
    ///
    /// - Throws: ``CopyError/resourceNotFound(name:)`` if the bundled JSON is
    ///   missing, or ``CopyError/decodingFailed(name:underlying:)`` if it cannot
    ///   be decoded into ``Accessibility``.
    public static func loadAccessibility() throws -> Accessibility {
        guard let url = Bundle.module.url(forResource: a11yResource, withExtension: "json") else {
            throw CopyError.resourceNotFound(name: "\(a11yResource).json")
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode(Accessibility.self, from: data)
        } catch {
            throw CopyError.decodingFailed(name: "\(a11yResource).json", underlying: error)
        }
    }

    /// The bundled accessibility copy, force-loaded once.
    ///
    /// Safe to force-load: the JSON ships in this module's resource bundle and is
    /// validated by `LifegamesCopyTests` + the design-system freshness gate, so it
    /// cannot be missing or malformed in a built product. Use this where a throwing
    /// call is impractical (e.g. Swift default-argument values); use
    /// ``loadAccessibility()`` where you want to handle failure explicitly.
    public static let a11y: Accessibility = {
        do {
            return try loadAccessibility()
        } catch {
            fatalError("LifegamesCopy: bundled \(a11yResource).json failed to load: \(error)")
        }
    }()
}
