import Foundation

/// Errors thrown while loading bundled copy resources.
public enum CopyError: Error, Sendable {
    /// The expected JSON resource was not present in the module bundle.
    case resourceNotFound(name: String)
    /// The resource was found but could not be decoded into the expected type.
    case decodingFailed(name: String, underlying: Error)
}

/// Loads the `@lifegames/copy` identity strings bundled with this target.
///
/// The JSON is generated by `packages/copy/scripts/build.ts` (flat values only —
/// no `_meta`) and copied to `Sources/LifegamesCopy/Resources/identity.en-US.json`.
/// `CopyLoader` and `CopyError` are the only hand-written Swift in this target;
/// `Identity` and its nested types are generated (`Identity.generated.swift`).
public enum CopyLoader {
    private static let identityResource = "identity.en-US"

    /// Decodes the bundled identity copy (en-US, flat values).
    ///
    /// - Throws: ``CopyError/resourceNotFound(name:)`` if the bundled JSON is
    ///   missing, or ``CopyError/decodingFailed(name:underlying:)`` if it cannot
    ///   be decoded into ``Identity``.
    public static func loadIdentity() throws -> Identity {
        guard let url = Bundle.module.url(forResource: identityResource, withExtension: "json") else {
            throw CopyError.resourceNotFound(name: "\(identityResource).json")
        }
        do {
            let data = try Data(contentsOf: url)
            return try JSONDecoder().decode(Identity.self, from: data)
        } catch {
            throw CopyError.decodingFailed(name: "\(identityResource).json", underlying: error)
        }
    }
}
