// Generated by packages/copy/scripts/build.ts — do not edit manually.
// Source of truth: packages/copy/src/errors.en-US.json (rich) → derived flat schema.
// Re-run: pnpm -F @j0nathan-ll0yd/copy build

import Foundation

/// Rich authoring schema for the errors slice of @j0nathan-ll0yd/copy. Cross-repo
/// user-facing error display text: the backend is the canonical source of these strings and
/// the iOS client decodes + presents them rather than hardcoding its own. Two groups:
/// `validation` (backend Zod request-validation messages returned to the client) and
/// `client` (iOS networking connection-test result strings). Each leaf is a CopyString
/// carrying authoring context in _meta, with usage citing BOTH the backend and iOS render
/// sites. The copy build derives a FLAT schema from this one (stripping _meta) for all
/// consumer codegen (TS/Zod/Swift). Strings are authored in ICU MessageFormat 1 syntax; the
/// client.serverReturned leaf is an interpolated template carrying its ICU placeholder
/// ({code}). Stored in natural case. Every object group has a UNIQUE title (Err*) so
/// quicktype-derived Swift struct names never collide across namespaces. The $defs block is
/// byte-identical to schema/identity.schema.json, schema/widgets.schema.json,
/// schema/a11y.schema.json, schema/app.schema.json, and schema/permissions.schema.json; the
/// $defs are inlined per schema file (no cross-file $ref), which the flat-schema derivation
/// requires.
// MARK: - Errors
public struct Errors: Codable, Sendable {
    /// iOS client networking connection-test result strings (connection-success message and
    /// HTTP-error template).
    public let client: ErrClient
    /// Backend request-validation error messages (Zod schema messages returned to the client on
    /// 400).
    public let validation: ErrValidation

    public init(client: ErrClient, validation: ErrValidation) {
        self.client = client
        self.validation = validation
    }
}

// MARK: Errors convenience initializers and mutators

public extension Errors {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Errors.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        client: ErrClient? = nil,
        validation: ErrValidation? = nil
    ) -> Errors {
        return Errors(
            client: client ?? self.client,
            validation: validation ?? self.validation
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// iOS client networking connection-test result strings (connection-success message and
/// HTTP-error template).
// MARK: - ErrClient
public struct ErrClient: Codable, Sendable {
    public let connectionSuccess, serverReturned: String

    public init(connectionSuccess: String, serverReturned: String) {
        self.connectionSuccess = connectionSuccess
        self.serverReturned = serverReturned
    }
}

// MARK: ErrClient convenience initializers and mutators

public extension ErrClient {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(ErrClient.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        connectionSuccess: String? = nil,
        serverReturned: String? = nil
    ) -> ErrClient {
        return ErrClient(
            connectionSuccess: connectionSuccess ?? self.connectionSuccess,
            serverReturned: serverReturned ?? self.serverReturned
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Backend request-validation error messages (Zod schema messages returned to the client on
/// 400).
// MARK: - ErrValidation
public struct ErrValidation: Codable, Sendable {
    public let bookNoFields, dateFormat: String

    public init(bookNoFields: String, dateFormat: String) {
        self.bookNoFields = bookNoFields
        self.dateFormat = dateFormat
    }
}

// MARK: ErrValidation convenience initializers and mutators

public extension ErrValidation {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(ErrValidation.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        bookNoFields: String? = nil,
        dateFormat: String? = nil
    ) -> ErrValidation {
        return ErrValidation(
            bookNoFields: bookNoFields ?? self.bookNoFields,
            dateFormat: dateFormat ?? self.dateFormat
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}
