// Generated by packages/copy/scripts/build.ts — do not edit manually.
// Source of truth: packages/copy/src/identity.en-US.json (rich) → derived flat schema.
// Re-run: pnpm -F @lifegames/copy build

import Foundation

/// Rich authoring schema for the identity slice of @lifegames/copy. Every customer-facing
/// identity string is a CopyString/CopyStringList leaf carrying authoring context in _meta.
/// The copy build derives a FLAT schema from this one (stripping _meta) for all consumer
/// codegen (TS/Zod/Swift). Strings are authored in ICU MessageFormat 1 syntax.
// MARK: - Identity
public struct Identity: Codable, Sendable {
    /// Accessibility copy in the V1 identity slice (skip link + OG image alt). The rest of a11y
    /// is V2.
    public let a11Y: A11Y
    /// Identity facts and biographical voices for Jonathan Lloyd.
    public let person: Person
    /// SEO/metadata copy. Composed strings are stored whole (D7), never concatenated in
    /// consumers.
    public let seo: SEO
    /// Brand/site-level naming and description.
    public let site: Site

    public enum CodingKeys: String, CodingKey {
        case a11Y = "a11y"
        case person, seo, site
    }

    public init(a11Y: A11Y, person: Person, seo: SEO, site: Site) {
        self.a11Y = a11Y
        self.person = person
        self.seo = seo
        self.site = site
    }
}

// MARK: Identity convenience initializers and mutators

public extension Identity {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Identity.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        a11Y: A11Y? = nil,
        person: Person? = nil,
        seo: SEO? = nil,
        site: Site? = nil
    ) -> Identity {
        return Identity(
            a11Y: a11Y ?? self.a11Y,
            person: person ?? self.person,
            seo: seo ?? self.seo,
            site: site ?? self.site
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Accessibility copy in the V1 identity slice (skip link + OG image alt). The rest of a11y
/// is V2.
// MARK: - A11Y
public struct A11Y: Codable, Sendable {
    public let ogImageAlt, skipToMain: String

    public init(ogImageAlt: String, skipToMain: String) {
        self.ogImageAlt = ogImageAlt
        self.skipToMain = skipToMain
    }
}

// MARK: A11Y convenience initializers and mutators

public extension A11Y {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11Y.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        ogImageAlt: String? = nil,
        skipToMain: String? = nil
    ) -> A11Y {
        return A11Y(
            ogImageAlt: ogImageAlt ?? self.ogImageAlt,
            skipToMain: skipToMain ?? self.skipToMain
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Identity facts and biographical voices for Jonathan Lloyd.
// MARK: - Person
public struct Person: Codable, Sendable {
    public let experiencePhrase, firstName, flavorBio, handle: String
    public let interests: [String]
    public let jobTitle, lastName, location, longBio: String
    public let name, philosophy: String
    public let sameAs: [String]
    public let shortBio: String
    public let skills: [String]
    public let socialBio, yearsExperience: String

    public init(experiencePhrase: String, firstName: String, flavorBio: String, handle: String, interests: [String], jobTitle: String, lastName: String, location: String, longBio: String, name: String, philosophy: String, sameAs: [String], shortBio: String, skills: [String], socialBio: String, yearsExperience: String) {
        self.experiencePhrase = experiencePhrase
        self.firstName = firstName
        self.flavorBio = flavorBio
        self.handle = handle
        self.interests = interests
        self.jobTitle = jobTitle
        self.lastName = lastName
        self.location = location
        self.longBio = longBio
        self.name = name
        self.philosophy = philosophy
        self.sameAs = sameAs
        self.shortBio = shortBio
        self.skills = skills
        self.socialBio = socialBio
        self.yearsExperience = yearsExperience
    }
}

// MARK: Person convenience initializers and mutators

public extension Person {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Person.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        experiencePhrase: String? = nil,
        firstName: String? = nil,
        flavorBio: String? = nil,
        handle: String? = nil,
        interests: [String]? = nil,
        jobTitle: String? = nil,
        lastName: String? = nil,
        location: String? = nil,
        longBio: String? = nil,
        name: String? = nil,
        philosophy: String? = nil,
        sameAs: [String]? = nil,
        shortBio: String? = nil,
        skills: [String]? = nil,
        socialBio: String? = nil,
        yearsExperience: String? = nil
    ) -> Person {
        return Person(
            experiencePhrase: experiencePhrase ?? self.experiencePhrase,
            firstName: firstName ?? self.firstName,
            flavorBio: flavorBio ?? self.flavorBio,
            handle: handle ?? self.handle,
            interests: interests ?? self.interests,
            jobTitle: jobTitle ?? self.jobTitle,
            lastName: lastName ?? self.lastName,
            location: location ?? self.location,
            longBio: longBio ?? self.longBio,
            name: name ?? self.name,
            philosophy: philosophy ?? self.philosophy,
            sameAs: sameAs ?? self.sameAs,
            shortBio: shortBio ?? self.shortBio,
            skills: skills ?? self.skills,
            socialBio: socialBio ?? self.socialBio,
            yearsExperience: yearsExperience ?? self.yearsExperience
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// SEO/metadata copy. Composed strings are stored whole (D7), never concatenated in
/// consumers.
// MARK: - SEO
public struct SEO: Codable, Sendable {
    public let expertise, keywords: [String]
    public let ogImageQuote, title: String

    public init(expertise: [String], keywords: [String], ogImageQuote: String, title: String) {
        self.expertise = expertise
        self.keywords = keywords
        self.ogImageQuote = ogImageQuote
        self.title = title
    }
}

// MARK: SEO convenience initializers and mutators

public extension SEO {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SEO.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        expertise: [String]? = nil,
        keywords: [String]? = nil,
        ogImageQuote: String? = nil,
        title: String? = nil
    ) -> SEO {
        return SEO(
            expertise: expertise ?? self.expertise,
            keywords: keywords ?? self.keywords,
            ogImageQuote: ogImageQuote ?? self.ogImageQuote,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Brand/site-level naming and description.
// MARK: - Site
public struct Site: Codable, Sendable {
    public let description, fullName, name, pwaDescription: String
    public let tagline: String

    public init(description: String, fullName: String, name: String, pwaDescription: String, tagline: String) {
        self.description = description
        self.fullName = fullName
        self.name = name
        self.pwaDescription = pwaDescription
        self.tagline = tagline
    }
}

// MARK: Site convenience initializers and mutators

public extension Site {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Site.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        description: String? = nil,
        fullName: String? = nil,
        name: String? = nil,
        pwaDescription: String? = nil,
        tagline: String? = nil
    ) -> Site {
        return Site(
            description: description ?? self.description,
            fullName: fullName ?? self.fullName,
            name: name ?? self.name,
            pwaDescription: pwaDescription ?? self.pwaDescription,
            tagline: tagline ?? self.tagline
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Helper functions for creating encoders and decoders

func newJSONDecoder() -> JSONDecoder {
    let decoder = JSONDecoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        decoder.dateDecodingStrategy = .iso8601
    }
    return decoder
}

func newJSONEncoder() -> JSONEncoder {
    let encoder = JSONEncoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        encoder.dateEncodingStrategy = .iso8601
    }
    return encoder
}
