// Generated by packages/copy/scripts/build.ts — do not edit manually.
// Source of truth: packages/copy/src/identity.en-US.json (rich) → derived flat schema.
// Re-run: pnpm -F @j0nathan-ll0yd/copy build

import Foundation

/// Rich authoring schema for the identity slice of @j0nathan-ll0yd/copy. Every
/// customer-facing identity string is a CopyString/CopyStringList leaf carrying authoring
/// context in _meta. The copy build derives a FLAT schema from this one (stripping _meta)
/// for all consumer codegen (TS/Zod/Swift). Strings are authored in ICU MessageFormat 1
/// syntax.
// MARK: - Identity
public struct Identity: Codable, Sendable {
    /// Accessibility copy in the V1 identity slice (skip link + OG image alt). The rest of a11y
    /// is V2.
    public let a11Y: A11Y
    /// RSS 2.0 + JSON Feed channel copy — title, description, author, copyright, and per-domain
    /// section labels.
    public let feed: Feed
    /// humans.txt endpoint data — web stack, hosting, standards, and credits for the SITE and
    /// THANKS sections.
    public let humansTxt: HumansTxt
    /// Identity facts and biographical voices for Jonathan Lloyd.
    public let person: Person
    /// Privacy policy page copy — plain-English sections covering who operates the site, what
    /// data is displayed, what is collected from visitors, analytics, user rights, and change
    /// notifications. Includes section headings, the last-updated label, and the back-link.
    public let privacy: Privacy
    /// SEO/metadata copy. Composed strings are stored whole (D7), never concatenated in
    /// consumers.
    public let seo: SEO
    /// Brand/site-level naming and description.
    public let site: Site

    public enum CodingKeys: String, CodingKey {
        case a11Y = "a11y"
        case feed, humansTxt, person, privacy, seo, site
    }

    public init(a11Y: A11Y, feed: Feed, humansTxt: HumansTxt, person: Person, privacy: Privacy, seo: SEO, site: Site) {
        self.a11Y = a11Y
        self.feed = feed
        self.humansTxt = humansTxt
        self.person = person
        self.privacy = privacy
        self.seo = seo
        self.site = site
    }
}

// MARK: Identity convenience initializers and mutators

public extension Identity {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Identity.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        a11Y: A11Y? = nil,
        feed: Feed? = nil,
        humansTxt: HumansTxt? = nil,
        person: Person? = nil,
        privacy: Privacy? = nil,
        seo: SEO? = nil,
        site: Site? = nil
    ) -> Identity {
        return Identity(
            a11Y: a11Y ?? self.a11Y,
            feed: feed ?? self.feed,
            humansTxt: humansTxt ?? self.humansTxt,
            person: person ?? self.person,
            privacy: privacy ?? self.privacy,
            seo: seo ?? self.seo,
            site: site ?? self.site
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Accessibility copy in the V1 identity slice (skip link + OG image alt). The rest of a11y
/// is V2.
// MARK: - A11Y
public struct A11Y: Codable, Sendable {
    public let ogImageAlt, skipToMain: String

    public init(ogImageAlt: String, skipToMain: String) {
        self.ogImageAlt = ogImageAlt
        self.skipToMain = skipToMain
    }
}

// MARK: A11Y convenience initializers and mutators

public extension A11Y {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(A11Y.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        ogImageAlt: String? = nil,
        skipToMain: String? = nil
    ) -> A11Y {
        return A11Y(
            ogImageAlt: ogImageAlt ?? self.ogImageAlt,
            skipToMain: skipToMain ?? self.skipToMain
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// RSS 2.0 + JSON Feed channel copy — title, description, author, copyright, and per-domain
/// section labels.
// MARK: - Feed
public struct Feed: Codable, Sendable {
    public let author, copyright, description: String
    /// Per-domain section labels for feed items.
    public let sections: Sections
    public let title: String

    public init(author: String, copyright: String, description: String, sections: Sections, title: String) {
        self.author = author
        self.copyright = copyright
        self.description = description
        self.sections = sections
        self.title = title
    }
}

// MARK: Feed convenience initializers and mutators

public extension Feed {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Feed.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        author: String? = nil,
        copyright: String? = nil,
        description: String? = nil,
        sections: Sections? = nil,
        title: String? = nil
    ) -> Feed {
        return Feed(
            author: author ?? self.author,
            copyright: copyright ?? self.copyright,
            description: description ?? self.description,
            sections: sections ?? self.sections,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Per-domain section labels for feed items.
// MARK: - Sections
public struct Sections: Codable, Sendable {
    public let articles, books, github, starred: String
    public let theatre: String

    public init(articles: String, books: String, github: String, starred: String, theatre: String) {
        self.articles = articles
        self.books = books
        self.github = github
        self.starred = starred
        self.theatre = theatre
    }
}

// MARK: Sections convenience initializers and mutators

public extension Sections {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Sections.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        articles: String? = nil,
        books: String? = nil,
        github: String? = nil,
        starred: String? = nil,
        theatre: String? = nil
    ) -> Sections {
        return Sections(
            articles: articles ?? self.articles,
            books: books ?? self.books,
            github: github ?? self.github,
            starred: starred ?? self.starred,
            theatre: theatre ?? self.theatre
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// humans.txt endpoint data — web stack, hosting, standards, and credits for the SITE and
/// THANKS sections.
// MARK: - HumansTxt
public struct HumansTxt: Codable, Sendable {
    public let hosting: String
    public let stack: [String]
    public let standards: String
    public let thanks: [String]

    public init(hosting: String, stack: [String], standards: String, thanks: [String]) {
        self.hosting = hosting
        self.stack = stack
        self.standards = standards
        self.thanks = thanks
    }
}

// MARK: HumansTxt convenience initializers and mutators

public extension HumansTxt {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(HumansTxt.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        hosting: String? = nil,
        stack: [String]? = nil,
        standards: String? = nil,
        thanks: [String]? = nil
    ) -> HumansTxt {
        return HumansTxt(
            hosting: hosting ?? self.hosting,
            stack: stack ?? self.stack,
            standards: standards ?? self.standards,
            thanks: thanks ?? self.thanks
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Identity facts and biographical voices for Jonathan Lloyd.
// MARK: - Person
public struct Person: Codable, Sendable {
    public let alumniOf, alumniOfURL, employer, employerURL: String
    public let experiencePhrase, firstName, flavorBio, handle: String
    public let interests: [String]
    public let jobTitle, lastName, location, longBio: String
    public let name, philosophy: String
    public let sameAs: [String]
    public let shortBio: String
    public let skills: [String]
    public let socialBio, yearsExperience: String

    public enum CodingKeys: String, CodingKey {
        case alumniOf
        case alumniOfURL = "alumniOfUrl"
        case employer
        case employerURL = "employerUrl"
        case experiencePhrase, firstName, flavorBio, handle, interests, jobTitle, lastName, location, longBio, name, philosophy, sameAs, shortBio, skills, socialBio, yearsExperience
    }

    public init(alumniOf: String, alumniOfURL: String, employer: String, employerURL: String, experiencePhrase: String, firstName: String, flavorBio: String, handle: String, interests: [String], jobTitle: String, lastName: String, location: String, longBio: String, name: String, philosophy: String, sameAs: [String], shortBio: String, skills: [String], socialBio: String, yearsExperience: String) {
        self.alumniOf = alumniOf
        self.alumniOfURL = alumniOfURL
        self.employer = employer
        self.employerURL = employerURL
        self.experiencePhrase = experiencePhrase
        self.firstName = firstName
        self.flavorBio = flavorBio
        self.handle = handle
        self.interests = interests
        self.jobTitle = jobTitle
        self.lastName = lastName
        self.location = location
        self.longBio = longBio
        self.name = name
        self.philosophy = philosophy
        self.sameAs = sameAs
        self.shortBio = shortBio
        self.skills = skills
        self.socialBio = socialBio
        self.yearsExperience = yearsExperience
    }
}

// MARK: Person convenience initializers and mutators

public extension Person {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Person.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        alumniOf: String? = nil,
        alumniOfURL: String? = nil,
        employer: String? = nil,
        employerURL: String? = nil,
        experiencePhrase: String? = nil,
        firstName: String? = nil,
        flavorBio: String? = nil,
        handle: String? = nil,
        interests: [String]? = nil,
        jobTitle: String? = nil,
        lastName: String? = nil,
        location: String? = nil,
        longBio: String? = nil,
        name: String? = nil,
        philosophy: String? = nil,
        sameAs: [String]? = nil,
        shortBio: String? = nil,
        skills: [String]? = nil,
        socialBio: String? = nil,
        yearsExperience: String? = nil
    ) -> Person {
        return Person(
            alumniOf: alumniOf ?? self.alumniOf,
            alumniOfURL: alumniOfURL ?? self.alumniOfURL,
            employer: employer ?? self.employer,
            employerURL: employerURL ?? self.employerURL,
            experiencePhrase: experiencePhrase ?? self.experiencePhrase,
            firstName: firstName ?? self.firstName,
            flavorBio: flavorBio ?? self.flavorBio,
            handle: handle ?? self.handle,
            interests: interests ?? self.interests,
            jobTitle: jobTitle ?? self.jobTitle,
            lastName: lastName ?? self.lastName,
            location: location ?? self.location,
            longBio: longBio ?? self.longBio,
            name: name ?? self.name,
            philosophy: philosophy ?? self.philosophy,
            sameAs: sameAs ?? self.sameAs,
            shortBio: shortBio ?? self.shortBio,
            skills: skills ?? self.skills,
            socialBio: socialBio ?? self.socialBio,
            yearsExperience: yearsExperience ?? self.yearsExperience
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Privacy policy page copy — plain-English sections covering who operates the site, what
/// data is displayed, what is collected from visitors, analytics, user rights, and change
/// notifications. Includes section headings, the last-updated label, and the back-link.
// MARK: - Privacy
public struct Privacy: Codable, Sendable {
    public let analytics, analyticsHeading, backLink, changes: String
    public let changesHeading, dataCollected, dataCollectedHeading, dataDisplayed: String
    public let dataDisplayedHeading, lastUpdated, lastUpdatedLabel, rights: String
    public let rightsHeading, title, who, whoHeading: String

    public init(analytics: String, analyticsHeading: String, backLink: String, changes: String, changesHeading: String, dataCollected: String, dataCollectedHeading: String, dataDisplayed: String, dataDisplayedHeading: String, lastUpdated: String, lastUpdatedLabel: String, rights: String, rightsHeading: String, title: String, who: String, whoHeading: String) {
        self.analytics = analytics
        self.analyticsHeading = analyticsHeading
        self.backLink = backLink
        self.changes = changes
        self.changesHeading = changesHeading
        self.dataCollected = dataCollected
        self.dataCollectedHeading = dataCollectedHeading
        self.dataDisplayed = dataDisplayed
        self.dataDisplayedHeading = dataDisplayedHeading
        self.lastUpdated = lastUpdated
        self.lastUpdatedLabel = lastUpdatedLabel
        self.rights = rights
        self.rightsHeading = rightsHeading
        self.title = title
        self.who = who
        self.whoHeading = whoHeading
    }
}

// MARK: Privacy convenience initializers and mutators

public extension Privacy {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Privacy.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        analytics: String? = nil,
        analyticsHeading: String? = nil,
        backLink: String? = nil,
        changes: String? = nil,
        changesHeading: String? = nil,
        dataCollected: String? = nil,
        dataCollectedHeading: String? = nil,
        dataDisplayed: String? = nil,
        dataDisplayedHeading: String? = nil,
        lastUpdated: String? = nil,
        lastUpdatedLabel: String? = nil,
        rights: String? = nil,
        rightsHeading: String? = nil,
        title: String? = nil,
        who: String? = nil,
        whoHeading: String? = nil
    ) -> Privacy {
        return Privacy(
            analytics: analytics ?? self.analytics,
            analyticsHeading: analyticsHeading ?? self.analyticsHeading,
            backLink: backLink ?? self.backLink,
            changes: changes ?? self.changes,
            changesHeading: changesHeading ?? self.changesHeading,
            dataCollected: dataCollected ?? self.dataCollected,
            dataCollectedHeading: dataCollectedHeading ?? self.dataCollectedHeading,
            dataDisplayed: dataDisplayed ?? self.dataDisplayed,
            dataDisplayedHeading: dataDisplayedHeading ?? self.dataDisplayedHeading,
            lastUpdated: lastUpdated ?? self.lastUpdated,
            lastUpdatedLabel: lastUpdatedLabel ?? self.lastUpdatedLabel,
            rights: rights ?? self.rights,
            rightsHeading: rightsHeading ?? self.rightsHeading,
            title: title ?? self.title,
            who: who ?? self.who,
            whoHeading: whoHeading ?? self.whoHeading
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// SEO/metadata copy. Composed strings are stored whole (D7), never concatenated in
/// consumers.
// MARK: - SEO
public struct SEO: Codable, Sendable {
    public let expertise, keywords: [String]
    public let ogImageQuote, title: String

    public init(expertise: [String], keywords: [String], ogImageQuote: String, title: String) {
        self.expertise = expertise
        self.keywords = keywords
        self.ogImageQuote = ogImageQuote
        self.title = title
    }
}

// MARK: SEO convenience initializers and mutators

public extension SEO {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SEO.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        expertise: [String]? = nil,
        keywords: [String]? = nil,
        ogImageQuote: String? = nil,
        title: String? = nil
    ) -> SEO {
        return SEO(
            expertise: expertise ?? self.expertise,
            keywords: keywords ?? self.keywords,
            ogImageQuote: ogImageQuote ?? self.ogImageQuote,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Brand/site-level naming and description.
// MARK: - Site
public struct Site: Codable, Sendable {
    public let description, fullName, name, pwaDescription: String
    public let tagline: String

    public init(description: String, fullName: String, name: String, pwaDescription: String, tagline: String) {
        self.description = description
        self.fullName = fullName
        self.name = name
        self.pwaDescription = pwaDescription
        self.tagline = tagline
    }
}

// MARK: Site convenience initializers and mutators

public extension Site {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Site.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        description: String? = nil,
        fullName: String? = nil,
        name: String? = nil,
        pwaDescription: String? = nil,
        tagline: String? = nil
    ) -> Site {
        return Site(
            description: description ?? self.description,
            fullName: fullName ?? self.fullName,
            name: name ?? self.name,
            pwaDescription: pwaDescription ?? self.pwaDescription,
            tagline: tagline ?? self.tagline
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Helper functions for creating encoders and decoders

func newJSONDecoder() -> JSONDecoder {
    let decoder = JSONDecoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        decoder.dateDecodingStrategy = .iso8601
    }
    return decoder
}

func newJSONEncoder() -> JSONEncoder {
    let encoder = JSONEncoder()
    if #available(iOS 10.0, OSX 10.12, tvOS 10.0, watchOS 3.0, *) {
        encoder.dateEncodingStrategy = .iso8601
    }
    return encoder
}
