// Generated by packages/copy/scripts/build.ts — do not edit manually.
// Source of truth: packages/copy/src/permissions.en-US.json (rich) → derived flat schema.
// Re-run: pnpm -F @lifegames/copy build

import Foundation

/// Rich authoring schema for the permissions slice of @lifegames/copy (V2). Every Info.plist
/// privacy-usage-description string the iOS app and watch present at permission-request
/// time, keyed per-target (D6b): the app and watch targets intentionally use different
/// wording (the watch omits app-only context). Each leaf is a CopyString carrying authoring
/// context in _meta. Source of truth is ios-LifegamesPortal/LifePortal/project.yml (the
/// NS*UsageDescription Info.plist properties on the LifePortal app target and the
/// LifePortalWatch target). The copy build derives a FLAT schema from this one (stripping
/// _meta) for all consumer codegen (TS/Zod/Swift). Strings are authored in ICU MessageFormat
/// 1 syntax (static passthrough — no interpolation here). Casing is natural-case (D3). The
/// $defs block is byte-identical to schema/identity.schema.json, schema/widgets.schema.json,
/// and schema/a11y.schema.json (per-file inlined, no cross-file $ref — §3.2).
// MARK: - Permissions
public struct Permissions: Codable, Sendable {
    /// NSHealthShareUsageDescription — shown when the app/watch requests HealthKit read access.
    /// The app variant adds 'to display metrics'; the watch variant only syncs.
    public let health: PermHealth
    /// NSLocationAlwaysAndWhenInUseUsageDescription — shown when the app requests background
    /// ('always') location access. App-only: the watch target has no always-on location usage
    /// description.
    public let locationAlways: PermLocationAlways
    /// NSLocationWhenInUseUsageDescription — shown when the app/watch requests foreground
    /// location access. The app variant tracks movement history; the watch variant only displays
    /// current position.
    public let locationWhenInUse: PermLocation
    /// NSMotionUsageDescription — shown when the app requests Core Motion access for
    /// arrival/departure detection. App-only: the watch target has no motion usage description.
    public let motion: PermMotion

    public init(health: PermHealth, locationAlways: PermLocationAlways, locationWhenInUse: PermLocation, motion: PermMotion) {
        self.health = health
        self.locationAlways = locationAlways
        self.locationWhenInUse = locationWhenInUse
        self.motion = motion
    }
}

// MARK: Permissions convenience initializers and mutators

public extension Permissions {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Permissions.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        health: PermHealth? = nil,
        locationAlways: PermLocationAlways? = nil,
        locationWhenInUse: PermLocation? = nil,
        motion: PermMotion? = nil
    ) -> Permissions {
        return Permissions(
            health: health ?? self.health,
            locationAlways: locationAlways ?? self.locationAlways,
            locationWhenInUse: locationWhenInUse ?? self.locationWhenInUse,
            motion: motion ?? self.motion
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// NSHealthShareUsageDescription — shown when the app/watch requests HealthKit read access.
/// The app variant adds 'to display metrics'; the watch variant only syncs.
// MARK: - PermHealth
public struct PermHealth: Codable, Sendable {
    public let app, watch: String

    public init(app: String, watch: String) {
        self.app = app
        self.watch = watch
    }
}

// MARK: PermHealth convenience initializers and mutators

public extension PermHealth {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(PermHealth.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        app: String? = nil,
        watch: String? = nil
    ) -> PermHealth {
        return PermHealth(
            app: app ?? self.app,
            watch: watch ?? self.watch
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// NSLocationAlwaysAndWhenInUseUsageDescription — shown when the app requests background
/// ('always') location access. App-only: the watch target has no always-on location usage
/// description.
// MARK: - PermLocationAlways
public struct PermLocationAlways: Codable, Sendable {
    public let app: String

    public init(app: String) {
        self.app = app
    }
}

// MARK: PermLocationAlways convenience initializers and mutators

public extension PermLocationAlways {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(PermLocationAlways.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        app: String? = nil
    ) -> PermLocationAlways {
        return PermLocationAlways(
            app: app ?? self.app
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// NSLocationWhenInUseUsageDescription — shown when the app/watch requests foreground
/// location access. The app variant tracks movement history; the watch variant only displays
/// current position.
// MARK: - PermLocation
public struct PermLocation: Codable, Sendable {
    public let app, watch: String

    public init(app: String, watch: String) {
        self.app = app
        self.watch = watch
    }
}

// MARK: PermLocation convenience initializers and mutators

public extension PermLocation {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(PermLocation.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        app: String? = nil,
        watch: String? = nil
    ) -> PermLocation {
        return PermLocation(
            app: app ?? self.app,
            watch: watch ?? self.watch
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// NSMotionUsageDescription — shown when the app requests Core Motion access for
/// arrival/departure detection. App-only: the watch target has no motion usage description.
// MARK: - PermMotion
public struct PermMotion: Codable, Sendable {
    public let app: String

    public init(app: String) {
        self.app = app
    }
}

// MARK: PermMotion convenience initializers and mutators

public extension PermMotion {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(PermMotion.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        app: String? = nil
    ) -> PermMotion {
        return PermMotion(
            app: app ?? self.app
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}
