// Generated by packages/copy/scripts/build.ts — do not edit manually.
// Source of truth: packages/copy/src/profile.en-US.json (rich) → derived flat schema.
// Re-run: pnpm -F @j0nathan-ll0yd/copy build

import Foundation

/// Rich authoring schema for the profile slice of @j0nathan-ll0yd/copy: the authored
/// identity content of the dashboard's IdentityCard and BioTerminal that the identity
/// namespace does not already hold (atlas decision 0160 Step 1.7). The name, title,
/// location, profile links and bio come from identity.person (name, jobTitle, location,
/// sameAs, flavorBio); this namespace adds the tagline and the bio terminal's command
/// blocks. Each terminal block is a CopyStringList whose FIRST string is the shell prompt
/// line and whose remaining strings are its output lines, in display order; blocks render in
/// key order, separated by a blank line, and the renderer appends the blinking cursor.
/// Location is authored public identity copy only; no coordinates (decision 0160 D14). The
/// copy build derives a FLAT schema from this one (stripping _meta) for all consumer codegen
/// (TS/Zod/Swift). Strings are authored in ICU MessageFormat 1 syntax (static passthrough,
/// no interpolation). The $defs block is byte-identical to the other namespaces' schemas;
/// the $defs are inlined per schema file (no cross-file $ref), which the flat-schema
/// derivation requires.
// MARK: - ProfileCopy
public struct ProfileCopy: Codable, Sendable {
    public let tagline: String
    /// The bio terminal's command blocks, in display order. Each block: [prompt line, ...output
    /// lines]. A prompt line starts with '$ ', an output line with '→ '.
    public let terminal: ProfileTerminal

    public init(tagline: String, terminal: ProfileTerminal) {
        self.tagline = tagline
        self.terminal = terminal
    }
}

// MARK: ProfileCopy convenience initializers and mutators

public extension ProfileCopy {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(ProfileCopy.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        tagline: String? = nil,
        terminal: ProfileTerminal? = nil
    ) -> ProfileCopy {
        return ProfileCopy(
            tagline: tagline ?? self.tagline,
            terminal: terminal ?? self.terminal
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// The bio terminal's command blocks, in display order. Each block: [prompt line, ...output
/// lines]. A prompt line starts with '$ ', an output line with '→ '.
// MARK: - ProfileTerminal
public struct ProfileTerminal: Codable, Sendable {
    public let gpg, interests, philosophy, stack: [String]
    public let uptime: [String]

    public init(gpg: [String], interests: [String], philosophy: [String], stack: [String], uptime: [String]) {
        self.gpg = gpg
        self.interests = interests
        self.philosophy = philosophy
        self.stack = stack
        self.uptime = uptime
    }
}

// MARK: ProfileTerminal convenience initializers and mutators

public extension ProfileTerminal {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(ProfileTerminal.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        gpg: [String]? = nil,
        interests: [String]? = nil,
        philosophy: [String]? = nil,
        stack: [String]? = nil,
        uptime: [String]? = nil
    ) -> ProfileTerminal {
        return ProfileTerminal(
            gpg: gpg ?? self.gpg,
            interests: interests ?? self.interests,
            philosophy: philosophy ?? self.philosophy,
            stack: stack ?? self.stack,
            uptime: uptime ?? self.uptime
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}
