// Generated by packages/copy/scripts/build.ts — do not edit manually.
// Source of truth: packages/copy/src/widgets.en-US.json (rich) → derived flat schema.
// Re-run: pnpm -F @lifegames/copy build

import Foundation

/// Rich authoring schema for the widgets slice of @lifegames/copy. Every customer-facing
/// widget label, unit, empty-state, zone/phase name, and timestamp badge is a
/// CopyString/CopyStringList leaf carrying authoring context in _meta. The copy build
/// derives a FLAT schema from this one (stripping _meta) for all consumer codegen
/// (TS/Zod/Swift). Strings are authored in ICU MessageFormat 1 syntax. Casing is canonical
/// natural case: consumers apply any uppercasing as a display-only transform; no all-caps
/// literals are stored. The $defs block is byte-identical to schema/identity.schema.json;
/// the $defs are inlined per schema file (no cross-file $ref), which the flat-schema
/// derivation requires.
// MARK: - Widgets
public struct Widgets: Codable, Sendable {
    /// Bio terminal widget — widget title, terminal title-bar text, bash timestamp.
    public let bio: Bio
    /// Book detail modal — section/stat labels, Amazon CTA, no-selection empty-state, progress
    /// caption template, finished-date prefix.
    public let bookModal: BookModal
    /// Bookshelf widget — title, empty-state heading/body, status labels
    /// (reading/upNext/finished/pending), finished-date line, timestamp.
    public let bookshelf: Bookshelf
    /// Coffee tracking screen (Acaia scale) — connection badge, primary action, caffeine
    /// readout, daily bar, and beverage short names.
    public let coffee: WidgetsCoffee
    /// Dev Log (GitHub activity) production widget — title, empty-state, live timestamp.
    public let devLog: DevLog
    /// Exploration odometer widget — title + the four odometer stat labels.
    public let exploration: Exploration
    /// Heart Rate widget — title, metric labels/units, HR zone names, empty-state, timestamp.
    public let heartRate: HeartRate
    /// Hydration widget — title, vessel labels, timestamp.
    public let hydration: Hydration
    /// Identity card — the social/link pill labels.
    public let identityCard: IdentityCard
    /// Movement Rings widget — title, ring/metric labels + short variants, units, empty-state,
    /// daylight caption template, timestamp.
    public let movement: Movement
    /// Night Summary (sleep) widget — title, score label, sleep-phase names, restorative caption
    /// template, empty-state, timestamp.
    public let nightSummary: NightSummary
    /// Reading Feed widget — title, empty-state, timestamp.
    public let readingFeed: ReadingFeed
    /// Starred Repos production widget — title, empty-state, recent timestamp.
    public let starredRepos: StarredRepos
    /// System Status widget — title, per-source active/offline status values (canonical natural
    /// case; consumers may uppercase as display transform), realtime timestamp, and popover
    /// provenance prose.
    public let systemStatus: SystemStatus
    /// Theatre Reviews widget — title + empty-state.
    public let theatreReviews: TheatreReviews
    /// Top Places leaderboard widget — title + empty-state.
    public let topPlaces: TopPlaces
    /// Workouts widget — title, recovery-day empty-state chrome, stat labels/units, timestamp.
    public let workouts: Workouts

    public init(bio: Bio, bookModal: BookModal, bookshelf: Bookshelf, coffee: WidgetsCoffee, devLog: DevLog, exploration: Exploration, heartRate: HeartRate, hydration: Hydration, identityCard: IdentityCard, movement: Movement, nightSummary: NightSummary, readingFeed: ReadingFeed, starredRepos: StarredRepos, systemStatus: SystemStatus, theatreReviews: TheatreReviews, topPlaces: TopPlaces, workouts: Workouts) {
        self.bio = bio
        self.bookModal = bookModal
        self.bookshelf = bookshelf
        self.coffee = coffee
        self.devLog = devLog
        self.exploration = exploration
        self.heartRate = heartRate
        self.hydration = hydration
        self.identityCard = identityCard
        self.movement = movement
        self.nightSummary = nightSummary
        self.readingFeed = readingFeed
        self.starredRepos = starredRepos
        self.systemStatus = systemStatus
        self.theatreReviews = theatreReviews
        self.topPlaces = topPlaces
        self.workouts = workouts
    }
}

// MARK: Widgets convenience initializers and mutators

public extension Widgets {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Widgets.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        bio: Bio? = nil,
        bookModal: BookModal? = nil,
        bookshelf: Bookshelf? = nil,
        coffee: WidgetsCoffee? = nil,
        devLog: DevLog? = nil,
        exploration: Exploration? = nil,
        heartRate: HeartRate? = nil,
        hydration: Hydration? = nil,
        identityCard: IdentityCard? = nil,
        movement: Movement? = nil,
        nightSummary: NightSummary? = nil,
        readingFeed: ReadingFeed? = nil,
        starredRepos: StarredRepos? = nil,
        systemStatus: SystemStatus? = nil,
        theatreReviews: TheatreReviews? = nil,
        topPlaces: TopPlaces? = nil,
        workouts: Workouts? = nil
    ) -> Widgets {
        return Widgets(
            bio: bio ?? self.bio,
            bookModal: bookModal ?? self.bookModal,
            bookshelf: bookshelf ?? self.bookshelf,
            coffee: coffee ?? self.coffee,
            devLog: devLog ?? self.devLog,
            exploration: exploration ?? self.exploration,
            heartRate: heartRate ?? self.heartRate,
            hydration: hydration ?? self.hydration,
            identityCard: identityCard ?? self.identityCard,
            movement: movement ?? self.movement,
            nightSummary: nightSummary ?? self.nightSummary,
            readingFeed: readingFeed ?? self.readingFeed,
            starredRepos: starredRepos ?? self.starredRepos,
            systemStatus: systemStatus ?? self.systemStatus,
            theatreReviews: theatreReviews ?? self.theatreReviews,
            topPlaces: topPlaces ?? self.topPlaces,
            workouts: workouts ?? self.workouts
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Bio terminal widget — widget title, terminal title-bar text, bash timestamp.
// MARK: - Bio
public struct Bio: Codable, Sendable {
    public let terminalTitle, timestampBash, title: String

    public init(terminalTitle: String, timestampBash: String, title: String) {
        self.terminalTitle = terminalTitle
        self.timestampBash = timestampBash
        self.title = title
    }
}

// MARK: Bio convenience initializers and mutators

public extension Bio {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Bio.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        terminalTitle: String? = nil,
        timestampBash: String? = nil,
        title: String? = nil
    ) -> Bio {
        return Bio(
            terminalTitle: terminalTitle ?? self.terminalTitle,
            timestampBash: timestampBash ?? self.timestampBash,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Book detail modal — section/stat labels, Amazon CTA, no-selection empty-state, progress
/// caption template, finished-date prefix.
// MARK: - BookModal
public struct BookModal: Codable, Sendable {
    public let amazonCta, empty, finishedDate, notes: String
    public let pages, progressSuffix, published, status: String

    public init(amazonCta: String, empty: String, finishedDate: String, notes: String, pages: String, progressSuffix: String, published: String, status: String) {
        self.amazonCta = amazonCta
        self.empty = empty
        self.finishedDate = finishedDate
        self.notes = notes
        self.pages = pages
        self.progressSuffix = progressSuffix
        self.published = published
        self.status = status
    }
}

// MARK: BookModal convenience initializers and mutators

public extension BookModal {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(BookModal.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        amazonCta: String? = nil,
        empty: String? = nil,
        finishedDate: String? = nil,
        notes: String? = nil,
        pages: String? = nil,
        progressSuffix: String? = nil,
        published: String? = nil,
        status: String? = nil
    ) -> BookModal {
        return BookModal(
            amazonCta: amazonCta ?? self.amazonCta,
            empty: empty ?? self.empty,
            finishedDate: finishedDate ?? self.finishedDate,
            notes: notes ?? self.notes,
            pages: pages ?? self.pages,
            progressSuffix: progressSuffix ?? self.progressSuffix,
            published: published ?? self.published,
            status: status ?? self.status
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Bookshelf widget — title, empty-state heading/body, status labels
/// (reading/upNext/finished/pending), finished-date line, timestamp.
// MARK: - Bookshelf
public struct Bookshelf: Codable, Sendable {
    public let emptyBody, emptyTitle, finishedDate, statusFinished: String
    public let statusPending, statusReading, statusUpNext, timestampLibrary: String
    public let title: String

    public init(emptyBody: String, emptyTitle: String, finishedDate: String, statusFinished: String, statusPending: String, statusReading: String, statusUpNext: String, timestampLibrary: String, title: String) {
        self.emptyBody = emptyBody
        self.emptyTitle = emptyTitle
        self.finishedDate = finishedDate
        self.statusFinished = statusFinished
        self.statusPending = statusPending
        self.statusReading = statusReading
        self.statusUpNext = statusUpNext
        self.timestampLibrary = timestampLibrary
        self.title = title
    }
}

// MARK: Bookshelf convenience initializers and mutators

public extension Bookshelf {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Bookshelf.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        emptyBody: String? = nil,
        emptyTitle: String? = nil,
        finishedDate: String? = nil,
        statusFinished: String? = nil,
        statusPending: String? = nil,
        statusReading: String? = nil,
        statusUpNext: String? = nil,
        timestampLibrary: String? = nil,
        title: String? = nil
    ) -> Bookshelf {
        return Bookshelf(
            emptyBody: emptyBody ?? self.emptyBody,
            emptyTitle: emptyTitle ?? self.emptyTitle,
            finishedDate: finishedDate ?? self.finishedDate,
            statusFinished: statusFinished ?? self.statusFinished,
            statusPending: statusPending ?? self.statusPending,
            statusReading: statusReading ?? self.statusReading,
            statusUpNext: statusUpNext ?? self.statusUpNext,
            timestampLibrary: timestampLibrary ?? self.timestampLibrary,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Coffee tracking screen (Acaia scale) — connection badge, primary action, caffeine
/// readout, daily bar, and beverage short names.
// MARK: - WidgetsCoffee
public struct WidgetsCoffee: Codable, Sendable {
    public let actionConnect, actionFinishCup, actionNewCup, actionReconnect: String
    public let badgeConnect, badgeConnected, badgeError, beverageColdBrew: String
    public let beverageDrip, beverageEspresso, caffeineUnit, dailyLabel: String
    public let searching, sipping, thisCup: String

    public init(actionConnect: String, actionFinishCup: String, actionNewCup: String, actionReconnect: String, badgeConnect: String, badgeConnected: String, badgeError: String, beverageColdBrew: String, beverageDrip: String, beverageEspresso: String, caffeineUnit: String, dailyLabel: String, searching: String, sipping: String, thisCup: String) {
        self.actionConnect = actionConnect
        self.actionFinishCup = actionFinishCup
        self.actionNewCup = actionNewCup
        self.actionReconnect = actionReconnect
        self.badgeConnect = badgeConnect
        self.badgeConnected = badgeConnected
        self.badgeError = badgeError
        self.beverageColdBrew = beverageColdBrew
        self.beverageDrip = beverageDrip
        self.beverageEspresso = beverageEspresso
        self.caffeineUnit = caffeineUnit
        self.dailyLabel = dailyLabel
        self.searching = searching
        self.sipping = sipping
        self.thisCup = thisCup
    }
}

// MARK: WidgetsCoffee convenience initializers and mutators

public extension WidgetsCoffee {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(WidgetsCoffee.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        actionConnect: String? = nil,
        actionFinishCup: String? = nil,
        actionNewCup: String? = nil,
        actionReconnect: String? = nil,
        badgeConnect: String? = nil,
        badgeConnected: String? = nil,
        badgeError: String? = nil,
        beverageColdBrew: String? = nil,
        beverageDrip: String? = nil,
        beverageEspresso: String? = nil,
        caffeineUnit: String? = nil,
        dailyLabel: String? = nil,
        searching: String? = nil,
        sipping: String? = nil,
        thisCup: String? = nil
    ) -> WidgetsCoffee {
        return WidgetsCoffee(
            actionConnect: actionConnect ?? self.actionConnect,
            actionFinishCup: actionFinishCup ?? self.actionFinishCup,
            actionNewCup: actionNewCup ?? self.actionNewCup,
            actionReconnect: actionReconnect ?? self.actionReconnect,
            badgeConnect: badgeConnect ?? self.badgeConnect,
            badgeConnected: badgeConnected ?? self.badgeConnected,
            badgeError: badgeError ?? self.badgeError,
            beverageColdBrew: beverageColdBrew ?? self.beverageColdBrew,
            beverageDrip: beverageDrip ?? self.beverageDrip,
            beverageEspresso: beverageEspresso ?? self.beverageEspresso,
            caffeineUnit: caffeineUnit ?? self.caffeineUnit,
            dailyLabel: dailyLabel ?? self.dailyLabel,
            searching: searching ?? self.searching,
            sipping: sipping ?? self.sipping,
            thisCup: thisCup ?? self.thisCup
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Dev Log (GitHub activity) production widget — title, empty-state, live timestamp.
// MARK: - DevLog
public struct DevLog: Codable, Sendable {
    public let empty, timestampLive, title: String

    public init(empty: String, timestampLive: String, title: String) {
        self.empty = empty
        self.timestampLive = timestampLive
        self.title = title
    }
}

// MARK: DevLog convenience initializers and mutators

public extension DevLog {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(DevLog.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        empty: String? = nil,
        timestampLive: String? = nil,
        title: String? = nil
    ) -> DevLog {
        return DevLog(
            empty: empty ?? self.empty,
            timestampLive: timestampLive ?? self.timestampLive,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Exploration odometer widget — title + the four odometer stat labels.
// MARK: - Exploration
public struct Exploration: Codable, Sendable {
    public let cities, places, states, title: String
    public let visits: String

    public init(cities: String, places: String, states: String, title: String, visits: String) {
        self.cities = cities
        self.places = places
        self.states = states
        self.title = title
        self.visits = visits
    }
}

// MARK: Exploration convenience initializers and mutators

public extension Exploration {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Exploration.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        cities: String? = nil,
        places: String? = nil,
        states: String? = nil,
        title: String? = nil,
        visits: String? = nil
    ) -> Exploration {
        return Exploration(
            cities: cities ?? self.cities,
            places: places ?? self.places,
            states: states ?? self.states,
            title: title ?? self.title,
            visits: visits ?? self.visits
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Heart Rate widget — title, metric labels/units, HR zone names, empty-state, timestamp.
// MARK: - HeartRate
public struct HeartRate: Codable, Sendable {
    public let bpm, empty, hrv, hrvUnit: String
    /// Paused-state badge strings for the Heart Rate widget (watch off or charging).
    public let paused: HeartRatePaused
    public let rhr, rhrUnit, rr, rrUnit: String
    public let temp, timestampLive, title, zoneBradycardia: String
    public let zoneFatBurn, zoneNormal, zonePeak, zoneResting: String

    public init(bpm: String, empty: String, hrv: String, hrvUnit: String, paused: HeartRatePaused, rhr: String, rhrUnit: String, rr: String, rrUnit: String, temp: String, timestampLive: String, title: String, zoneBradycardia: String, zoneFatBurn: String, zoneNormal: String, zonePeak: String, zoneResting: String) {
        self.bpm = bpm
        self.empty = empty
        self.hrv = hrv
        self.hrvUnit = hrvUnit
        self.paused = paused
        self.rhr = rhr
        self.rhrUnit = rhrUnit
        self.rr = rr
        self.rrUnit = rrUnit
        self.temp = temp
        self.timestampLive = timestampLive
        self.title = title
        self.zoneBradycardia = zoneBradycardia
        self.zoneFatBurn = zoneFatBurn
        self.zoneNormal = zoneNormal
        self.zonePeak = zonePeak
        self.zoneResting = zoneResting
    }
}

// MARK: HeartRate convenience initializers and mutators

public extension HeartRate {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(HeartRate.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        bpm: String? = nil,
        empty: String? = nil,
        hrv: String? = nil,
        hrvUnit: String? = nil,
        paused: HeartRatePaused? = nil,
        rhr: String? = nil,
        rhrUnit: String? = nil,
        rr: String? = nil,
        rrUnit: String? = nil,
        temp: String? = nil,
        timestampLive: String? = nil,
        title: String? = nil,
        zoneBradycardia: String? = nil,
        zoneFatBurn: String? = nil,
        zoneNormal: String? = nil,
        zonePeak: String? = nil,
        zoneResting: String? = nil
    ) -> HeartRate {
        return HeartRate(
            bpm: bpm ?? self.bpm,
            empty: empty ?? self.empty,
            hrv: hrv ?? self.hrv,
            hrvUnit: hrvUnit ?? self.hrvUnit,
            paused: paused ?? self.paused,
            rhr: rhr ?? self.rhr,
            rhrUnit: rhrUnit ?? self.rhrUnit,
            rr: rr ?? self.rr,
            rrUnit: rrUnit ?? self.rrUnit,
            temp: temp ?? self.temp,
            timestampLive: timestampLive ?? self.timestampLive,
            title: title ?? self.title,
            zoneBradycardia: zoneBradycardia ?? self.zoneBradycardia,
            zoneFatBurn: zoneFatBurn ?? self.zoneFatBurn,
            zoneNormal: zoneNormal ?? self.zoneNormal,
            zonePeak: zonePeak ?? self.zonePeak,
            zoneResting: zoneResting ?? self.zoneResting
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Paused-state badge strings for the Heart Rate widget (watch off or charging).
// MARK: - HeartRatePaused
public struct HeartRatePaused: Codable, Sendable {
    public let description, descriptionCharging, label, labelCharging: String

    public init(description: String, descriptionCharging: String, label: String, labelCharging: String) {
        self.description = description
        self.descriptionCharging = descriptionCharging
        self.label = label
        self.labelCharging = labelCharging
    }
}

// MARK: HeartRatePaused convenience initializers and mutators

public extension HeartRatePaused {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(HeartRatePaused.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        description: String? = nil,
        descriptionCharging: String? = nil,
        label: String? = nil,
        labelCharging: String? = nil
    ) -> HeartRatePaused {
        return HeartRatePaused(
            description: description ?? self.description,
            descriptionCharging: descriptionCharging ?? self.descriptionCharging,
            label: label ?? self.label,
            labelCharging: labelCharging ?? self.labelCharging
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Hydration widget — title, vessel labels, timestamp.
// MARK: - Hydration
public struct Hydration: Codable, Sendable {
    public let caffeine, timestampToday, title, water: String

    public init(caffeine: String, timestampToday: String, title: String, water: String) {
        self.caffeine = caffeine
        self.timestampToday = timestampToday
        self.title = title
        self.water = water
    }
}

// MARK: Hydration convenience initializers and mutators

public extension Hydration {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Hydration.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        caffeine: String? = nil,
        timestampToday: String? = nil,
        title: String? = nil,
        water: String? = nil
    ) -> Hydration {
        return Hydration(
            caffeine: caffeine ?? self.caffeine,
            timestampToday: timestampToday ?? self.timestampToday,
            title: title ?? self.title,
            water: water ?? self.water
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Identity card — the social/link pill labels.
// MARK: - IdentityCard
public struct IdentityCard: Codable, Sendable {
    public let bluesky, github, linkedin, mastodon: String
    public let site: String

    public init(bluesky: String, github: String, linkedin: String, mastodon: String, site: String) {
        self.bluesky = bluesky
        self.github = github
        self.linkedin = linkedin
        self.mastodon = mastodon
        self.site = site
    }
}

// MARK: IdentityCard convenience initializers and mutators

public extension IdentityCard {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(IdentityCard.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        bluesky: String? = nil,
        github: String? = nil,
        linkedin: String? = nil,
        mastodon: String? = nil,
        site: String? = nil
    ) -> IdentityCard {
        return IdentityCard(
            bluesky: bluesky ?? self.bluesky,
            github: github ?? self.github,
            linkedin: linkedin ?? self.linkedin,
            mastodon: mastodon ?? self.mastodon,
            site: site ?? self.site
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Movement Rings widget — title, ring/metric labels + short variants, units, empty-state,
/// daylight caption template, timestamp.
// MARK: - Movement
public struct Movement: Codable, Sendable {
    public let calories, caloriesShort, daylightCaption, daylightGoal: String
    public let distance, distanceUnit, empty, exercise: String
    public let exerciseShort, flights: String
    /// Paused-state badge strings for the Movement Rings widget (watch off or charging).
    public let paused: MovementPaused
    public let stand, steps, timestampToday, title: String

    public init(calories: String, caloriesShort: String, daylightCaption: String, daylightGoal: String, distance: String, distanceUnit: String, empty: String, exercise: String, exerciseShort: String, flights: String, paused: MovementPaused, stand: String, steps: String, timestampToday: String, title: String) {
        self.calories = calories
        self.caloriesShort = caloriesShort
        self.daylightCaption = daylightCaption
        self.daylightGoal = daylightGoal
        self.distance = distance
        self.distanceUnit = distanceUnit
        self.empty = empty
        self.exercise = exercise
        self.exerciseShort = exerciseShort
        self.flights = flights
        self.paused = paused
        self.stand = stand
        self.steps = steps
        self.timestampToday = timestampToday
        self.title = title
    }
}

// MARK: Movement convenience initializers and mutators

public extension Movement {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Movement.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        calories: String? = nil,
        caloriesShort: String? = nil,
        daylightCaption: String? = nil,
        daylightGoal: String? = nil,
        distance: String? = nil,
        distanceUnit: String? = nil,
        empty: String? = nil,
        exercise: String? = nil,
        exerciseShort: String? = nil,
        flights: String? = nil,
        paused: MovementPaused? = nil,
        stand: String? = nil,
        steps: String? = nil,
        timestampToday: String? = nil,
        title: String? = nil
    ) -> Movement {
        return Movement(
            calories: calories ?? self.calories,
            caloriesShort: caloriesShort ?? self.caloriesShort,
            daylightCaption: daylightCaption ?? self.daylightCaption,
            daylightGoal: daylightGoal ?? self.daylightGoal,
            distance: distance ?? self.distance,
            distanceUnit: distanceUnit ?? self.distanceUnit,
            empty: empty ?? self.empty,
            exercise: exercise ?? self.exercise,
            exerciseShort: exerciseShort ?? self.exerciseShort,
            flights: flights ?? self.flights,
            paused: paused ?? self.paused,
            stand: stand ?? self.stand,
            steps: steps ?? self.steps,
            timestampToday: timestampToday ?? self.timestampToday,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Paused-state badge strings for the Movement Rings widget (watch off or charging).
// MARK: - MovementPaused
public struct MovementPaused: Codable, Sendable {
    public let description, descriptionCharging, label, labelCharging: String

    public init(description: String, descriptionCharging: String, label: String, labelCharging: String) {
        self.description = description
        self.descriptionCharging = descriptionCharging
        self.label = label
        self.labelCharging = labelCharging
    }
}

// MARK: MovementPaused convenience initializers and mutators

public extension MovementPaused {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(MovementPaused.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        description: String? = nil,
        descriptionCharging: String? = nil,
        label: String? = nil,
        labelCharging: String? = nil
    ) -> MovementPaused {
        return MovementPaused(
            description: description ?? self.description,
            descriptionCharging: descriptionCharging ?? self.descriptionCharging,
            label: label ?? self.label,
            labelCharging: labelCharging ?? self.labelCharging
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Night Summary (sleep) widget — title, score label, sleep-phase names, restorative caption
/// template, empty-state, timestamp.
// MARK: - NightSummary
public struct NightSummary: Codable, Sendable {
    public let empty, phaseAwake, phaseCore, phaseDeep: String
    public let phaseRem, restorative, score, timestampLastNight: String
    public let title: String

    public init(empty: String, phaseAwake: String, phaseCore: String, phaseDeep: String, phaseRem: String, restorative: String, score: String, timestampLastNight: String, title: String) {
        self.empty = empty
        self.phaseAwake = phaseAwake
        self.phaseCore = phaseCore
        self.phaseDeep = phaseDeep
        self.phaseRem = phaseRem
        self.restorative = restorative
        self.score = score
        self.timestampLastNight = timestampLastNight
        self.title = title
    }
}

// MARK: NightSummary convenience initializers and mutators

public extension NightSummary {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(NightSummary.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        empty: String? = nil,
        phaseAwake: String? = nil,
        phaseCore: String? = nil,
        phaseDeep: String? = nil,
        phaseRem: String? = nil,
        restorative: String? = nil,
        score: String? = nil,
        timestampLastNight: String? = nil,
        title: String? = nil
    ) -> NightSummary {
        return NightSummary(
            empty: empty ?? self.empty,
            phaseAwake: phaseAwake ?? self.phaseAwake,
            phaseCore: phaseCore ?? self.phaseCore,
            phaseDeep: phaseDeep ?? self.phaseDeep,
            phaseRem: phaseRem ?? self.phaseRem,
            restorative: restorative ?? self.restorative,
            score: score ?? self.score,
            timestampLastNight: timestampLastNight ?? self.timestampLastNight,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Reading Feed widget — title, empty-state, timestamp.
// MARK: - ReadingFeed
public struct ReadingFeed: Codable, Sendable {
    public let empty, timestampRecent, title: String

    public init(empty: String, timestampRecent: String, title: String) {
        self.empty = empty
        self.timestampRecent = timestampRecent
        self.title = title
    }
}

// MARK: ReadingFeed convenience initializers and mutators

public extension ReadingFeed {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(ReadingFeed.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        empty: String? = nil,
        timestampRecent: String? = nil,
        title: String? = nil
    ) -> ReadingFeed {
        return ReadingFeed(
            empty: empty ?? self.empty,
            timestampRecent: timestampRecent ?? self.timestampRecent,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Starred Repos production widget — title, empty-state, recent timestamp.
// MARK: - StarredRepos
public struct StarredRepos: Codable, Sendable {
    public let empty, timestampRecent, title: String

    public init(empty: String, timestampRecent: String, title: String) {
        self.empty = empty
        self.timestampRecent = timestampRecent
        self.title = title
    }
}

// MARK: StarredRepos convenience initializers and mutators

public extension StarredRepos {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(StarredRepos.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        empty: String? = nil,
        timestampRecent: String? = nil,
        title: String? = nil
    ) -> StarredRepos {
        return StarredRepos(
            empty: empty ?? self.empty,
            timestampRecent: timestampRecent ?? self.timestampRecent,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// System Status widget — title, per-source active/offline status values (canonical natural
/// case; consumers may uppercase as display transform), realtime timestamp, and popover
/// provenance prose.
// MARK: - SystemStatus
public struct SystemStatus: Codable, Sendable {
    /// Structured provenance for each System Status data source. Translatable prose (body, with
    /// {phKey} ICU MF1 placeholders) is separated from structural link refs (label + machine
    /// href) so a TMS never sees a URL and platforms compose their own anchors. Web composes
    /// anchor HTML via composeProvenance(); iOS composes native links from the same shape.
    public let sources: Sources
    public let timestampRealtime, title, valueActive, valueOffline: String

    public init(sources: Sources, timestampRealtime: String, title: String, valueActive: String, valueOffline: String) {
        self.sources = sources
        self.timestampRealtime = timestampRealtime
        self.title = title
        self.valueActive = valueActive
        self.valueOffline = valueOffline
    }
}

// MARK: SystemStatus convenience initializers and mutators

public extension SystemStatus {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatus.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        sources: Sources? = nil,
        timestampRealtime: String? = nil,
        title: String? = nil,
        valueActive: String? = nil,
        valueOffline: String? = nil
    ) -> SystemStatus {
        return SystemStatus(
            sources: sources ?? self.sources,
            timestampRealtime: timestampRealtime ?? self.timestampRealtime,
            title: title ?? self.title,
            valueActive: valueActive ?? self.valueActive,
            valueOffline: valueOffline ?? self.valueOffline
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Structured provenance for each System Status data source. Translatable prose (body, with
/// {phKey} ICU MF1 placeholders) is separated from structural link refs (label + machine
/// href) so a TMS never sees a URL and platforms compose their own anchors. Web composes
/// anchor HTML via composeProvenance(); iOS composes native links from the same shape.
// MARK: - Sources
public struct Sources: Codable, Sendable {
    public let articles: SystemStatusSourceArticles
    public let books: SystemStatusSourceBooks
    public let githubEvents: SystemStatusSourceGithubEvents
    public let health: SystemStatusSourceHealth
    public let sleep: SystemStatusSourceSleep
    public let starredRepos: SystemStatusSourceStarredRepos
    public let theatreReviews: SystemStatusSourceTheatreReviews

    public init(articles: SystemStatusSourceArticles, books: SystemStatusSourceBooks, githubEvents: SystemStatusSourceGithubEvents, health: SystemStatusSourceHealth, sleep: SystemStatusSourceSleep, starredRepos: SystemStatusSourceStarredRepos, theatreReviews: SystemStatusSourceTheatreReviews) {
        self.articles = articles
        self.books = books
        self.githubEvents = githubEvents
        self.health = health
        self.sleep = sleep
        self.starredRepos = starredRepos
        self.theatreReviews = theatreReviews
    }
}

// MARK: Sources convenience initializers and mutators

public extension Sources {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Sources.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        articles: SystemStatusSourceArticles? = nil,
        books: SystemStatusSourceBooks? = nil,
        githubEvents: SystemStatusSourceGithubEvents? = nil,
        health: SystemStatusSourceHealth? = nil,
        sleep: SystemStatusSourceSleep? = nil,
        starredRepos: SystemStatusSourceStarredRepos? = nil,
        theatreReviews: SystemStatusSourceTheatreReviews? = nil
    ) -> Sources {
        return Sources(
            articles: articles ?? self.articles,
            books: books ?? self.books,
            githubEvents: githubEvents ?? self.githubEvents,
            health: health ?? self.health,
            sleep: sleep ?? self.sleep,
            starredRepos: starredRepos ?? self.starredRepos,
            theatreReviews: theatreReviews ?? self.theatreReviews
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusSourceArticles
public struct SystemStatusSourceArticles: Codable, Sendable {
    public let body: String
    public let refs: SystemStatusRefsArticles

    public init(body: String, refs: SystemStatusRefsArticles) {
        self.body = body
        self.refs = refs
    }
}

// MARK: SystemStatusSourceArticles convenience initializers and mutators

public extension SystemStatusSourceArticles {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusSourceArticles.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        body: String? = nil,
        refs: SystemStatusRefsArticles? = nil
    ) -> SystemStatusSourceArticles {
        return SystemStatusSourceArticles(
            body: body ?? self.body,
            refs: refs ?? self.refs
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusRefsArticles
public struct SystemStatusRefsArticles: Codable, Sendable {
    public let feedly: Feedly

    public init(feedly: Feedly) {
        self.feedly = feedly
    }
}

// MARK: SystemStatusRefsArticles convenience initializers and mutators

public extension SystemStatusRefsArticles {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusRefsArticles.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        feedly: Feedly? = nil
    ) -> SystemStatusRefsArticles {
        return SystemStatusRefsArticles(
            feedly: feedly ?? self.feedly
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Feedly
public struct Feedly: Codable, Sendable {
    public let href, label: String

    public init(href: String, label: String) {
        self.href = href
        self.label = label
    }
}

// MARK: Feedly convenience initializers and mutators

public extension Feedly {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Feedly.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        href: String? = nil,
        label: String? = nil
    ) -> Feedly {
        return Feedly(
            href: href ?? self.href,
            label: label ?? self.label
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusSourceBooks
public struct SystemStatusSourceBooks: Codable, Sendable {
    public let body: String
    public let refs: SystemStatusRefsBooks

    public init(body: String, refs: SystemStatusRefsBooks) {
        self.body = body
        self.refs = refs
    }
}

// MARK: SystemStatusSourceBooks convenience initializers and mutators

public extension SystemStatusSourceBooks {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusSourceBooks.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        body: String? = nil,
        refs: SystemStatusRefsBooks? = nil
    ) -> SystemStatusSourceBooks {
        return SystemStatusSourceBooks(
            body: body ?? self.body,
            refs: refs ?? self.refs
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusRefsBooks
public struct SystemStatusRefsBooks: Codable, Sendable {

    public init() {
    }
}

// MARK: SystemStatusRefsBooks convenience initializers and mutators

public extension SystemStatusRefsBooks {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusRefsBooks.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
    ) -> SystemStatusRefsBooks {
        return SystemStatusRefsBooks(
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusSourceGithubEvents
public struct SystemStatusSourceGithubEvents: Codable, Sendable {
    public let body: String
    public let refs: SystemStatusRefsGithubEvents

    public init(body: String, refs: SystemStatusRefsGithubEvents) {
        self.body = body
        self.refs = refs
    }
}

// MARK: SystemStatusSourceGithubEvents convenience initializers and mutators

public extension SystemStatusSourceGithubEvents {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusSourceGithubEvents.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        body: String? = nil,
        refs: SystemStatusRefsGithubEvents? = nil
    ) -> SystemStatusSourceGithubEvents {
        return SystemStatusSourceGithubEvents(
            body: body ?? self.body,
            refs: refs ?? self.refs
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusRefsGithubEvents
public struct SystemStatusRefsGithubEvents: Codable, Sendable {
    public let github: PurpleGithub

    public init(github: PurpleGithub) {
        self.github = github
    }
}

// MARK: SystemStatusRefsGithubEvents convenience initializers and mutators

public extension SystemStatusRefsGithubEvents {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusRefsGithubEvents.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        github: PurpleGithub? = nil
    ) -> SystemStatusRefsGithubEvents {
        return SystemStatusRefsGithubEvents(
            github: github ?? self.github
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - PurpleGithub
public struct PurpleGithub: Codable, Sendable {
    public let href, label: String

    public init(href: String, label: String) {
        self.href = href
        self.label = label
    }
}

// MARK: PurpleGithub convenience initializers and mutators

public extension PurpleGithub {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(PurpleGithub.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        href: String? = nil,
        label: String? = nil
    ) -> PurpleGithub {
        return PurpleGithub(
            href: href ?? self.href,
            label: label ?? self.label
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusSourceHealth
public struct SystemStatusSourceHealth: Codable, Sendable {
    public let body: String
    public let refs: SystemStatusRefsHealth

    public init(body: String, refs: SystemStatusRefsHealth) {
        self.body = body
        self.refs = refs
    }
}

// MARK: SystemStatusSourceHealth convenience initializers and mutators

public extension SystemStatusSourceHealth {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusSourceHealth.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        body: String? = nil,
        refs: SystemStatusRefsHealth? = nil
    ) -> SystemStatusSourceHealth {
        return SystemStatusSourceHealth(
            body: body ?? self.body,
            refs: refs ?? self.refs
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusRefsHealth
public struct SystemStatusRefsHealth: Codable, Sendable {
    public let coffee: Coffee
    public let watch: PurpleWatch
    public let water: Water

    public init(coffee: Coffee, watch: PurpleWatch, water: Water) {
        self.coffee = coffee
        self.watch = watch
        self.water = water
    }
}

// MARK: SystemStatusRefsHealth convenience initializers and mutators

public extension SystemStatusRefsHealth {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusRefsHealth.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        coffee: Coffee? = nil,
        watch: PurpleWatch? = nil,
        water: Water? = nil
    ) -> SystemStatusRefsHealth {
        return SystemStatusRefsHealth(
            coffee: coffee ?? self.coffee,
            watch: watch ?? self.watch,
            water: water ?? self.water
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Coffee
public struct Coffee: Codable, Sendable {
    public let href, label: String

    public init(href: String, label: String) {
        self.href = href
        self.label = label
    }
}

// MARK: Coffee convenience initializers and mutators

public extension Coffee {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Coffee.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        href: String? = nil,
        label: String? = nil
    ) -> Coffee {
        return Coffee(
            href: href ?? self.href,
            label: label ?? self.label
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - PurpleWatch
public struct PurpleWatch: Codable, Sendable {
    public let href, label: String

    public init(href: String, label: String) {
        self.href = href
        self.label = label
    }
}

// MARK: PurpleWatch convenience initializers and mutators

public extension PurpleWatch {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(PurpleWatch.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        href: String? = nil,
        label: String? = nil
    ) -> PurpleWatch {
        return PurpleWatch(
            href: href ?? self.href,
            label: label ?? self.label
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Water
public struct Water: Codable, Sendable {
    public let href, label: String

    public init(href: String, label: String) {
        self.href = href
        self.label = label
    }
}

// MARK: Water convenience initializers and mutators

public extension Water {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Water.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        href: String? = nil,
        label: String? = nil
    ) -> Water {
        return Water(
            href: href ?? self.href,
            label: label ?? self.label
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusSourceSleep
public struct SystemStatusSourceSleep: Codable, Sendable {
    public let body: String
    public let refs: SystemStatusRefsSleep

    public init(body: String, refs: SystemStatusRefsSleep) {
        self.body = body
        self.refs = refs
    }
}

// MARK: SystemStatusSourceSleep convenience initializers and mutators

public extension SystemStatusSourceSleep {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusSourceSleep.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        body: String? = nil,
        refs: SystemStatusRefsSleep? = nil
    ) -> SystemStatusSourceSleep {
        return SystemStatusSourceSleep(
            body: body ?? self.body,
            refs: refs ?? self.refs
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusRefsSleep
public struct SystemStatusRefsSleep: Codable, Sendable {
    public let watch: FluffyWatch

    public init(watch: FluffyWatch) {
        self.watch = watch
    }
}

// MARK: SystemStatusRefsSleep convenience initializers and mutators

public extension SystemStatusRefsSleep {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusRefsSleep.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        watch: FluffyWatch? = nil
    ) -> SystemStatusRefsSleep {
        return SystemStatusRefsSleep(
            watch: watch ?? self.watch
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - FluffyWatch
public struct FluffyWatch: Codable, Sendable {
    public let href, label: String

    public init(href: String, label: String) {
        self.href = href
        self.label = label
    }
}

// MARK: FluffyWatch convenience initializers and mutators

public extension FluffyWatch {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(FluffyWatch.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        href: String? = nil,
        label: String? = nil
    ) -> FluffyWatch {
        return FluffyWatch(
            href: href ?? self.href,
            label: label ?? self.label
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusSourceStarredRepos
public struct SystemStatusSourceStarredRepos: Codable, Sendable {
    public let body: String
    public let refs: SystemStatusRefsStarredRepos

    public init(body: String, refs: SystemStatusRefsStarredRepos) {
        self.body = body
        self.refs = refs
    }
}

// MARK: SystemStatusSourceStarredRepos convenience initializers and mutators

public extension SystemStatusSourceStarredRepos {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusSourceStarredRepos.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        body: String? = nil,
        refs: SystemStatusRefsStarredRepos? = nil
    ) -> SystemStatusSourceStarredRepos {
        return SystemStatusSourceStarredRepos(
            body: body ?? self.body,
            refs: refs ?? self.refs
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusRefsStarredRepos
public struct SystemStatusRefsStarredRepos: Codable, Sendable {
    public let github: FluffyGithub

    public init(github: FluffyGithub) {
        self.github = github
    }
}

// MARK: SystemStatusRefsStarredRepos convenience initializers and mutators

public extension SystemStatusRefsStarredRepos {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusRefsStarredRepos.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        github: FluffyGithub? = nil
    ) -> SystemStatusRefsStarredRepos {
        return SystemStatusRefsStarredRepos(
            github: github ?? self.github
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - FluffyGithub
public struct FluffyGithub: Codable, Sendable {
    public let href, label: String

    public init(href: String, label: String) {
        self.href = href
        self.label = label
    }
}

// MARK: FluffyGithub convenience initializers and mutators

public extension FluffyGithub {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(FluffyGithub.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        href: String? = nil,
        label: String? = nil
    ) -> FluffyGithub {
        return FluffyGithub(
            href: href ?? self.href,
            label: label ?? self.label
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusSourceTheatreReviews
public struct SystemStatusSourceTheatreReviews: Codable, Sendable {
    public let body: String
    public let refs: SystemStatusRefsTheatreReviews

    public init(body: String, refs: SystemStatusRefsTheatreReviews) {
        self.body = body
        self.refs = refs
    }
}

// MARK: SystemStatusSourceTheatreReviews convenience initializers and mutators

public extension SystemStatusSourceTheatreReviews {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusSourceTheatreReviews.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        body: String? = nil,
        refs: SystemStatusRefsTheatreReviews? = nil
    ) -> SystemStatusSourceTheatreReviews {
        return SystemStatusSourceTheatreReviews(
            body: body ?? self.body,
            refs: refs ?? self.refs
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - SystemStatusRefsTheatreReviews
public struct SystemStatusRefsTheatreReviews: Codable, Sendable {
    public let squarespace: Squarespace

    public init(squarespace: Squarespace) {
        self.squarespace = squarespace
    }
}

// MARK: SystemStatusRefsTheatreReviews convenience initializers and mutators

public extension SystemStatusRefsTheatreReviews {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(SystemStatusRefsTheatreReviews.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        squarespace: Squarespace? = nil
    ) -> SystemStatusRefsTheatreReviews {
        return SystemStatusRefsTheatreReviews(
            squarespace: squarespace ?? self.squarespace
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

// MARK: - Squarespace
public struct Squarespace: Codable, Sendable {
    public let href, label: String

    public init(href: String, label: String) {
        self.href = href
        self.label = label
    }
}

// MARK: Squarespace convenience initializers and mutators

public extension Squarespace {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Squarespace.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        href: String? = nil,
        label: String? = nil
    ) -> Squarespace {
        return Squarespace(
            href: href ?? self.href,
            label: label ?? self.label
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Theatre Reviews widget — title + empty-state.
// MARK: - TheatreReviews
public struct TheatreReviews: Codable, Sendable {
    public let empty, title: String

    public init(empty: String, title: String) {
        self.empty = empty
        self.title = title
    }
}

// MARK: TheatreReviews convenience initializers and mutators

public extension TheatreReviews {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(TheatreReviews.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        empty: String? = nil,
        title: String? = nil
    ) -> TheatreReviews {
        return TheatreReviews(
            empty: empty ?? self.empty,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Top Places leaderboard widget — title + empty-state.
// MARK: - TopPlaces
public struct TopPlaces: Codable, Sendable {
    public let empty, title: String

    public init(empty: String, title: String) {
        self.empty = empty
        self.title = title
    }
}

// MARK: TopPlaces convenience initializers and mutators

public extension TopPlaces {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(TopPlaces.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        empty: String? = nil,
        title: String? = nil
    ) -> TopPlaces {
        return TopPlaces(
            empty: empty ?? self.empty,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}

/// Workouts widget — title, recovery-day empty-state chrome, stat labels/units, timestamp.
// MARK: - Workouts
public struct Workouts: Codable, Sendable {
    public let calories, caloriesUnit, distance, distanceUnit: String
    public let duration, none, recoveryBody, recoveryDay: String
    public let timestampToday, title: String

    public init(calories: String, caloriesUnit: String, distance: String, distanceUnit: String, duration: String, none: String, recoveryBody: String, recoveryDay: String, timestampToday: String, title: String) {
        self.calories = calories
        self.caloriesUnit = caloriesUnit
        self.distance = distance
        self.distanceUnit = distanceUnit
        self.duration = duration
        self.none = none
        self.recoveryBody = recoveryBody
        self.recoveryDay = recoveryDay
        self.timestampToday = timestampToday
        self.title = title
    }
}

// MARK: Workouts convenience initializers and mutators

public extension Workouts {
    init(data: Data) throws {
        self = try newJSONDecoder().decode(Workouts.self, from: data)
    }

    init(_ json: String, using encoding: String.Encoding = .utf8) throws {
        guard let data = json.data(using: encoding) else {
            throw NSError(domain: "JSONDecoding", code: 0, userInfo: nil)
        }
        try self.init(data: data)
    }

    init(fromURL url: URL) throws {
        try self.init(data: try Data(contentsOf: url))
    }

    func with(
        calories: String? = nil,
        caloriesUnit: String? = nil,
        distance: String? = nil,
        distanceUnit: String? = nil,
        duration: String? = nil,
        none: String? = nil,
        recoveryBody: String? = nil,
        recoveryDay: String? = nil,
        timestampToday: String? = nil,
        title: String? = nil
    ) -> Workouts {
        return Workouts(
            calories: calories ?? self.calories,
            caloriesUnit: caloriesUnit ?? self.caloriesUnit,
            distance: distance ?? self.distance,
            distanceUnit: distanceUnit ?? self.distanceUnit,
            duration: duration ?? self.duration,
            none: none ?? self.none,
            recoveryBody: recoveryBody ?? self.recoveryBody,
            recoveryDay: recoveryDay ?? self.recoveryDay,
            timestampToday: timestampToday ?? self.timestampToday,
            title: title ?? self.title
        )
    }

    func jsonData() throws -> Data {
        return try newJSONEncoder().encode(self)
    }

    func jsonString(encoding: String.Encoding = .utf8) throws -> String? {
        return String(data: try self.jsonData(), encoding: encoding)
    }
}
