// Generated by Style Dictionary — do not edit
import SwiftUI

/// Color tokens for surfaces rendered by AI clients (thinking indicators,
/// citations, tool-use disclosure, artifact frames, code blocks).
public enum AISurfaces {
    public static let surfaceThinking = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.05)
    public static let surfaceCitation = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.03)
    public static let surfaceToolUse = Color(red: 0.388, green: 0.400, blue: 0.945, opacity: 0.08)
    public static let surfaceArtifactFrame = Color(red: 1.000, green: 1.000, blue: 1.000, opacity: 0.04)
    public static let surfaceCodeBlock = Color(red: 0.000, green: 0.000, blue: 0.000, opacity: 0.35)
    public static let surfaceCodeBlockDiffAdded = Color(red: 0.024, green: 0.839, blue: 0.627, opacity: 0.12)
    public static let surfaceCodeBlockDiffRemoved = Color(red: 0.937, green: 0.267, blue: 0.267, opacity: 0.12)
}
