// Generated by Style Dictionary — do not edit
import SwiftUI

public enum ShadowTokens {
    public static func shadowGlowPink() -> _ShadowModifier_shadowGlowPink { _ShadowModifier_shadowGlowPink() }
    public static func shadowGlowBlue() -> _ShadowModifier_shadowGlowBlue { _ShadowModifier_shadowGlowBlue() }
    public static func shadowGlowGreen() -> _ShadowModifier_shadowGlowGreen { _ShadowModifier_shadowGlowGreen() }
    public static func shadowGlowAmber() -> _ShadowModifier_shadowGlowAmber { _ShadowModifier_shadowGlowAmber() }
    public static func shadowGlowPurple() -> _ShadowModifier_shadowGlowPurple { _ShadowModifier_shadowGlowPurple() }
    public static func shadowGlowRed() -> _ShadowModifier_shadowGlowRed { _ShadowModifier_shadowGlowRed() }
    public static func shadowGlowCyan() -> _ShadowModifier_shadowGlowCyan { _ShadowModifier_shadowGlowCyan() }
    public static func shadowGlowOrange() -> _ShadowModifier_shadowGlowOrange { _ShadowModifier_shadowGlowOrange() }
    public static func shadowGlowIndigo() -> _ShadowModifier_shadowGlowIndigo { _ShadowModifier_shadowGlowIndigo() }
    public static func shadowGlowPinkSm() -> _ShadowModifier_shadowGlowPinkSm { _ShadowModifier_shadowGlowPinkSm() }
    public static func shadowGlowBlueSm() -> _ShadowModifier_shadowGlowBlueSm { _ShadowModifier_shadowGlowBlueSm() }
    public static func shadowGlowGreenSm() -> _ShadowModifier_shadowGlowGreenSm { _ShadowModifier_shadowGlowGreenSm() }
    public static func shadowGlowAmberSm() -> _ShadowModifier_shadowGlowAmberSm { _ShadowModifier_shadowGlowAmberSm() }
    public static func shadowGlowPurpleSm() -> _ShadowModifier_shadowGlowPurpleSm { _ShadowModifier_shadowGlowPurpleSm() }
    public static func shadowGlowRedSm() -> _ShadowModifier_shadowGlowRedSm { _ShadowModifier_shadowGlowRedSm() }
    public static func shadowGlowCyanSm() -> _ShadowModifier_shadowGlowCyanSm { _ShadowModifier_shadowGlowCyanSm() }
    public static func shadowGlowOrangeSm() -> _ShadowModifier_shadowGlowOrangeSm { _ShadowModifier_shadowGlowOrangeSm() }
    public static func shadowGlowIndigoSm() -> _ShadowModifier_shadowGlowIndigoSm { _ShadowModifier_shadowGlowIndigoSm() }
    public static func shadowGlowAccent() -> _ShadowModifier_shadowGlowAccent { _ShadowModifier_shadowGlowAccent() }
    public static func shadowGlowAccentSm() -> _ShadowModifier_shadowGlowAccentSm { _ShadowModifier_shadowGlowAccentSm() }
}

public struct _ShadowModifier_shadowGlowPink: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 1.000, green: 0.000, blue: 0.431, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 1.000, green: 0.000, blue: 0.431, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowBlue: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.227, green: 0.525, blue: 1.000, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 0.227, green: 0.525, blue: 1.000, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowGreen: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.024, green: 0.839, blue: 0.627, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 0.024, green: 0.839, blue: 0.627, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowAmber: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.961, green: 0.620, blue: 0.043, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 0.961, green: 0.620, blue: 0.043, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowPurple: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.659, green: 0.333, blue: 0.969, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 0.659, green: 0.333, blue: 0.969, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowRed: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.937, green: 0.267, blue: 0.267, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 0.937, green: 0.267, blue: 0.267, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowCyan: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.000, green: 0.831, blue: 1.000, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 0.000, green: 0.831, blue: 1.000, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowOrange: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 1.000, green: 0.420, blue: 0.000, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 1.000, green: 0.420, blue: 0.000, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowIndigo: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowPinkSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 1.000, green: 0.000, blue: 0.431, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowBlueSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.227, green: 0.525, blue: 1.000, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowGreenSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.024, green: 0.839, blue: 0.627, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowAmberSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.961, green: 0.620, blue: 0.043, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowPurpleSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.659, green: 0.333, blue: 0.969, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowRedSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.937, green: 0.267, blue: 0.267, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowCyanSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.000, green: 0.831, blue: 1.000, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowOrangeSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 1.000, green: 0.420, blue: 0.000, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowIndigoSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowAccent: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 0.3), radius: 10, x: 0, y: 0)
            .shadow(color: Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 0.15), radius: 20, x: 0, y: 0)
    }
}

public struct _ShadowModifier_shadowGlowAccentSm: ViewModifier {
    public func body(content: Content) -> some View {
        content
            .shadow(color: Color(red: 0.506, green: 0.549, blue: 0.973, opacity: 0.25), radius: 6, x: 0, y: 0)
    }
}

