#!/usr/bin/env tsx
/**
 * build.ts — @lifegames/copy build + codegen pipeline (Plan A4).
 *
 * Single producer of every copy artifact. Pipeline:
 *   1. Validate the RICH authoring file (src/identity.en-US.json) against the
 *      rich schema (@lifegames/schemas/authored/copy.identity.schema.json) with
 *      Ajv + ajv-formats. This is the ONLY place the rich {value,_meta} shape is
 *      validated.
 *   2. Derive a FLAT JSON Schema from the rich one: walk the schema tree and
 *      replace ONLY the leaf $refs (CopyString → {type:string}, CopyStringList →
 *      {type:array,items:{type:string}}), preserving every object wrapper,
 *      `required` array, and `additionalProperties:false`. This flat schema is
 *      the SINGLE input to all codegen (TS/Zod/Swift) — consumers read flat
 *      values, never the rich {value,_meta} shape.
 *   3. Emit the flat instance (dist/identity.flat.json, _meta stripped) + barrel.
 *   4. TS    — json-schema-to-typescript over the flat schema → dist/identity.ts
 *   5. Zod   — json-schema-to-zod over the flat schema → dist/identity.zod.ts
 *   6. Swift — quicktype over the flat schema → ../../Sources/LifegamesCopy/Identity.generated.swift
 *   7. Resource — flat instance → ../../Sources/LifegamesCopy/Resources/identity.en-US.json
 *
 * Round-trip guard: the derived flat schema MUST validate the flat instance
 * (ajv.validate(flatSchema, flatJson)) so a derivation bug cannot silently drop
 * a `required` field. Idempotent: re-running yields byte-identical output.
 *
 * D9 boundary: this script lives in scripts/ (NOT src/) — it is the only place
 * permitted to import @lifegames/schemas. The src/ tree stays a zero-dep leaf.
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { compile } from 'json-schema-to-typescript';
import jsonSchemaToZod from 'json-schema-to-zod';

const require = createRequire(import.meta.url);
const HERE = dirname(fileURLToPath(import.meta.url));

const PKG_ROOT = join(HERE, '..'); // packages/copy
const DS_ROOT = join(PKG_ROOT, '..', '..'); // design-system-Lifegames
const SRC = join(PKG_ROOT, 'src');
const DIST = join(PKG_ROOT, 'dist');
const SWIFT_TARGET = join(DS_ROOT, 'Sources', 'LifegamesCopy');
const SWIFT_RESOURCES = join(SWIFT_TARGET, 'Resources');

const RICH_INSTANCE_PATH = join(SRC, 'identity.en-US.json');
const RICH_SCHEMA_PATH = require.resolve('@lifegames/schemas/authored/copy.identity.schema.json');

type JsonSchema = Record<string, any>;

const GEN_HEADER =
  '// Generated by packages/copy/scripts/build.ts — do not edit manually.\n' +
  '// Source of truth: packages/copy/src/identity.en-US.json (rich) → derived flat schema.\n' +
  '// Re-run: pnpm -F @lifegames/copy build\n\n';

function readJson(p: string): any {
  return JSON.parse(readFileSync(p, 'utf-8'));
}
function ensureDir(p: string): void {
  mkdirSync(p, { recursive: true });
}

// ── 1. Validate the rich authoring file ───────────────────────────────────────
console.log('copy:build — validating rich identity against rich schema (Ajv)...');
const richSchema = readJson(RICH_SCHEMA_PATH) as JsonSchema;
const richInstance = readJson(RICH_INSTANCE_PATH);

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

const validateRich = ajv.compile(richSchema);
if (!validateRich(richInstance)) {
  console.error('copy:build — RICH validation FAILED:');
  for (const e of validateRich.errors ?? []) {
    console.error(`  ${e.instancePath || '/'} ${e.message}`);
  }
  process.exit(1);
}
console.log('  rich OK.');

// ── 2. Derive the FLAT schema (tree-walk; replace only leaf $refs) ────────────
const STRING_REF = '#/$defs/CopyString';
const LIST_REF = '#/$defs/CopyStringList';

function deriveFlat(node: JsonSchema): JsonSchema {
  if (node && typeof node === 'object' && typeof node.$ref === 'string') {
    if (node.$ref === STRING_REF) return { type: 'string' };
    if (node.$ref === LIST_REF) return { type: 'array', items: { type: 'string' } };
    throw new Error(`deriveFlat: unexpected $ref "${node.$ref}" — only CopyString/CopyStringList leaves are allowed`);
  }
  if (node && node.type === 'object' && node.properties) {
    const properties: JsonSchema = {};
    for (const [key, sub] of Object.entries(node.properties)) {
      properties[key] = deriveFlat(sub as JsonSchema);
    }
    const out: JsonSchema = { type: 'object' };
    if (node.title) out.title = node.title;
    if (node.description) out.description = node.description;
    out.properties = properties;
    if (Array.isArray(node.required)) out.required = [...node.required];
    if ('additionalProperties' in node) out.additionalProperties = node.additionalProperties;
    return out;
  }
  throw new Error(`deriveFlat: unexpected node shape ${JSON.stringify(node).slice(0, 160)}`);
}

console.log('copy:build — deriving flat schema...');
const flatSchema: JsonSchema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'https://lifegames.org/schemas/copy.identity.flat.schema.json',
  ...deriveFlat(richSchema),
  title: 'Identity',
};

// ── 3. Derive the FLAT instance (strip _meta, keep values) + round-trip guard ─
function isLeaf(n: any): boolean {
  return (
    n &&
    typeof n === 'object' &&
    !Array.isArray(n) &&
    Object.prototype.hasOwnProperty.call(n, 'value') &&
    Object.prototype.hasOwnProperty.call(n, '_meta')
  );
}
function flattenInstance(n: any): any {
  if (isLeaf(n)) return n.value;
  if (n && typeof n === 'object' && !Array.isArray(n)) {
    const out: any = {};
    for (const [key, val] of Object.entries(n)) out[key] = flattenInstance(val);
    return out;
  }
  return n;
}
const flatInstance = flattenInstance(richInstance);

const validateFlat = ajv.compile(flatSchema);
if (!validateFlat(flatInstance)) {
  console.error('copy:build — FLAT round-trip validation FAILED (derivation bug):');
  for (const e of validateFlat.errors ?? []) {
    console.error(`  ${e.instancePath || '/'} ${e.message}`);
  }
  process.exit(1);
}
console.log('  flat derivation + round-trip OK.');

// ── 4. Write JSON artifacts ───────────────────────────────────────────────────
ensureDir(DIST);
ensureDir(SWIFT_TARGET);
ensureDir(SWIFT_RESOURCES);

const flatSchemaJson = JSON.stringify(flatSchema, null, 2) + '\n';
const flatInstanceJson = JSON.stringify(flatInstance, null, 2) + '\n';
const FLAT_SCHEMA_PATH = join(DIST, 'identity.flat.schema.json');
writeFileSync(FLAT_SCHEMA_PATH, flatSchemaJson);
writeFileSync(join(DIST, 'identity.flat.json'), flatInstanceJson);

// ── 5. TS types ───────────────────────────────────────────────────────────────
console.log('copy:build — TS (json-schema-to-typescript)...');
const ts = await compile(flatSchema as Parameters<typeof compile>[0], 'Identity', {
  bannerComment: '',
  additionalProperties: false,
  declareExternallyReferenced: true,
  enableConstEnums: false,
  style: { singleQuote: true },
});
writeFileSync(join(DIST, 'identity.ts'), GEN_HEADER + ts);

// ── 6. Zod (validates the FLAT JSON the web collection reads) ──────────────────
console.log('copy:build — Zod (json-schema-to-zod)...');
let zod = jsonSchemaToZod(flatSchema, { name: 'identitySchema', module: 'esm' });
if (!zod.endsWith('\n')) zod += '\n';
writeFileSync(join(DIST, 'identity.zod.ts'), GEN_HEADER + zod);

// ── 7. Barrel (zero-dep main entry: typed flat identity; no Zod import) ────────
const barrel =
  GEN_HEADER +
  "import data from './identity.flat.json';\n" +
  "import type { Identity } from './identity';\n\n" +
  "export type { Identity } from './identity';\n\n" +
  'export const identity: Identity = data;\n';
writeFileSync(join(DIST, 'index.ts'), barrel);

// ── 8. Swift (quicktype over the flat schema) ─────────────────────────────────
console.log('copy:build — Swift (quicktype)...');
const QUICKTYPE_BIN = join(PKG_ROOT, 'node_modules', '.bin', 'quicktype');
const swiftTmp = join(DIST, '.identity.swift.tmp');
execFileSync(
  QUICKTYPE_BIN,
  [
    '--src-lang', 'schema',
    '--lang', 'swift',
    '--top-level', 'Identity',
    '--access-level', 'public',
    '--sendable',
    '-o', swiftTmp,
    FLAT_SCHEMA_PATH,
  ],
  { stdio: 'pipe' },
);
let swift = readFileSync(swiftTmp, 'utf-8');
rmSync(swiftTmp);
// Drop quicktype's leading comment banner (everything before the first import).
swift = swift.replace(/^[\s\S]*?(?=^import )/m, '').trimStart();
writeFileSync(join(SWIFT_TARGET, 'Identity.generated.swift'), GEN_HEADER + swift + (swift.endsWith('\n') ? '' : '\n'));

// ── 9. Resource (flat values shipped to device) ──────────────────────────────
writeFileSync(join(SWIFT_RESOURCES, 'identity.en-US.json'), flatInstanceJson);

console.log('copy:build — done.');
console.log('  dist/: identity.flat.schema.json, identity.flat.json, identity.ts, identity.zod.ts, index.ts');
console.log('  swift: Sources/LifegamesCopy/Identity.generated.swift (+ Resources/identity.en-US.json)');
