/**
 * THE NORMATIVE GRAMMAR for the component-contract catalog.
 *
 * This file is the SCHEMA. The files under `catalog/` are the SPEC. The split matters: the schema
 * says what a contract entry may look like, the spec says what the widgets actually are. Only the
 * schema is hand-written. Every entry in the spec is generated by `generate.mjs` from sources that
 * already exist in this repo, because a hand-authored second copy of a prop shape is the drift this
 * catalog exists to detect.
 *
 * Zero dependencies, on purpose. The gate that consumes this must run before any install step and
 * must not be able to fail for a reason unrelated to the contract.
 *
 * CATALOG_SPEC_VERSION discipline: the number below and `specVersion` in every entry AND in
 * `component-catalog-conformance.json` are one number. Bumping it means regenerating the catalog,
 * the conformance vectors, and the sha256 sidecar in a single change. `runner.mjs` case zero
 * asserts the implementation and the vectors agree on it, so a half-done bump reds immediately.
 */

export const CATALOG_SPEC_VERSION = 3

/**
 * The recursion cap on the `props` tree, and the reason the gate stays finite.
 *
 * The grammar owns this number rather than the generator, so the two cannot disagree: `generate.mjs`
 * imports it, stops descending at it, and marks the cut node `truncated: true`. A committed tree
 * deeper than the cap could not have been generated, so the grammar rejects it here rather than
 * letting a hand-edit smuggle in a shape the generator would never emit.
 *
 * 8 is chosen against the sources, not arbitrarily: the deepest pilot prop tree (bio-terminal's
 * `profile.terminalLines[].text`) is 4 levels, so the cap is slack for real widget props and still
 * bounds a self-referential type at a size a reader can hold.
 */
export const MAX_PROP_DEPTH = 8

/**
 * The widget groups this design system recognises. Mirrors `CATEGORIES` in
 * `packages/schemas/scripts/generate-widget-schemas.mjs` — a group outside this set means the
 * generator read a directory the schema generator does not know about.
 */
export const KNOWN_GROUPS = ['github', 'health', 'identity', 'location', 'other', 'reading']

/**
 * The two platforms this design system ships a widget to, in the order `platforms` must be sorted in.
 *
 * v3 admits a PARTIAL entry: a widget that exists on only one side. Before v3 every entry asserted
 * both, which is why the catalog could only hold the widgets that happened to be complete — the
 * web-only and Swift-only widgets were simply absent, and an absent widget reads as no gap at all.
 */
export const KNOWN_PLATFORMS = ['swift', 'web']

const REQUIRED_KEYS = [
  'specVersion',
  'widget',
  'group',
  'platforms',
  'props',
  'propsRef',
  'swiftPropsRef',
  'states',
  'a11y',
  'conformance',
  'generatedBy'
]

/** `sources` records where the generator READ each axis from. Provenance, not contract. */
const OPTIONAL_KEYS = ['sources']

const PROP_REQUIRED_KEYS = ['type', 'optional']
/** `truncated`, `properties` and `items` are shape-dependent: legal only on the node kinds below. */
const PROP_OPTIONAL_KEYS = ['truncated', 'properties', 'items']
const A11Y_KEYS = ['voiceOverLabel', 'ref']
const CONFORMANCE_KEYS = ['behavioralTest']

const KEBAB = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

const isPlainObject = (value) => typeof value === 'object' && value !== null && !Array.isArray(value)
const isNonEmptyString = (value) => typeof value === 'string' && value.length > 0
const show = (value) => (value === undefined ? 'undefined' : JSON.stringify(value))

/** Reject unknown keys AND report missing required ones, so a typo is a failure rather than a silent drop. */
function checkKeys(errors, label, object, required, optional) {
  const allowed = new Set([...required, ...optional])
  for (const key of required) {
    if (!Object.hasOwn(object, key)) {
      errors.push(`${label}: missing required field \`${key}\``)
    }
  }
  for (const key of Object.keys(object)) {
    if (!allowed.has(key)) {
      errors.push(`${label}: unknown field \`${key}\``)
    }
  }
}

/**
 * The type names a node declares, as a set, or `null` when `type` is malformed.
 *
 * Canonical form: a single type is a bare string, a union is an array of two or more UNIQUE names.
 * A one-element array and a duplicated member are both rejected — the generator collapses a
 * one-member union to a string and deduplicates, so either shape means the tree was hand-edited,
 * and two spellings of one type would make `properties`/`items` legality depend on the spelling.
 */
function propTypeNames(errors, label, type) {
  if (isNonEmptyString(type)) {
    return new Set([type])
  }
  const malformed = `${label}.type: expected a non-empty string or an array of two or more unique type names, got ${show(type)}`
  if (!Array.isArray(type)) {
    errors.push(malformed)
    return null
  }
  if (type.length < 2 || !type.every(isNonEmptyString) || new Set(type).size !== type.length) {
    errors.push(malformed)
    return null
  }
  return new Set(type)
}

/**
 * Validate one node of the recursive `props` tree.
 *
 * A node is `{type, optional}` plus, by kind: `properties` (a map of nodes) when the type set holds
 * `object`, `items` (one node) when it holds `array`, and `truncated: true` when the generator hit
 * MAX_PROP_DEPTH and stopped. Every conditional key is checked BOTH ways — present-and-illegal and
 * legal-but-malformed — because a `properties` map hanging off a `string` node is a shape a reader
 * would take at face value.
 *
 * `truncated: false` is rejected on the same rule as `a11y.voiceOverLabel: false`: absence is the
 * canonical way to say "not truncated", and a second spelling of the same fact is drift waiting to
 * happen. A truncated node carries no children — it is the record of children NOT walked.
 */
function checkPropNode(errors, label, node, depth) {
  if (!isPlainObject(node)) {
    errors.push(`${label}: expected an object, got ${show(node)}`)
    return
  }
  if (depth > MAX_PROP_DEPTH) {
    errors.push(`${label}: exceeds the maximum prop depth of ${MAX_PROP_DEPTH} — the generator truncates at that depth, so this tree was not generated`)
    return
  }

  checkKeys(errors, label, node, PROP_REQUIRED_KEYS, PROP_OPTIONAL_KEYS)

  const types = Object.hasOwn(node, 'type') ? propTypeNames(errors, label, node.type) : null

  if (Object.hasOwn(node, 'optional') && typeof node.optional !== 'boolean') {
    errors.push(`${label}.optional: expected a boolean, got ${show(node.optional)}`)
  }

  const truncated = Object.hasOwn(node, 'truncated')
  if (truncated && node.truncated !== true) {
    errors.push(`${label}.truncated: expected true or the field to be absent, got ${show(node.truncated)}`)
  }

  if (Object.hasOwn(node, 'properties')) {
    if (truncated) {
      errors.push(`${label}: is truncated but carries \`properties\` — a truncated node records children that were NOT walked`)
    } else if (types !== null && !types.has('object')) {
      errors.push(`${label}: has \`properties\` but its type is ${show(node.type)} — only an \`object\` node has properties`)
    } else if (!isPlainObject(node.properties)) {
      errors.push(`${label}.properties: expected a map of prop nodes, got ${show(node.properties)}`)
    } else {
      for (const name of Object.keys(node.properties)) {
        checkPropNode(errors, `${label}.properties.${name}`, node.properties[name], depth + 1)
      }
    }
  }

  if (Object.hasOwn(node, 'items')) {
    if (truncated) {
      errors.push(`${label}: is truncated but carries \`items\` — a truncated node records children that were NOT walked`)
    } else if (types !== null && !types.has('array')) {
      errors.push(`${label}: has \`items\` but its type is ${show(node.type)} — only an \`array\` node has items`)
    } else {
      checkPropNode(errors, `${label}.items`, node.items, depth + 1)
    }
  }
}

/**
 * `props` is the recursive tree, or `null` for a widget with no generated web schema.
 *
 * v3 admits the null. The props axis is read from `packages/schemas/generated/widgets/*.schema.json`,
 * which is itself generated from the WEB types, so a widget that ships only on Swift may have no
 * schema to read. `null` is the written gap; an empty `{}` would claim "this widget takes no props",
 * which is a different and checkable fact (four widgets in this repo really do take none).
 */
function checkProps(errors, props) {
  if (props === null) {
    return
  }
  if (!isPlainObject(props)) {
    errors.push(`props: expected an object or null, got ${show(props)}`)
    return
  }
  for (const name of Object.keys(props)) {
    checkPropNode(errors, `props.${name}`, props[name], 1)
  }
}

/**
 * The platform set: a non-empty, sorted, duplicate-free subset of KNOWN_PLATFORMS.
 *
 * Sortedness is a grammar rule rather than a generator habit because the field is a SET written as an
 * array — `["web","swift"]` and `["swift","web"]` are the same claim, and two spellings of one fact
 * make the committed bytes depend on iteration order instead of on the widget.
 */
function checkPlatforms(errors, platforms) {
  if (!Array.isArray(platforms)) {
    errors.push(`platforms: expected an array, got ${show(platforms)}`)
    return
  }
  if (platforms.length === 0) {
    errors.push('platforms: expected at least one of swift, web — a widget on neither platform is not a widget')
    return
  }
  const unknown = platforms.filter((platform) => !KNOWN_PLATFORMS.includes(platform))
  if (unknown.length > 0) {
    errors.push(`platforms: expected a subset of ${KNOWN_PLATFORMS.join(', ')}, got ${show(platforms)}`)
    return
  }
  if (new Set(platforms).size !== platforms.length) {
    errors.push(`platforms: duplicate entry in ${show(platforms)}`)
    return
  }
  const sorted = [...platforms].sort()
  if (platforms.some((platform, index) => platform !== sorted[index])) {
    errors.push(`platforms: expected ${show(sorted)}, got ${show(platforms)} — the set is written sorted so the bytes do not depend on read order`)
  }
}

/**
 * `states` may be EMPTY at v3.
 *
 * v2 rejected an empty array on the reasoning that a widget with no states has no renderable surface.
 * That held while the catalog covered three widgets that all had fixtures. Across the full set it
 * would force the generator to either throw on a widget with no fixture and no snapshot, or invent a
 * state name. An empty array is the honest third answer: nothing was found, and the catalog says so.
 */
function checkStates(errors, states) {
  if (!Array.isArray(states)) {
    errors.push(`states: expected an array, got ${show(states)}`)
    return
  }
  const seen = new Set()
  for (const state of states) {
    if (!isNonEmptyString(state)) {
      errors.push(`states: expected non-empty strings, got ${show(state)}`)
      continue
    }
    if (seen.has(state)) {
      errors.push(`states: duplicate state \`${state}\``)
    }
    seen.add(state)
  }
}

/**
 * `voiceOverLabel` is a three-valued axis collapsed to two: `true` (a label exists) or `null` (this
 * widget has none, a written gap). `false` is deliberately not accepted — an absent label is
 * unknown-until-audited, and a claimed label must cite where it lives, so `true` requires a `ref`.
 */
function checkA11y(errors, a11y) {
  if (!isPlainObject(a11y)) {
    errors.push(`a11y: expected an object, got ${show(a11y)}`)
    return
  }
  checkKeys(errors, 'a11y', a11y, A11Y_KEYS, [])
  const {voiceOverLabel, ref} = a11y
  if (voiceOverLabel !== null && voiceOverLabel !== true) {
    errors.push(`a11y.voiceOverLabel: expected true or null, got ${show(voiceOverLabel)}`)
  }
  if (ref !== null && !isNonEmptyString(ref)) {
    errors.push(`a11y.ref: expected a non-empty string or null, got ${show(ref)}`)
  }
  if (voiceOverLabel === true && ref === null) {
    errors.push('a11y: voiceOverLabel is true but ref is null — a claimed label must cite <file>:<line>')
  }
  if (voiceOverLabel === null && ref !== null && ref !== undefined) {
    errors.push(`a11y: voiceOverLabel is null but ref is ${show(ref)} — a gap cites nothing`)
  }
}

function checkConformance(errors, conformance) {
  if (!isPlainObject(conformance)) {
    errors.push(`conformance: expected an object, got ${show(conformance)}`)
    return
  }
  checkKeys(errors, 'conformance', conformance, CONFORMANCE_KEYS, [])
  const {behavioralTest} = conformance
  if (behavioralTest !== null && !isNonEmptyString(behavioralTest)) {
    errors.push(`conformance.behavioralTest: expected a non-empty string or null, got ${show(behavioralTest)}`)
  }
}

function checkSources(errors, sources) {
  if (!isPlainObject(sources)) {
    errors.push(`sources: expected an object, got ${show(sources)}`)
    return
  }
  for (const [axis, value] of Object.entries(sources)) {
    const values = Array.isArray(value) ? value : [value]
    if (values.length === 0) {
      errors.push(`sources.${axis}: expected at least one path`)
    }
    for (const path of values) {
      if (!isNonEmptyString(path)) {
        errors.push(`sources.${axis}: expected non-empty path strings, got ${show(path)}`)
      }
    }
  }
}

/**
 * Validate one catalog entry against the grammar.
 *
 * @param {unknown} entry a parsed `catalog/<widget>.contract.json`
 * @returns {{valid: boolean, errors: string[]}} every violation, not just the first
 */
export function validateEntry(entry) {
  const errors = []

  if (!isPlainObject(entry)) {
    return {valid: false, errors: [`entry: expected an object, got ${show(entry)}`]}
  }

  checkKeys(errors, 'entry', entry, REQUIRED_KEYS, OPTIONAL_KEYS)

  if (entry.specVersion !== CATALOG_SPEC_VERSION) {
    errors.push(`specVersion: expected ${CATALOG_SPEC_VERSION}, got ${show(entry.specVersion)}`)
  }

  if (!isNonEmptyString(entry.widget) || !KEBAB.test(entry.widget)) {
    errors.push(`widget: expected a non-empty kebab-case string, got ${show(entry.widget)}`)
  }

  if (!KNOWN_GROUPS.includes(entry.group)) {
    errors.push(`group: expected one of ${KNOWN_GROUPS.join(', ')}, got ${show(entry.group)}`)
  }

  checkPlatforms(errors, entry.platforms)
  checkProps(errors, entry.props)

  // The two refs are the auditable half of the contract, and either may be a written `null` at v3:
  // no web types file for a Swift-only widget, no dedicated Swift Props file for a widget that shares
  // one (five widgets in this repo do). An EMPTY STRING is still rejected — it reads as populated and
  // resolves to nothing.
  for (const key of ['propsRef', 'swiftPropsRef']) {
    if (entry[key] !== null && !isNonEmptyString(entry[key])) {
      errors.push(`${key}: expected a non-empty string or null, got ${show(entry[key])}`)
    }
  }

  if (!isNonEmptyString(entry.generatedBy)) {
    errors.push(`generatedBy: expected a non-empty string, got ${show(entry.generatedBy)}`)
  }

  checkStates(errors, entry.states)
  checkA11y(errors, entry.a11y)
  checkConformance(errors, entry.conformance)

  // ── v3 invariants: a partial entry must still be a CONTRACT ────────────────
  //
  // Admitting one-sided entries is what makes the catalog cover the whole widget set. It is also the
  // shape a broken source read produces, so the grammar pins the floor: an entry that records neither
  // a prop tree nor a Swift props file has nothing anyone could be held to, and would sit in the
  // catalog reading as covered. That is the exact failure this catalog exists to prevent.
  if (entry.props === null && entry.swiftPropsRef === null) {
    errors.push('entry: props is null and swiftPropsRef is null — an entry with neither a prop tree nor a Swift props file records no contract')
  }

  // `platforms` is a claim about which trees hold this widget, so it must agree with the refs read
  // from those trees. Without this coupling the field is decoration: nothing else in the entry
  // contradicts a wrong value.
  const platforms = Array.isArray(entry.platforms) ? entry.platforms : []
  if (isNonEmptyString(entry.propsRef) !== platforms.includes('web')) {
    errors.push(
      `entry: propsRef is ${show(entry.propsRef)} but platforms is ${show(entry.platforms)} — propsRef IS the web types file, so the two must agree`
    )
  }
  if (isNonEmptyString(entry.swiftPropsRef) && !platforms.includes('swift')) {
    errors.push(`entry: swiftPropsRef is ${show(entry.swiftPropsRef)} but platforms is ${show(entry.platforms)} — a Swift props file means a Swift platform`)
  }

  if (Object.hasOwn(entry, 'sources')) {
    checkSources(errors, entry.sources)
  }

  return {valid: errors.length === 0, errors}
}
