/**
 * THE NORMATIVE GRAMMAR for the component-contract catalog.
 *
 * This file is the SCHEMA. The files under `catalog/` are the SPEC. The split matters: the schema
 * says what a contract entry may look like, the spec says what the widgets actually are. Only the
 * schema is hand-written. Every entry in the spec is generated by `generate.mjs` from sources that
 * already exist in this repo, because a hand-authored second copy of a prop shape is the drift this
 * catalog exists to detect.
 *
 * Zero dependencies, on purpose. The gate that consumes this must run before any install step and
 * must not be able to fail for a reason unrelated to the contract.
 *
 * CATALOG_SPEC_VERSION discipline: the number below and `specVersion` in every entry AND in
 * `component-catalog-conformance.json` are one number. Bumping it means regenerating the catalog,
 * the conformance vectors, and the sha256 sidecar in a single change. `runner.mjs` case zero
 * asserts the implementation and the vectors agree on it, so a half-done bump reds immediately.
 */

export const CATALOG_SPEC_VERSION = 1

/**
 * The widget groups this design system recognises. Mirrors `CATEGORIES` in
 * `packages/schemas/scripts/generate-widget-schemas.mjs` — a group outside this set means the
 * generator read a directory the schema generator does not know about.
 */
export const KNOWN_GROUPS = ['github', 'health', 'identity', 'location', 'other', 'reading']

const REQUIRED_KEYS = [
  'specVersion',
  'widget',
  'group',
  'props',
  'propsRef',
  'swiftPropsRef',
  'states',
  'a11y',
  'conformance',
  'generatedBy'
]

/** `sources` records where the generator READ each axis from. Provenance, not contract. */
const OPTIONAL_KEYS = ['sources']

const PROP_KEYS = ['type', 'optional']
const A11Y_KEYS = ['voiceOverLabel', 'ref']
const CONFORMANCE_KEYS = ['behavioralTest']

const KEBAB = /^[a-z0-9]+(?:-[a-z0-9]+)*$/

const isPlainObject = (value) => typeof value === 'object' && value !== null && !Array.isArray(value)
const isNonEmptyString = (value) => typeof value === 'string' && value.length > 0
const show = (value) => (value === undefined ? 'undefined' : JSON.stringify(value))

/** Reject unknown keys AND report missing required ones, so a typo is a failure rather than a silent drop. */
function checkKeys(errors, label, object, required, optional) {
  const allowed = new Set([...required, ...optional])
  for (const key of required) {
    if (!Object.hasOwn(object, key)) {
      errors.push(`${label}: missing required field \`${key}\``)
    }
  }
  for (const key of Object.keys(object)) {
    if (!allowed.has(key)) {
      errors.push(`${label}: unknown field \`${key}\``)
    }
  }
}

function checkProps(errors, props) {
  if (!isPlainObject(props)) {
    errors.push(`props: expected an object, got ${show(props)}`)
    return
  }
  for (const [name, descriptor] of Object.entries(props)) {
    const label = `props.${name}`
    if (!isPlainObject(descriptor)) {
      errors.push(`${label}: expected an object, got ${show(descriptor)}`)
      continue
    }
    checkKeys(errors, label, descriptor, PROP_KEYS, [])
    if (Object.hasOwn(descriptor, 'type') && !isNonEmptyString(descriptor.type)) {
      errors.push(`${label}.type: expected a non-empty string, got ${show(descriptor.type)}`)
    }
    if (Object.hasOwn(descriptor, 'optional') && typeof descriptor.optional !== 'boolean') {
      errors.push(`${label}.optional: expected a boolean, got ${show(descriptor.optional)}`)
    }
  }
}

function checkStates(errors, states) {
  if (!Array.isArray(states)) {
    errors.push(`states: expected an array, got ${show(states)}`)
    return
  }
  if (states.length === 0) {
    errors.push('states: expected at least one state, got an empty array')
    return
  }
  const seen = new Set()
  for (const state of states) {
    if (!isNonEmptyString(state)) {
      errors.push(`states: expected non-empty strings, got ${show(state)}`)
      continue
    }
    if (seen.has(state)) {
      errors.push(`states: duplicate state \`${state}\``)
    }
    seen.add(state)
  }
}

/**
 * `voiceOverLabel` is a three-valued axis collapsed to two: `true` (a label exists) or `null` (this
 * widget has none, a written gap). `false` is deliberately not accepted — an absent label is
 * unknown-until-audited, and a claimed label must cite where it lives, so `true` requires a `ref`.
 */
function checkA11y(errors, a11y) {
  if (!isPlainObject(a11y)) {
    errors.push(`a11y: expected an object, got ${show(a11y)}`)
    return
  }
  checkKeys(errors, 'a11y', a11y, A11Y_KEYS, [])
  const {voiceOverLabel, ref} = a11y
  if (voiceOverLabel !== null && voiceOverLabel !== true) {
    errors.push(`a11y.voiceOverLabel: expected true or null, got ${show(voiceOverLabel)}`)
  }
  if (ref !== null && !isNonEmptyString(ref)) {
    errors.push(`a11y.ref: expected a non-empty string or null, got ${show(ref)}`)
  }
  if (voiceOverLabel === true && ref === null) {
    errors.push('a11y: voiceOverLabel is true but ref is null — a claimed label must cite <file>:<line>')
  }
  if (voiceOverLabel === null && ref !== null && ref !== undefined) {
    errors.push(`a11y: voiceOverLabel is null but ref is ${show(ref)} — a gap cites nothing`)
  }
}

function checkConformance(errors, conformance) {
  if (!isPlainObject(conformance)) {
    errors.push(`conformance: expected an object, got ${show(conformance)}`)
    return
  }
  checkKeys(errors, 'conformance', conformance, CONFORMANCE_KEYS, [])
  const {behavioralTest} = conformance
  if (behavioralTest !== null && !isNonEmptyString(behavioralTest)) {
    errors.push(`conformance.behavioralTest: expected a non-empty string or null, got ${show(behavioralTest)}`)
  }
}

function checkSources(errors, sources) {
  if (!isPlainObject(sources)) {
    errors.push(`sources: expected an object, got ${show(sources)}`)
    return
  }
  for (const [axis, value] of Object.entries(sources)) {
    const values = Array.isArray(value) ? value : [value]
    if (values.length === 0) {
      errors.push(`sources.${axis}: expected at least one path`)
    }
    for (const path of values) {
      if (!isNonEmptyString(path)) {
        errors.push(`sources.${axis}: expected non-empty path strings, got ${show(path)}`)
      }
    }
  }
}

/**
 * Validate one catalog entry against the grammar.
 *
 * @param {unknown} entry a parsed `catalog/<widget>.contract.json`
 * @returns {{valid: boolean, errors: string[]}} every violation, not just the first
 */
export function validateEntry(entry) {
  const errors = []

  if (!isPlainObject(entry)) {
    return {valid: false, errors: [`entry: expected an object, got ${show(entry)}`]}
  }

  checkKeys(errors, 'entry', entry, REQUIRED_KEYS, OPTIONAL_KEYS)

  if (entry.specVersion !== CATALOG_SPEC_VERSION) {
    errors.push(`specVersion: expected ${CATALOG_SPEC_VERSION}, got ${show(entry.specVersion)}`)
  }

  if (!isNonEmptyString(entry.widget) || !KEBAB.test(entry.widget)) {
    errors.push(`widget: expected a non-empty kebab-case string, got ${show(entry.widget)}`)
  }

  if (!KNOWN_GROUPS.includes(entry.group)) {
    errors.push(`group: expected one of ${KNOWN_GROUPS.join(', ')}, got ${show(entry.group)}`)
  }

  checkProps(errors, entry.props)

  for (const key of ['propsRef', 'swiftPropsRef', 'generatedBy']) {
    if (!isNonEmptyString(entry[key])) {
      errors.push(`${key}: expected a non-empty string, got ${show(entry[key])}`)
    }
  }

  checkStates(errors, entry.states)
  checkA11y(errors, entry.a11y)
  checkConformance(errors, entry.conformance)

  if (Object.hasOwn(entry, 'sources')) {
    checkSources(errors, entry.sources)
  }

  return {valid: errors.length === 0, errors}
}
